classdef TestFixedDecimatorSmoke < matlab.unittest.TestCase
    %% ==========================================================
    %% SMOKE TEST SUITE FOR ADC TO FIXED-POINT POLYPHASE DECIMATOR
    %% ==========================================================

    methods (Test)
        function testCompleteSignalGeneratorToFixedDecimatorFrameChain(testCase)
            %% Full smoke test through the encoded fixed-point DSP backend

            Config = EndToEndTestConfig();
            ADCParams = Config.ADCParams;
            DSPParams = Config.DSPParams;

            DcF = DSPParams.getValue("DcF");
            NumBits = ADCParams.getValue("NumBits");

            OldRngState = rng;
            CleanupObj = onCleanup(@() rng(OldRngState)); %#ok<NASGU>
            rng(177, "twister");

            %% ==========================================
            %% GENERATE ONE REPRODUCIBLE COMPLETE SOURCE SIGNAL
            %% ==========================================

            SG = SignalGenerator(ADCParams);
            CompleteInput = zeros(0, 1);

            while ~SG.IsDone()
                InputFrame = SG.GenNoisySignal();
                CompleteInput = ...
                    [CompleteInput; InputFrame]; %#ok<AGROW>
            end

            testCase.verifyEqual(numel(CompleteInput), 420);
            testCase.verifyTrue(SG.IsDone());

            %% ==========================================
            %% ONE-FRAME ADC REFERENCE
            %% ==========================================

            WholeFilter = ADCFilter(ADCParams);
            ExpectedHPFOutput = ...
                WholeFilter.ProcessHPFFrame(CompleteInput);
            ExpectedLPFOutput = ...
                WholeFilter.ProcessLPFFrame(ExpectedHPFOutput);

            WholeAGC = AGC(ADCParams);
            ExpectedAGCOutput = ...
                WholeAGC.GainControl(ExpectedLPFOutput);

            WholeADC = ADC(ADCParams);
            [ExpectedSampledOutput, ExpectedSampleIndex] = ...
                WholeADC.Sampler(ExpectedAGCOutput);
            [ExpectedQuantizedOutput, ExpectedQuantizerIndices] = ...
                WholeADC.Midtread(ExpectedSampledOutput);

            Encoder = ADCEncoder(ADCParams);
            [~, ExpectedTwosComplement] = ...
                Encoder.Encode(ExpectedQuantizerIndices);
            ExpectedADCInputCodes = ...
                int64(ExpectedTwosComplement(:));

            InputFormat.WL = NumBits;
            InputFormat.IWL = NumBits;
            InputFormat.FWL = 0;

            %% ==========================================
            %% CHARACTERIZE AND SELECT BOUNDED MAC FORMAT
            %% ==========================================

            ReferenceD = FixedDSPDecimator(DSPParams);

            CoefficientFormat.WL = ReferenceD.CoeffWL;
            CoefficientFormat.IWL = ReferenceD.CoeffIWL;
            CoefficientFormat.FWL = ReferenceD.CoeffFWL;

            [InPadded, NumBlocks] = ...
                ReferenceD.FixedPrepareInput(ExpectedADCInputCodes);

            [ReferenceCodes, ReferenceMACData] = ...
                ReferenceD.FixedDecimator( ...
                    InPadded, NumBlocks, ...
                    InputFormat, CoefficientFormat);

            MACFormat = FindMACFormat( ...
                InputFormat, ...
                CoefficientFormat, ...
                ReferenceD.BranchCoefficients, ...
                ReferenceMACData, ...
                1);

            [ExpectedLegacyCodes, ExpectedLegacyMACData] = ...
                ReferenceD.FixedDecimator( ...
                    InPadded, NumBlocks, ...
                    InputFormat, CoefficientFormat, MACFormat);

            %% ==========================================
            %% ONE-FRAME FIXED DSP STREAMING REFERENCE
            %% ==========================================

            WholeFrameD = FixedDSPDecimator(DSPParams);
            [ExpectedFixedCodes, ExpectedFixedMACData, ...
                ExpectedFixedFrameInfo] = WholeFrameD.ProcessFrame( ...
                    ExpectedADCInputCodes, true, ...
                    InputFormat, CoefficientFormat, MACFormat);

            testCase.verifyEqual(ExpectedFixedCodes, ReferenceCodes);
            testCase.verifyEqual(ExpectedFixedCodes, ExpectedLegacyCodes);
            testCase.verifyEqual( ...
                ExpectedFixedMACData, ExpectedLegacyMACData);

            %% ==========================================
            %% IRREGULAR HIGH-RATE FRAME PROCESSING
            %% ==========================================

            FrameFilter = ADCFilter(ADCParams);
            FrameAGC = AGC(ADCParams);
            FrameADC = ADC(ADCParams);
            FrameD = FixedDSPDecimator(DSPParams);

            FrameLengths = [29, 7, 64, 3, 111, 206];

            CompleteHPFOutput = zeros(0, 1);
            CompleteLPFOutput = zeros(0, 1);
            CompleteAGCOutput = zeros(0, 1);
            CompleteSampledOutput = zeros(0, 1);
            CompleteSampleIndex = zeros(0, 1);
            CompleteQuantizedOutput = zeros(0, 1);
            CompleteQuantizerIndices = zeros(0, 1);
            CompleteADCInputCodes = zeros(0, 1, 'int64');
            CompleteFixedCodes = zeros(1, 0, 'int64');
            CompleteFixedOutputIndex = zeros(0, 1);

            FinalMACData = [];
            FinalFrameInfo = [];
            StartIndex = 1;

            for k = 1:numel(FrameLengths)
                EndIndex = StartIndex + FrameLengths(k) - 1;
                InputFrame = CompleteInput(StartIndex:EndIndex);
                IsLastFrame = k == numel(FrameLengths);

                HPFOutputFrame = ...
                    FrameFilter.ProcessHPFFrame(InputFrame);
                LPFOutputFrame = ...
                    FrameFilter.ProcessLPFFrame(HPFOutputFrame);
                AGCOutputFrame = ...
                    FrameAGC.GainControl(LPFOutputFrame);

                [SampledOutputFrame, SampleIndexFrame] = ...
                    FrameADC.Sampler(AGCOutputFrame);

                [QuantizedOutputFrame, QuantizerIndexFrame] = ...
                    FrameADC.Midtread(SampledOutputFrame);

                [~, TwosComplementFrame] = ...
                    Encoder.Encode(QuantizerIndexFrame);

                ADCInputCodeFrame = ...
                    int64(TwosComplementFrame(:));

                [FixedCodeFrame, FinalMACData, FinalFrameInfo] = ...
                    FrameD.ProcessFrame( ...
                        ADCInputCodeFrame, IsLastFrame, ...
                        InputFormat, CoefficientFormat, MACFormat);

                CompleteHPFOutput = ...
                    [CompleteHPFOutput; HPFOutputFrame]; %#ok<AGROW>
                CompleteLPFOutput = ...
                    [CompleteLPFOutput; LPFOutputFrame]; %#ok<AGROW>
                CompleteAGCOutput = ...
                    [CompleteAGCOutput; AGCOutputFrame]; %#ok<AGROW>
                CompleteSampledOutput = ...
                    [CompleteSampledOutput; SampledOutputFrame]; %#ok<AGROW>
                CompleteSampleIndex = ...
                    [CompleteSampleIndex; SampleIndexFrame]; %#ok<AGROW>
                CompleteQuantizedOutput = ...
                    [CompleteQuantizedOutput; ...
                     QuantizedOutputFrame]; %#ok<AGROW>
                CompleteQuantizerIndices = ...
                    [CompleteQuantizerIndices; ...
                     QuantizerIndexFrame]; %#ok<AGROW>
                CompleteADCInputCodes = ...
                    [CompleteADCInputCodes; ADCInputCodeFrame]; %#ok<AGROW>
                CompleteFixedCodes = ...
                    [CompleteFixedCodes, FixedCodeFrame]; %#ok<AGROW>
                CompleteFixedOutputIndex = [ ...
                    CompleteFixedOutputIndex; ...
                    FinalFrameInfo.OutputSampleIndex]; %#ok<AGROW>

                StartIndex = EndIndex + 1;
            end

            %% ==========================================
            %% VERIFY EVERY HANDOFF AND TERMINAL STATE
            %% ==========================================

            testCase.verifyEqual( ...
                CompleteHPFOutput, ExpectedHPFOutput, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                CompleteLPFOutput, ExpectedLPFOutput, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                CompleteAGCOutput, ExpectedAGCOutput, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                CompleteSampledOutput, ExpectedSampledOutput, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                CompleteSampleIndex, ExpectedSampleIndex);
            testCase.verifyEqual( ...
                CompleteQuantizedOutput, ExpectedQuantizedOutput);
            testCase.verifyEqual( ...
                CompleteQuantizerIndices, ExpectedQuantizerIndices);
            testCase.verifyEqual( ...
                CompleteADCInputCodes, ExpectedADCInputCodes);
            testCase.verifyEqual( ...
                CompleteFixedCodes, ExpectedFixedCodes);
            testCase.verifyEqual( ...
                FinalMACData, ExpectedFixedMACData);
            testCase.verifyEqual( ...
                CompleteFixedOutputIndex, (0:NumBlocks-1)');

            testCase.verifyEqual( ...
                FrameFilter.HPFState, WholeFilter.HPFState, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                FrameFilter.LPFState, WholeFilter.LPFState, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                FrameAGC.Envelope, WholeAGC.Envelope, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                FrameAGC.Gain, WholeAGC.Gain, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                FrameAGC.GateGain, WholeAGC.GateGain, ...
                "AbsTol", 1e-12);

            testCase.verifyEqual( ...
                FrameAGC.SamplesProcessed, numel(CompleteInput));
            testCase.verifyEqual( ...
                FrameAGC.FramesProcessed, numel(FrameLengths));
            testCase.verifyEqual( ...
                FrameD.DelayLines, WholeFrameD.DelayLines);
            testCase.verifyEqual( ...
                FrameD.CumulativeMACData, ExpectedFixedMACData);

            ExpectedPadding = mod( ...
                DcF - mod(numel(ExpectedADCInputCodes), DcF), DcF);

            ExpectedOutputCount = ...
                ceil(numel(ExpectedADCInputCodes) / DcF);

            testCase.verifyEqual( ...
                FinalFrameInfo.NumPaddingSamples, ExpectedPadding);
            testCase.verifyEqual( ...
                ExpectedFixedFrameInfo.NumPaddingSamples, ...
                ExpectedPadding);
            testCase.verifyEqual( ...
                numel(CompleteFixedCodes), ExpectedOutputCount);
            testCase.verifyEqual( ...
                FrameD.OutputSamplesProduced, ExpectedOutputCount);
            testCase.verifyEqual( ...
                FrameD.InputSamplesReceived, ...
                numel(ExpectedADCInputCodes));
            testCase.verifyEqual( ...
                FrameADC.InputSamplesProcessed, numel(CompleteInput));
            testCase.verifyEqual( ...
                FrameADC.OutputSamplesProduced, ...
                numel(ExpectedSampledOutput));
            testCase.verifyEqual( ...
                FrameADC.FramesProcessed, numel(FrameLengths));
            testCase.verifyEqual( ...
                FrameD.FramesProcessed, numel(FrameLengths));
            testCase.verifyTrue(FinalFrameInfo.StreamFinalized);
            testCase.verifyTrue(FrameD.StreamFinalized);
        end
    end
end
