classdef SamplerAnalyzer < handle
    %% =======================================================
    %% IDEAL FRAME-BASED ADC SAMPLER PERFORMANCE VISUALIZATION
    %% =======================================================
    % Plotting is deliberately kept separate from RunDemoSampler's
    % numerical compliance decisions. The existing SpectrumAnalyzer
    % supplies the spectra; this class only presents the two approved
    % sampler figures.

    properties (SetAccess = private)
        Parameters
    end

    methods
        function obj = SamplerAnalyzer(P)
            %% ===========================
            %% SAMPLER ANALYZER CONSTRUCTOR
            %% ===========================
            obj.Parameters = P;
        end

        function PlotSamplingOperation( ...
                obj, InputTime, InputSignal, ...
                SampleTime, SampledSignal, SampleIndex)
            %% =====================================================
            %% PLOT HIGH-RATE AGC OUTPUT AND RETAINED ADC-RATE SAMPLES
            %% =====================================================

            InputTime = InputTime(:);
            InputSignal = InputSignal(:);
            SampleTime = SampleTime(:);
            SampledSignal = SampledSignal(:);
            SampleIndex = SampleIndex(:);

            if numel(InputTime) ~= numel(InputSignal) || ...
                    numel(SampleTime) ~= numel(SampledSignal) || ...
                    numel(SampleTime) ~= numel(SampleIndex)
                error('SamplerAnalyzer:TimeSignalLengthMismatch', ...
                    ['Each sampler time/index vector must match its ', ...
                     'corresponding signal vector.']);
            end

            if isempty(InputTime) || isempty(SampleTime)
                error('SamplerAnalyzer:EmptySignal', ...
                    'Sampler plots require nonempty input and output signals.');
            end

            InputSamplingFrequency = ...
                obj.Parameters.getValue("Fs");
            DownsamplingFactor = ...
                obj.Parameters.getValue("DF");
            ADCSamplingFrequency = ...
                InputSamplingFrequency / DownsamplingFactor;

            % Twelve cycles around the Gaussian-burst centre expose the
            % one-in-four sampling pattern without reducing the waveform
            % to an unreadable solid trace.
            DesiredFrequency = ...
                obj.Parameters.getValue("FData");
            PlotCentreTime = ...
                obj.Parameters.getValue("mu");
            PlotDuration = 12 / DesiredFrequency;

            PlotStartTime = max( ...
                InputTime(1), PlotCentreTime - PlotDuration / 2);
            PlotEndTime = min( ...
                InputTime(end), PlotCentreTime + PlotDuration / 2);

            InputPlotMask = ...
                InputTime >= PlotStartTime & InputTime <= PlotEndTime;
            SamplePlotMask = ...
                SampleTime >= PlotStartTime & SampleTime <= PlotEndTime;

            if ~any(InputPlotMask) || ~any(SamplePlotMask)
                error('SamplerAnalyzer:EmptyPlotWindow', ...
                    'The selected sampler display interval is empty.');
            end

            figure( ...
                "Name", "Sampler - Time-Domain Sampling Operation", ...
                "Color", "w");

            plot( ...
                InputTime(InputPlotMask) * 1e6, ...
                InputSignal(InputPlotMask), ...
                "LineWidth", 1.1, ...
                "DisplayName", sprintf( ...
                    "AGC output reference (%.1f GS/s)", ...
                    InputSamplingFrequency / 1e9));
            hold on;

            stem( ...
                SampleTime(SamplePlotMask) * 1e6, ...
                SampledSignal(SamplePlotMask), ...
                "Marker", "o", ...
                "MarkerSize", 4, ...
                "LineWidth", 0.9, ...
                "DisplayName", sprintf( ...
                    "Retained ADC samples (%.1f GS/s)", ...
                    ADCSamplingFrequency / 1e9));

            grid on;
            xlim([PlotStartTime, PlotEndTime] * 1e6);
            xlabel("Time (microseconds)");
            ylabel("Amplitude (V)");
            title(sprintf( ...
                "Ideal Sampling: Retain One of Every %d Input Samples", ...
                DownsamplingFactor));

            VisibleIndices = SampleIndex(SamplePlotMask);
            subtitle(sprintf( ...
                "Global source indices %d:%d:%d; clock jitter excluded", ...
                VisibleIndices(1), ...
                DownsamplingFactor, ...
                VisibleIndices(end)));

            legend("Location", "best");
            hold off;
        end

        function PlotSpectralComparison(obj, PlotData)
            %% ======================================================
            %% PLOT DESIRED-TONE PRESERVATION AND INTERFERENCE FOLDING
            %% ======================================================

            RequiredFields = [ ...
                "InputFFTFrequency"; ...
                "InputMagnitude"; ...
                "OutputFFTFrequency"; ...
                "OutputMagnitude"; ...
                "CommonPSDFrequency"; ...
                "InputCommonPSD"; ...
                "OutputPSD"; ...
                "DesiredFrequencies"; ...
                "InputInterferenceFrequency"; ...
                "OutputAliasFrequency"; ...
                "ADCSamplingFrequency"];

            for k = 1:numel(RequiredFields)
                if ~isfield(PlotData, RequiredFields(k))
                    error('SamplerAnalyzer:MissingPlotData', ...
                        'PlotData.%s is required.', RequiredFields(k));
                end
            end

            InputFFTFrequency = PlotData.InputFFTFrequency(:);
            InputMagnitude = PlotData.InputMagnitude(:);
            OutputFFTFrequency = PlotData.OutputFFTFrequency(:);
            OutputMagnitude = PlotData.OutputMagnitude(:);
            CommonPSDFrequency = PlotData.CommonPSDFrequency(:);
            InputCommonPSD = PlotData.InputCommonPSD(:);
            OutputPSD = PlotData.OutputPSD(:);
            DesiredFrequencies = PlotData.DesiredFrequencies(:);

            if numel(InputFFTFrequency) ~= numel(InputMagnitude) || ...
                    numel(OutputFFTFrequency) ~= numel(OutputMagnitude) || ...
                    numel(CommonPSDFrequency) ~= numel(InputCommonPSD) || ...
                    numel(CommonPSDFrequency) ~= numel(OutputPSD)
                error('SamplerAnalyzer:PlotDataLengthMismatch', ...
                    'Each spectral axis must match its corresponding data.');
            end

            if numel(DesiredFrequencies) ~= 2
                error('SamplerAnalyzer:InvalidDesiredFrequencies', ...
                    'Exactly two desired frequencies are required.');
            end

            InputMagnitude_dBV = ...
                20 * log10(max(InputMagnitude, realmin("double")));
            OutputMagnitude_dBV = ...
                20 * log10(max(OutputMagnitude, realmin("double")));
            InputPSD_dB = ...
                10 * log10(max(InputCommonPSD, realmin("double")));
            OutputPSD_dB = ...
                10 * log10(max(OutputPSD, realmin("double")));

            ADCSamplingFrequency = PlotData.ADCSamplingFrequency;
            ADCNyquistFrequency = ADCSamplingFrequency / 2;

            figure( ...
                "Name", "Sampler - Spectral Preservation and Aliasing", ...
                "Color", "w");

            SpectrumLayout = tiledlayout(3, 1, ...
                "TileSpacing", "compact", ...
                "Padding", "compact");


            %% MATCHED-TIME WELCH PSD IN THE ADC NYQUIST BAND

            nexttile;

            plot( ...
                CommonPSDFrequency / 1e9, ...
                InputPSD_dB, ...
                "LineWidth", 1.1, ...
                "DisplayName", "Before sampler");
            hold on;
            plot( ...
                CommonPSDFrequency / 1e9, ...
                OutputPSD_dB, ...
                "--", ...
                "LineWidth", 1.1, ...
                "DisplayName", "After sampler");

            xline( ...
                PlotData.OutputAliasFrequency / 1e9, ...
                ":", ...
                "Predicted alias", ...
                "HandleVisibility", "off");

            grid on;
            xlim([0, ADCNyquistFrequency / 1e9]);
            xlabel("Frequency (GHz)");
            ylabel("PSD (dBV^2/Hz)");
            title("Matched-Time Hamming-Welch PSD: Common 0-5 GHz Band");
            legend("Location", "best");
            hold off;


            %% DATA 1 / DATA 2 HAMMING-FFT PRESERVATION

            nexttile;

            plot( ...
                InputFFTFrequency / 1e9, ...
                InputMagnitude_dBV, ...
                "LineWidth", 1.1, ...
                "DisplayName", "Before sampler");
            hold on;
            plot( ...
                OutputFFTFrequency / 1e9, ...
                OutputMagnitude_dBV, ...
                "--", ...
                "LineWidth", 1.1, ...
                "DisplayName", "After sampler");

            xline(DesiredFrequencies(1) / 1e9, ":", "Data 1", ...
                "HandleVisibility", "off");
            xline(DesiredFrequencies(2) / 1e9, ":", "Data 2", ...
                "HandleVisibility", "off");

            ToneSpan = max( ...
                5e6, 5 * abs(diff(DesiredFrequencies)));
            ToneCentre = mean(DesiredFrequencies);

            grid on;
            xlim((ToneCentre + [-ToneSpan, ToneSpan]) / 1e9);
            xlabel("Frequency (GHz)");
            ylabel("Magnitude (dBV)");
            title("Hamming FFT: Data 1 and Data 2 Preservation");
            legend("Location", "best");
            hold off;


            %% INTERFERER-TO-ALIAS FOLDING

            nexttile;

            plot( ...
                InputFFTFrequency / 1e9, ...
                InputMagnitude_dBV, ...
                "LineWidth", 1.1, ...
                "DisplayName", "Before sampler");
            hold on;
            plot( ...
                OutputFFTFrequency / 1e9, ...
                OutputMagnitude_dBV, ...
                "--", ...
                "LineWidth", 1.1, ...
                "DisplayName", "After sampler");

            xline( ...
                PlotData.InputInterferenceFrequency / 1e9, ...
                ":", ...
                "Input interferer", ...
                "HandleVisibility", "off");
            xline( ...
                PlotData.OutputAliasFrequency / 1e9, ...
                ":", ...
                "Predicted alias", ...
                "HandleVisibility", "off");
            xline( ...
                ADCNyquistFrequency / 1e9, ...
                "-.", ...
                "ADC Nyquist", ...
                "HandleVisibility", "off");

            AliasPlotLower = max( ...
                0, PlotData.OutputAliasFrequency - 0.4e9);
            AliasPlotUpper = ...
                PlotData.InputInterferenceFrequency + 0.4e9;

            grid on;
            xlim([AliasPlotLower, AliasPlotUpper] / 1e9);
            xlabel("Frequency (GHz)");
            ylabel("Magnitude (dBV)");
            title(sprintf( ...
                "Hamming FFT: %.3f GHz Folds to %.3f GHz", ...
                PlotData.InputInterferenceFrequency / 1e9, ...
                PlotData.OutputAliasFrequency / 1e9));
            legend("Location", "best");
            hold off;

            title(SpectrumLayout, ...
                "Received-Signal Preservation Through Ideal ADC Sampling");
        end
    end
end
