function Metrics = MeasurePolyphaseComputation( ...
    FilterLength, DecimationFactor, RectangularBranchSlots)
%% ==========================================
%% MEASURE POLYPHASE MAC REQUIREMENTS
%% ==========================================
%
% Direct FIR filtering calculates every full-rate output before
% downsampling. Polyphase filtering calculates only the retained outputs.

    validateattributes(FilterLength, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'integer', 'positive'});

    validateattributes(DecimationFactor, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'integer', 'positive'});

    validateattributes(RectangularBranchSlots, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'integer', 'positive'});

    if RectangularBranchSlots < FilterLength
        error('MeasurePolyphaseComputation:InsufficientStorage', ...
            ['RectangularBranchSlots cannot be smaller than ', ...
             'FilterLength.']);
    end

    DirectMACsPerInputSample = FilterLength;

    IdealPolyphaseMACsPerInputSample = ...
        FilterLength / DecimationFactor;

    ImplementedMACsPerInputSample = ...
        RectangularBranchSlots / DecimationFactor;

    Metrics.DirectMACsPerInputSample = ...
        DirectMACsPerInputSample;

    Metrics.IdealPolyphaseMACsPerInputSample = ...
        IdealPolyphaseMACsPerInputSample;

    Metrics.ImplementedMACsPerInputSample = ...
        ImplementedMACsPerInputSample;

    Metrics.PaddingMACsPerOutputSample = ...
        RectangularBranchSlots - FilterLength;

    Metrics.IdealMACReductionPercent = ...
        100 * (1 - ...
        IdealPolyphaseMACsPerInputSample / ...
        DirectMACsPerInputSample);

    Metrics.ImplementedMACReductionPercent = ...
        100 * (1 - ...
        ImplementedMACsPerInputSample / ...
        DirectMACsPerInputSample);
end
