function Metrics = MeasureCoefficientFixedPointDesign(FixedDecimator)
%% =====================================================
%% MEASURE FIXED-POINT COEFFICIENT DESIGN CHARACTERISTICS
%% =====================================================

    RequiredProperties = { ...
        'FilterCoefficients', ...
        'FixedFilterCoefficients', ...
        'CoeffWL', ...
        'CoeffIWL', ...
        'CoeffFWL', ...
        'CoeffScale'};

    if ~isobject(FixedDecimator)
        error('MeasureCoefficientFixedPointDesign:InvalidDecimator', ...
            'FixedDecimator must be a fixed-decimator object.');
    end

    for k = 1:numel(RequiredProperties)
        if ~isprop(FixedDecimator, RequiredProperties{k})
            error( ...
                'MeasureCoefficientFixedPointDesign:MissingProperty', ...
                'FixedDecimator must provide the %s property.', ...
                RequiredProperties{k});
        end
    end

    FormatValues = [ ...
        FixedDecimator.CoeffWL, ...
        FixedDecimator.CoeffIWL, ...
        FixedDecimator.CoeffFWL];

    ValidFormat = ...
        isnumeric(FormatValues) && ...
        isreal(FormatValues) && ...
        all(isfinite(FormatValues)) && ...
        all(FormatValues >= 0) && ...
        all(FormatValues == floor(FormatValues)) && ...
        FixedDecimator.CoeffIWL >= 1 && ...
        FixedDecimator.CoeffWL == ...
        FixedDecimator.CoeffIWL + FixedDecimator.CoeffFWL;

    if ~ValidFormat
        error( ...
            'MeasureCoefficientFixedPointDesign:InvalidFormat', ...
            'The fixed coefficient WL, IWL, and FWL are inconsistent.');
    end

    validateattributes(FixedDecimator.CoeffScale, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});

    if FixedDecimator.CoeffScale ~= 2^FixedDecimator.CoeffFWL
        error( ...
            'MeasureCoefficientFixedPointDesign:ScaleMismatch', ...
            'CoeffScale must equal 2^CoeffFWL.');
    end

    FloatingCoefficients = ...
        double(FixedDecimator.FilterCoefficients(:));

    FixedCoefficientCodes = ...
        double(FixedDecimator.FixedFilterCoefficients(:));

    if isempty(FloatingCoefficients) || ...
            any(~isfinite(FloatingCoefficients)) || ...
            any(~isfinite(FixedCoefficientCodes))

        error( ...
            'MeasureCoefficientFixedPointDesign:InvalidCoefficients', ...
            'Floating and fixed coefficients must be finite vectors.');
    end

    if numel(FloatingCoefficients) ~= numel(FixedCoefficientCodes)
        error( ...
            'MeasureCoefficientFixedPointDesign:LengthMismatch', ...
            ['Floating and fixed coefficient representations must ', ...
             'have equal lengths.']);
    end

    QuantizedCoefficients = ...
        FixedCoefficientCodes / FixedDecimator.CoeffScale;

    CoefficientError = ...
        QuantizedCoefficients - FloatingCoefficients;

    Metrics.Format.WL = FixedDecimator.CoeffWL;
    Metrics.Format.IWL = FixedDecimator.CoeffIWL;
    Metrics.Format.FWL = FixedDecimator.CoeffFWL;
    Metrics.Format.Scale = FixedDecimator.CoeffScale;

    % FindCoefficientFormat searches upward from FWL = 0 and selects the
    % first candidate satisfying both passband and stopband specifications.
    Metrics.MinimumPassingFWL = FixedDecimator.CoeffFWL;

    Metrics.RMSError = ...
        sqrt(mean(CoefficientError.^2));

    Metrics.MaximumAbsoluteError = ...
        max(abs(CoefficientError));
end
