function Metrics = MeasureMACFixedPointDesign( ...
    InputFormat, MACFormat, MACData)
%% ================================================
%% MEASURE FIXED-POINT MAC DESIGN CHARACTERISTICS
%% ================================================

    ValidateFormat(InputFormat, 'InputFormat');
    ValidateFormat(MACFormat, 'MACFormat');

    RequiredMACFormatFields = { ...
        'ProductWL', ...
        'ProductIWL', ...
        'ProductFWL', ...
        'RoundingMethod', ...
        'OverflowAction', ...
        'HeadroomBits', ...
        'RequiredMagnitude', ...
        'AnalyticalFinalBound', ...
        'GuardBits', ...
        'ReferenceContainerWL'};

    RequireFields( ...
        MACFormat, RequiredMACFormatFields, 'MACFormat');

    RequiredMACDataFields = { ...
        'ProductFormat', ...
        'AccumulatorFormat', ...
        'FinalAccumulator', ...
        'ProductCastOverflowCount', ...
        'BranchAccumulatorOverflowCount', ...
        'FinalAccumulatorOverflowCount'};

    RequireFields(MACData, RequiredMACDataFields, 'MACData');
    RequireFields( ...
        MACData.FinalAccumulator, {'MaxAbsCode'}, ...
        'MACData.FinalAccumulator');

    ValidateFormat(MACData.ProductFormat, 'MACData.ProductFormat');
    ValidateFormat( ...
        MACData.AccumulatorFormat, 'MACData.AccumulatorFormat');

    if MACData.AccumulatorFormat.WL ~= MACFormat.WL || ...
            MACData.AccumulatorFormat.IWL ~= MACFormat.IWL || ...
            MACData.AccumulatorFormat.FWL ~= MACFormat.FWL

        error('MeasureMACFixedPointDesign:FormatMismatch', ...
            ['MACData.AccumulatorFormat must match the selected ', ...
             'MACFormat.']);
    end

    ProductFormat.WL = MACFormat.ProductWL;
    ProductFormat.IWL = MACFormat.ProductIWL;
    ProductFormat.FWL = MACFormat.ProductFWL;
    ValidateFormat(ProductFormat, 'ProductFormat');

    ProductCastOverflowCount = ...
        double(MACData.ProductCastOverflowCount);

    BranchOverflowCount = ...
        double(MACData.BranchAccumulatorOverflowCount);

    FinalOverflowCount = ...
        double(MACData.FinalAccumulatorOverflowCount);

    TotalOverflowEventCount = ...
        ProductCastOverflowCount + ...
        BranchOverflowCount + ...
        FinalOverflowCount;

    Metrics.InputFormat = InputFormat;
    Metrics.ProductFormat = ProductFormat;

    Metrics.AccumulatorFormat.WL = MACFormat.WL;
    Metrics.AccumulatorFormat.IWL = MACFormat.IWL;
    Metrics.AccumulatorFormat.FWL = MACFormat.FWL;

    Metrics.MinimumSafeAccumulatorIWL = ...
        MACFormat.IWL - MACFormat.HeadroomBits;

    Metrics.ConfiguredHeadroomBits = MACFormat.HeadroomBits;
    Metrics.GuardBits = MACFormat.GuardBits;
    Metrics.ReferenceContainerWL = MACFormat.ReferenceContainerWL;

    Metrics.ProductFractionBitsRemoved = ...
        MACFormat.ProductFWL - MACFormat.FWL;

    Metrics.RequiredMagnitude = MACFormat.RequiredMagnitude;
    Metrics.AnalyticalFinalBound = MACFormat.AnalyticalFinalBound;

    Metrics.AccumulatorFullScaleMagnitude = ...
        2^(MACFormat.IWL - 1);

    Metrics.ObservedFinalMaxAbs = ...
        double(MACData.FinalAccumulator.MaxAbsCode) * ...
        2^(-MACFormat.FWL);

    Metrics.RoundingMethod = string(MACFormat.RoundingMethod);
    Metrics.OverflowAction = string(MACFormat.OverflowAction);

    Metrics.ProductCastOverflowCount = ...
        ProductCastOverflowCount;
    Metrics.BranchAccumulatorOverflowCount = ...
        BranchOverflowCount;
    Metrics.FinalAccumulatorOverflowCount = ...
        FinalOverflowCount;
    Metrics.TotalOverflowEventCount = ...
        TotalOverflowEventCount;
    Metrics.NoOverflowObserved = ...
        TotalOverflowEventCount == 0;
end

function ValidateFormat(Format, FormatName)
%% ==========================================
%% VALIDATE WL / IWL / FWL FORMAT STRUCTURE
%% ==========================================

    RequireFields(Format, {'WL', 'IWL', 'FWL'}, FormatName);

    Values = [Format.WL, Format.IWL, Format.FWL];

    ValidValues = ...
        isnumeric(Values) && ...
        isreal(Values) && ...
        all(isfinite(Values)) && ...
        all(Values >= 0) && ...
        all(Values == floor(Values));

    if ~ValidValues || Format.IWL < 1 || ...
            Format.WL ~= Format.IWL + Format.FWL

        error('MeasureMACFixedPointDesign:InvalidFormat', ...
            ['%s must contain integer WL, IWL, and FWL values ', ...
             'satisfying WL = IWL + FWL.'], ...
            FormatName);
    end
end

function RequireFields(InputStruct, RequiredFields, StructName)
%% ==========================================
%% REQUIRE NAMED STRUCTURE FIELDS
%% ==========================================

    if ~isstruct(InputStruct) || ~isscalar(InputStruct)
        error('MeasureMACFixedPointDesign:InvalidStructure', ...
            '%s must be a scalar structure.', StructName);
    end

    for k = 1:numel(RequiredFields)
        if ~isfield(InputStruct, RequiredFields{k})
            error('MeasureMACFixedPointDesign:MissingField', ...
                '%s must contain the %s field.', ...
                StructName, RequiredFields{k});
        end
    end
end
