function Metrics = MeasurePolyphaseStructure(Decimator)
%% ================================================
%% MEASURE POLYPHASE BRANCH STRUCTURE AND STORAGE
%% ================================================

    RequiredProperties = { ...
        'DcF', ...
        'FilterCoefficients', ...
        'BranchCoefficients'};

    if ~isobject(Decimator)
        error('MeasurePolyphaseStructure:InvalidDecimator', ...
            'Decimator must be a floating- or fixed-decimator object.');
    end

    for k = 1:numel(RequiredProperties)
        if ~isprop(Decimator, RequiredProperties{k})
            error('MeasurePolyphaseStructure:MissingProperty', ...
                'Decimator must provide the %s property.', ...
                RequiredProperties{k});
        end
    end

    FilterCoefficients = Decimator.FilterCoefficients;
    BranchCoefficients = Decimator.BranchCoefficients;
    DecimationFactor = double(Decimator.DcF);

    ValidFilter = ...
        isnumeric(FilterCoefficients) && ...
        isreal(FilterCoefficients) && ...
        isvector(FilterCoefficients) && ...
        ~isempty(FilterCoefficients) && ...
        all(isfinite(double(FilterCoefficients(:))));

    if ~ValidFilter
        error('MeasurePolyphaseStructure:InvalidFilter', ...
            'FilterCoefficients must be a finite real numeric vector.');
    end

    ValidBranches = ...
        isnumeric(BranchCoefficients) && ...
        isreal(BranchCoefficients) && ...
        ismatrix(BranchCoefficients) && ...
        ~isempty(BranchCoefficients) && ...
        all(isfinite(double(BranchCoefficients(:))));

    if ~ValidBranches
        error('MeasurePolyphaseStructure:InvalidBranches', ...
            'BranchCoefficients must be a finite real numeric matrix.');
    end

    validateattributes(DecimationFactor, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'integer', 'positive'});

    FilterLength = numel(FilterCoefficients);
    NumberBranches = size(BranchCoefficients, 1);
    LongestBranchLength = size(BranchCoefficients, 2);

    if NumberBranches ~= DecimationFactor
        error('MeasurePolyphaseStructure:BranchCountMismatch', ...
            ['The number of polyphase branches must equal the ', ...
             'decimation factor.']);
    end

    RectangularBranchSlots = ...
        NumberBranches * LongestBranchLength;

    if RectangularBranchSlots < FilterLength
        error('MeasurePolyphaseStructure:InsufficientStorage', ...
            ['The branch matrix cannot contain every prototype ', ...
             'FIR coefficient.']);
    end

    PhaseIndex = 0:DecimationFactor-1;

    BranchTapCounts = max( ...
        0, ...
        floor((FilterLength - 1 - PhaseIndex) / ...
        DecimationFactor) + 1);

    Metrics.FilterLength = FilterLength;
    Metrics.DecimationFactor = DecimationFactor;
    Metrics.NumberBranches = NumberBranches;
    Metrics.BranchTapCounts = BranchTapCounts;
    Metrics.LongestBranchLength = LongestBranchLength;
    Metrics.RectangularBranchSlots = RectangularBranchSlots;
    Metrics.PaddingSlots = RectangularBranchSlots - FilterLength;
end
