function State = RunDemoLPF(State, ShowPlots)
%% =======================================================
%% ANTI-ALIASING LOW-PASS FILTER DEMONSTRATION
%% =======================================================
% Process the HPF output through the frame-based LPF, verify the approved
% anti-aliasing requirements, and pass the filtered signal to the next
% approved stage through State.CurrentSignal.


    %% ==========================================
    %% VALIDATE INTERSTAGE INPUT CONTRACT
    %% ==========================================

    if nargin < 1 || nargin > 2 || ~isstruct(State)
        error('RunDemoLPF:InvalidState', ...
            ['RunDemoLPF requires a State structure input and an ', ...
             'optional logical ShowPlots input.']);
    end

    if nargin < 2 || isempty(ShowPlots)
        ShowPlots = true;
    end

    if ~islogical(ShowPlots) || ~isscalar(ShowPlots)
        error('RunDemoLPF:InvalidPlotVisibility', ...
            'ShowPlots must be a logical scalar.');
    end

    RequiredFields = [ ...
        "Parameters", ...
        "Fs", ...
        "Time", ...
        "CurrentSignal", ...
        "SignalGenerator", ...
        "HPF"];

    for k = 1:numel(RequiredFields)
        if ~isfield(State, RequiredFields(k))
            error('RunDemoLPF:MissingStateField', ...
                'State.%s is required.', RequiredFields(k));
        end
    end

    P = State.Parameters;
    Fs = State.Fs;
    Time = State.Time(:);
    InputSignal = double(State.CurrentSignal(:));

    if numel(Time) ~= numel(InputSignal)
        error('RunDemoLPF:StateLengthMismatch', ...
            'State.Time and State.CurrentSignal must have equal lengths.');
    end

    FrameLength = P.getValue("FrameLength");
    NumberSamples = numel(InputSignal);
    NumberFrames = ceil(NumberSamples / FrameLength);


    %% ==========================================
    %% FRAME-BASED LOW-PASS FILTER PROCESSING
    %% ==========================================

    Filter = ADCFilter(P);
    LPFOutputSignal = zeros(NumberSamples, 1);

    for FrameIndex = 1:NumberFrames
        FrameStart = (FrameIndex - 1) * FrameLength + 1;
        FrameEnd = min(FrameStart + FrameLength - 1, NumberSamples);
        FrameIndices = FrameStart:FrameEnd;

        LPFOutputSignal(FrameIndices) = ...
            Filter.ProcessLPFFrame(InputSignal(FrameIndices));
    end

    % Retrieve the exact initialized design used by ProcessLPFFrame().
    LPFSOS = Filter.LPFSOS;
    LPFGain = Filter.LPFGain;


    %% ==========================================
    %% FILTER-ORDER AND RESPONSE VERIFICATION
    %% ==========================================

    [MinimumOrder, MinimumCutoffHz, TransitionWidthHz, ...
        ConfiguredOrder, OrderOK, RollOff_dBPerOctave, ...
        RollOff_dBPerDecade] = ...
        FindButterworthOrder(P, "LPF");

    [PassbandOK, StopbandOK, ResponseOverallOK, ...
        PassbandRipple_dB, WorstPassbandLoss_dB, ...
        StopbandAttenuation_dB, MeasuredTransitionWidthHz, ...
        WorstStopbandFrequencyHz] = ...
        CheckADCFilterResponse(P, "LPF", 131072);


    %% ==========================================
    %% ALIAS PROTECTION, TRANSIENT, AND STABILITY
    %% ==========================================

    AntiAliasingMetrics = MeasureAntiAliasingResponse( ...
        LPFSOS, ...
        LPFGain, ...
        P);


    %% ==========================================
    %% MEASURED INPUT/OUTPUT SNR AND SINR
    %% ==========================================
    % Use the exact observation record and detected component frequencies
    % established by the signal-generator stage. Both sides of the LPF are
    % measured with identical Welch and component-power settings.

    if ~isfield(State.SignalGenerator, "AnalysisRecord") || ...
            ~isfield(State.SignalGenerator, "Measurements") || ...
            ~isfield( ...
                State.SignalGenerator.Measurements, ...
                "DesiredFrequencies_Hz") || ...
            ~isfield( ...
                State.SignalGenerator.Measurements, ...
                "InterferenceFrequency_Hz")

        error('RunDemoLPF:MissingSignalAnalysisState', ...
            ['The signal-generator analysis record and detected ', ...
             'component frequencies are required for LPF SNR/SINR ', ...
             'measurement.']);
    end

    AnalysisStartIndex = ...
        State.SignalGenerator.AnalysisRecord.StartIndex;
    AnalysisEndIndex = ...
        State.SignalGenerator.AnalysisRecord.EndIndex;

    if ~isscalar(AnalysisStartIndex) || ...
            ~isscalar(AnalysisEndIndex) || ...
            AnalysisStartIndex < 1 || ...
            AnalysisEndIndex > NumberSamples || ...
            AnalysisStartIndex ~= fix(AnalysisStartIndex) || ...
            AnalysisEndIndex ~= fix(AnalysisEndIndex) || ...
            AnalysisEndIndex < AnalysisStartIndex

        error('RunDemoLPF:InvalidSignalAnalysisRecord', ...
            'The signal-generator analysis-record indices are invalid.');
    end

    AnalysisIndices = AnalysisStartIndex:AnalysisEndIndex;
    InputAnalysisRecord = InputSignal(AnalysisIndices);
    OutputAnalysisRecord = LPFOutputSignal(AnalysisIndices);

    Spectrum = SpectrumAnalyzer(P, Fs);

    [PowerPSDFrequency, InputPowerPSD] = ...
        Spectrum.HammingPSD(InputAnalysisRecord);
    [OutputPowerPSDFrequency, OutputPowerPSD] = ...
        Spectrum.HammingPSD(OutputAnalysisRecord);

    if ~isequal(PowerPSDFrequency, OutputPowerPSDFrequency)
        error('RunDemoLPF:PSDGridMismatch', ...
            'Input and output Welch PSD frequency grids must match.');
    end

    PSDWindowLength = P.getValue("PSDWindowLength");
    DCGuardBandwidth = 2 * Fs / PSDWindowLength;

    DetectedDesiredFrequencies = ...
        State.SignalGenerator.Measurements.DesiredFrequencies_Hz(:);
    DetectedInterferenceFrequency = ...
        State.SignalGenerator.Measurements.InterferenceFrequency_Hz;

    if numel(DetectedDesiredFrequencies) ~= 2
        error('RunDemoLPF:InvalidDesiredFrequencies', ...
            'Exactly two detected desired frequencies are required.');
    end

    PowerMeasurementNames = [ ...
        "Data Signal 1"; ...
        "Data Signal 2"; ...
        "Detected Interferer"];

    PowerMeasurementFrequencies = [ ...
        DetectedDesiredFrequencies; ...
        DetectedInterferenceFrequency];

    InputComponentMeasurements = ...
        Spectrum.MeasureComponentPowerAmplitude( ...
            InputPowerPSD, ...
            PowerPSDFrequency, ...
            PSDWindowLength, ...
            PowerMeasurementFrequencies, ...
            PowerMeasurementNames);

    OutputComponentMeasurements = ...
        Spectrum.MeasureComponentPowerAmplitude( ...
            OutputPowerPSD, ...
            PowerPSDFrequency, ...
            PSDWindowLength, ...
            PowerMeasurementFrequencies, ...
            PowerMeasurementNames);

    DesiredBandLower = ...
        min(P.getValue("FData"), P.getValue("FData2")) - 50e6;
    DesiredBandUpper = ...
        max(P.getValue("FData"), P.getValue("FData2")) + 50e6;

    BroadbandNoiseMask = ...
        PowerPSDFrequency > DCGuardBandwidth & ...
        PowerPSDFrequency <= Fs/2 & ...
        ~(PowerPSDFrequency >= DesiredBandLower & ...
        PowerPSDFrequency <= DesiredBandUpper) & ...
        abs( ...
            PowerPSDFrequency - DetectedInterferenceFrequency) > 50e6;

    if ~any(BroadbandNoiseMask)
        error('RunDemoLPF:EmptyNoiseMeasurementBand', ...
            'No Welch PSD bins remain for broadband-noise measurement.');
    end

    InputBroadbandNoisePSD = ...
        mean(InputPowerPSD(BroadbandNoiseMask));
    OutputBroadbandNoisePSD = ...
        mean(OutputPowerPSD(BroadbandNoiseMask));

    % Use the same one-sided equivalent-noise convention as the preceding
    % stages so the reported changes remain directly comparable.
    NoiseBandwidth = Fs / 2;

    InputBroadbandNoisePower = ...
        InputBroadbandNoisePSD * NoiseBandwidth;
    OutputBroadbandNoisePower = ...
        OutputBroadbandNoisePSD * NoiseBandwidth;

    InputDesiredSignalPower = ...
        sum(InputComponentMeasurements.ComponentPower_V2(1:2));
    OutputDesiredSignalPower = ...
        sum(OutputComponentMeasurements.ComponentPower_V2(1:2));

    InputInterferencePower = ...
        InputComponentMeasurements.ComponentPower_V2(3);
    OutputInterferencePower = ...
        OutputComponentMeasurements.ComponentPower_V2(3);

    InputSNR_dB = 10 * log10( ...
        max(InputDesiredSignalPower, realmin("double")) / ...
        max(InputBroadbandNoisePower, realmin("double")));

    OutputSNR_dB = 10 * log10( ...
        max(OutputDesiredSignalPower, realmin("double")) / ...
        max(OutputBroadbandNoisePower, realmin("double")));

    InputSINR_dB = 10 * log10( ...
        max(InputDesiredSignalPower, realmin("double")) / ...
        max( ...
            InputBroadbandNoisePower + InputInterferencePower, ...
            realmin("double")));

    OutputSINR_dB = 10 * log10( ...
        max(OutputDesiredSignalPower, realmin("double")) / ...
        max( ...
            OutputBroadbandNoisePower + OutputInterferencePower, ...
            realmin("double")));

    SNRChange_dB = OutputSNR_dB - InputSNR_dB;
    SINRChange_dB = OutputSINR_dB - InputSINR_dB;

    NoisePowerReduction_dB = 10 * log10( ...
        max(InputBroadbandNoisePower, realmin("double")) / ...
        max(OutputBroadbandNoisePower, realmin("double")));

    PowerRatioSummary = table( ...
        ["Before LPF"; "After LPF"], ...
        [InputDesiredSignalPower; OutputDesiredSignalPower], ...
        [InputBroadbandNoisePower; OutputBroadbandNoisePower], ...
        [InputInterferencePower; OutputInterferencePower], ...
        [InputSNR_dB; OutputSNR_dB], ...
        [InputSINR_dB; OutputSINR_dB], ...
        'VariableNames', { ...
            'Observation', ...
            'DesiredSignalPower_V2', ...
            'BroadbandNoisePower_V2', ...
            'InterferencePower_V2', ...
            'SNR_dB', ...
            'SINR_dB'});


    %% ==========================================
    %% TWO-TONE INTERMODULATION COMPARISON
    %% ==========================================
    % Characterize the same IM2 / IM3 product locations before and after
    % the linear LPF using the actual 40-GS/s stage sampling frequency.

    InputIMDMetrics = ...
        MeasureADCIntermodulationPerformance( ...
            InputSignal, DetectedDesiredFrequencies, P, Fs);

    OutputIMDMetrics = ...
        MeasureADCIntermodulationPerformance( ...
            LPFOutputSignal, DetectedDesiredFrequencies, P, Fs);

    IM2Change_dB = ...
        OutputIMDMetrics.WorstIM2_dBc - ...
        InputIMDMetrics.WorstIM2_dBc;

    IM3Change_dB = ...
        OutputIMDMetrics.WorstIM3_dBc - ...
        InputIMDMetrics.WorstIM3_dBc;

    IMDComparisonSummary = table( ...
        ["Worst IM2"; "Worst IM3"], ...
        [InputIMDMetrics.WorstIM2_dBc; ...
         InputIMDMetrics.WorstIM3_dBc], ...
        [OutputIMDMetrics.WorstIM2_dBc; ...
         OutputIMDMetrics.WorstIM3_dBc], ...
        [IM2Change_dB; IM3Change_dB], ...
        'VariableNames', { ...
            'Metric', ...
            'BeforeLPF_dBc', ...
            'AfterLPF_dBc', ...
            'Change_dB'});
    %% ==========================================
    %% OVERALL LPF PERFORMANCE DECISION
    %% ==========================================

    OverallLPFOK = ...
        OrderOK && ...
        ResponseOverallOK && ...
        AntiAliasingMetrics.OverallOK;


    %% ==========================================
    %% COMMAND-WINDOW PERFORMANCE SUMMARY
    %% ==========================================

    fprintf("\n");
    fprintf("===============================================================\n");
    fprintf("ANTI-ALIASING LOW-PASS FILTER PERFORMANCE SUMMARY\n");
    fprintf("===============================================================\n");

    fprintf("Design and implementation\n");
    fprintf("  Butterworth order               : %d\n", ...
        ConfiguredOrder);
    fprintf("  Minimum required order          : %d\n", ...
        MinimumOrder);
    fprintf("  Configured cutoff               : %.9f GHz\n", ...
        P.getValue("FcLow") / 1e9);
    fprintf("  Minimum-order cutoff            : %.9f GHz\n", ...
        MinimumCutoffHz / 1e9);
    fprintf("  SOS sections                    : %d\n", ...
        size(LPFSOS, 1));
    fprintf("  Processed frames                : %d\n", ...
        NumberFrames);
    fprintf("  Roll-off                        : %.3f dB/octave\n", ...
        RollOff_dBPerOctave);
    fprintf("  Roll-off                        : %.3f dB/decade\n", ...
        RollOff_dBPerDecade);

    fprintf("\nProtected sampler interface\n");
    fprintf("  Downsampling factor             : %d\n", ...
        AntiAliasingMetrics.DownsamplingFactor);
    fprintf("  ADC sampling frequency          : %.6f GS/s\n", ...
        AntiAliasingMetrics.ADCSamplingFrequency_Hz / 1e9);
    fprintf("  Protected Nyquist frequency     : %.6f GHz\n", ...
        AntiAliasingMetrics.ProtectedNyquistFrequency_Hz / 1e9);
    fprintf("  LPF stopband edge               : %.6f GHz\n", ...
        AntiAliasingMetrics.StopbandEdge_Hz / 1e9);
    fprintf("  Alias-boundary margin           : %.6f MHz\n", ...
        AntiAliasingMetrics.AliasBoundaryMargin_Hz / 1e6);

    fprintf("\nFrequency-response compliance\n");
    fprintf("  Transition width                : %.6f GHz\n", ...
        MeasuredTransitionWidthHz / 1e9);
    fprintf("  Passband loss                   : %.6f dB\n", ...
        WorstPassbandLoss_dB);
    fprintf("  Passband ripple                 : %.6f dB\n", ...
        PassbandRipple_dB);
    fprintf("  Stopband attenuation            : %.6f dB\n", ...
        StopbandAttenuation_dB);
    fprintf("  Worst stopband frequency        : %.6f GHz\n", ...
        WorstStopbandFrequencyHz / 1e9);

    fprintf("\nDesired-tone and interference response\n");
    fprintf("  Data Signal 1 loss              : %.9f dB\n", ...
        AntiAliasingMetrics.DesiredToneLoss_dB(1));
    fprintf("  Data Signal 2 loss              : %.9f dB\n", ...
        AntiAliasingMetrics.DesiredToneLoss_dB(2));
    fprintf("  Differential tone loss          : %.9f dB\n", ...
        AntiAliasingMetrics.DifferentialToneLoss_dB);
    fprintf("  Maximum permitted tone loss     : %.6f dB\n", ...
        AntiAliasingMetrics.MaximumDesiredToneLoss_dB);
    fprintf("  Interference frequency          : %.6f GHz\n", ...
        AntiAliasingMetrics.InterferenceFrequency_Hz / 1e9);
    fprintf("  Interference attenuation        : %.6f dB\n", ...
        AntiAliasingMetrics.InterferenceAttenuation_dB);
    fprintf("  Required interference atten.    : %.6f dB\n", ...
        AntiAliasingMetrics.RequiredInterferenceAttenuation_dB);

    fprintf("\nTransient and stability\n");
    fprintf("  1%% settling time                : %.6f ns\n", ...
        AntiAliasingMetrics.SettlingTime_s * 1e9);
    fprintf("  Required settling time          : %.6f ns\n", ...
        AntiAliasingMetrics.RequiredSettlingTime_s * 1e9);
    fprintf("  Step overshoot                  : %.6f %%\n", ...
        100 * AntiAliasingMetrics.StepOvershoot);
    fprintf("  Maximum permitted overshoot     : %.6f %%\n", ...
        100 * AntiAliasingMetrics.MaximumStepOvershoot);
    fprintf("  Maximum pole radius             : %.9f\n", ...
        AntiAliasingMetrics.MaximumPoleRadius);

    fprintf("\nTwo-tone intermodulation comparison\n");
    disp(IMDComparisonSummary);
    fprintf( ...
        "  Positive change means the IM product became stronger after the LPF.\n");

    fprintf("\nMeasured power-ratio comparison\n");
    disp(PowerRatioSummary);
    fprintf("  Broadband-noise reduction       : %+.3f dB\n", ...
        NoisePowerReduction_dB);
    fprintf("  SNR change (after - before)     : %+.3f dB\n", ...
        SNRChange_dB);
    fprintf("  SINR change (after - before)    : %+.3f dB\n", ...
        SINRChange_dB);

    if OverallLPFOK
        fprintf("\nOverall LPF performance           : PASS\n");
    else
        fprintf("\nOverall LPF performance           : FAIL\n");
    end


    if ShowPlots

        %% ==========================================
        %% STATIC MAGNITUDE-RESPONSE PLOT
        %% ==========================================

        Fpass = P.getValue("FpassLPF");
        Fstop = P.getValue("FstopLPF");
        Apass = P.getValue("ApassLPF");
        Astop = P.getValue("AstopLPF");
        FcLow = P.getValue("FcLow");
        InterferenceFrequency = P.getValue("Fnoise");

        ResponsePlotMaximumHz = 8e9;
        ResponseFrequency = linspace(0, ResponsePlotMaximumHz, 65537);
        ResponseFrequency = unique([ ...
            ResponseFrequency, ...
            AntiAliasingMetrics.DesiredFrequencies_Hz.', ...
            Fpass, ...
            FcLow, ...
            Fstop, ...
            InterferenceFrequency]);

        [FrequencyResponse, ResponseFrequency] = ...
            freqz(LPFSOS, ResponseFrequency, Fs);

        FrequencyResponse = LPFGain .* FrequencyResponse;
        MagnitudeResponse_dB = ...
            20 * log10(max(abs(FrequencyResponse), realmin("double")));

        figure( ...
            "Name", "Anti-Aliasing LPF - Magnitude Response", ...
            "Color", "w");

        plot( ...
            ResponseFrequency / 1e9, ...
            MagnitudeResponse_dB, ...
            "LineWidth", 1.5, ...
            "DisplayName", "Realized LPF response");
        hold on;

        plot( ...
            [0, Fpass] / 1e9, ...
            [-Apass, -Apass], ...
            "g--", ...
            "LineWidth", 1.3, ...
            "DisplayName", "Passband-loss limit");

        plot( ...
            [Fstop, ResponsePlotMaximumHz] / 1e9, ...
            [-Astop, -Astop], ...
            "r--", ...
            "LineWidth", 1.3, ...
            "DisplayName", "Stopband limit");

        xline(Fpass / 1e9, ":", "Fpass", ...
            "HandleVisibility", "off");
        xline(FcLow / 1e9, ":", "FcLow", ...
            "HandleVisibility", "off");
        xline(Fstop / 1e9, ":", "Sampler Nyquist / Fstop", ...
            "HandleVisibility", "off");
        xline(InterferenceFrequency / 1e9, ":", "Interferer", ...
            "HandleVisibility", "off");

        grid on;
        xlim([0, ResponsePlotMaximumHz / 1e9]);
        ylim([-140, 2]);
        xlabel("Frequency (GHz)");
        ylabel("Magnitude (dB)");
        title(sprintf( ...
            "Order-%d Butterworth Anti-Aliasing LPF", ...
            ConfiguredOrder));
        legend("Location", "southwest");


        %% ==========================================
        %% PHASE-DELAY PLOT IN SAMPLES
        %% ==========================================
        % Phase delay is -phase/omega.  Using omega in rad/sample makes
        % the result directly readable in samples.  DC is excluded because
        % phase delay is undefined at omega = 0.

        DigitalAngularFrequency = ...
            2 * pi * ResponseFrequency / Fs;
        UnwrappedPhase_rad = unwrap(angle(FrequencyResponse));

        PhaseDelay_samples = NaN(size(ResponseFrequency));
        NonzeroFrequencyMask = DigitalAngularFrequency > 0;

        PhaseDelay_samples(NonzeroFrequencyMask) = ...
            -UnwrappedPhase_rad(NonzeroFrequencyMask) ./ ...
            DigitalAngularFrequency(NonzeroFrequencyMask);

        figure( ...
            "Name", "Anti-Aliasing LPF - Phase Delay", ...
            "Color", "w");

        plot( ...
            ResponseFrequency / 1e9, ...
            PhaseDelay_samples, ...
            "LineWidth", 1.5, ...
            "DisplayName", "LPF phase delay");
        hold on;

        %xline(P.getValue("FData") / 1e9, ":", "Data 1", ...
            %"HandleVisibility", "on", ...
            %"DisplayName", "Data 1");
        %xline((P.getValue("FData2") / 1e9), ":", "Data 2", ...
            %"HandleVisibility", "on", ...
            %"DisplayName", "Data 2" );
        DesiredToneCenter = ...
            mean([P.getValue("FData"), P.getValue("FData2")]);

        xline( ...
            DesiredToneCenter / 1e9, ...
            ":", ...
            "Data 1 / Data 2 (1.000 / 1.001 GHz)", ...
            "HandleVisibility", "on", ...
            "DisplayName", "Desired Tones");

        xline(Fpass / 1e9, ":", "Fpass", ...
            "HandleVisibility", "off");
        xline(Fstop / 1e9, ":", "Sampler Nyquist / Fstop", ...
            "HandleVisibility", "off");
        xline(InterferenceFrequency / 1e9, ":", "Interferer", ...
            "HandleVisibility", "off");

        grid on;
        xlim([0, ResponsePlotMaximumHz / 1e9]);
        xlabel("Frequency (GHz)");
        ylabel("Phase Delay (samples)");
        title("Anti-Aliasing LPF Phase Delay");
        legend("Location", "best");


        %% ==========================================
        %% NORMALIZED UNIT-STEP RESPONSE PLOT
        %% ==========================================

        StepPlotMaximum_s = ...
            2 * AntiAliasingMetrics.RequiredSettlingTime_s;
        StepPlotMask = ...
            AntiAliasingMetrics.StepTime_s <= StepPlotMaximum_s;

        figure( ...
            "Name", "Anti-Aliasing LPF - Step Response", ...
            "Color", "w");

        plot( ...
            AntiAliasingMetrics.StepTime_s(StepPlotMask) * 1e6, ...
            AntiAliasingMetrics.NormalizedStepResponse(StepPlotMask), ...
            "LineWidth", 1.5, ...
            "DisplayName", "Normalized LPF step response");
        hold on;

        yline(1, "k:", "Final value", ...
            "HandleVisibility", "off");
        yline( ...
            1 + AntiAliasingMetrics.SettlingTolerance, ...
            "r--", ...
            "+1% tolerance", ...
           "HandleVisibility", "off");
        yline( ...
            1 - AntiAliasingMetrics.SettlingTolerance, ...
            "r--", ...
            "-1% tolerance", ...
            "HandleVisibility", "off");

        if isfinite(AntiAliasingMetrics.SettlingTime_s)
            xline( ...
                AntiAliasingMetrics.SettlingTime_s * 1e6, ...
                "b--", ...
                "Measured settling", ...
                "HandleVisibility", "off");
        end

        xline( ...
            AntiAliasingMetrics.RequiredSettlingTime_s * 1e6, ...
            "k:", ...
            sprintf( ...
                "%.3g microseconds requirement", ...
                AntiAliasingMetrics.RequiredSettlingTime_s * 1e6), ...
            "HandleVisibility", "off");

        grid on;
        xlim([0, StepPlotMaximum_s * 1e6]);
        xlabel("Time (microseconds)");
        ylabel("Normalized amplitude");
        title("Anti-Aliasing LPF Unit-Step Settling and Overshoot");
        legend("Location", "best");


        %% ==========================================
        %% RECEIVED-SIGNAL SPECTRAL COMPARISON
        %% ==========================================

        InputPSD_dB = ...
            10 * log10(max(InputPowerPSD, realmin("double")));
        OutputPSD_dB = ...
            10 * log10(max(OutputPowerPSD, realmin("double")));

        [FFTFrequency, InputMagnitude] = ...
            Spectrum.HammingFFT(InputSignal);
        [~, OutputMagnitude] = ...
            Spectrum.HammingFFT(LPFOutputSignal);

        InputMagnitude_dBV = ...
            20 * log10(max(InputMagnitude, realmin("double")));
        OutputMagnitude_dBV = ...
            20 * log10(max(OutputMagnitude, realmin("double")));

        figure( ...
            "Name", "Anti-Aliasing LPF - Received-Signal Spectrum", ...
            "Color", "w");

        SpectrumLayout = tiledlayout(3, 1, ...
            "TileSpacing", "compact", ...
            "Padding", "compact");

        nexttile;
        plot( ...
            PowerPSDFrequency / 1e9, ...
            InputPSD_dB, ...
            "LineWidth", 1.1, ...
            "DisplayName", "Before LPF");
        hold on;
        plot( ...
            PowerPSDFrequency / 1e9, ...
            OutputPSD_dB, ...
            "LineStyle", "--", ...
            "LineWidth", 1.1, ...
            "DisplayName", "After LPF");
        xline(Fpass / 1e9, ":", "Fpass", ...
            "HandleVisibility", "off");
        xline(Fstop / 1e9, ":", "Sampler Nyquist", ...
            "HandleVisibility", "off");
        xline(InterferenceFrequency / 1e9, ":", "Interferer", ...
            "HandleVisibility", "off");
        grid on;
        xlim([0, ResponsePlotMaximumHz / 1e9]);
        xlabel("Frequency (GHz)");
        ylabel("PSD (dBV^2/Hz)");
        title("Welch PSD: Broadband-Noise and Alias-Band Rejection");
        legend("Location", "best");

        nexttile;
        plot( ...
            FFTFrequency / 1e9, ...
            InputMagnitude_dBV, ...
            "LineWidth", 1.1, ...
            "DisplayName", "Before LPF");
        hold on;
        plot( ...
            FFTFrequency / 1e9, ...
            OutputMagnitude_dBV, ...
            "LineStyle", "--", ...
            "LineWidth", 1.1, ...
            "DisplayName", "After LPF");
        xline(P.getValue("FData") / 1e9, ":", "Data 1", ...
            "HandleVisibility", "off");
        xline(P.getValue("FData2") / 1e9, ":", "Data 2", ...
            "HandleVisibility", "off");
        grid on;
        xlim([0.995, 1.006]);
        xlabel("Frequency (GHz)");
        ylabel("Magnitude (dBV)");
        title("Hamming FFT: Desired-Tone Preservation");
        legend("Location", "best");

        nexttile;
        plot( ...
            FFTFrequency / 1e9, ...
            InputMagnitude_dBV, ...
            "LineWidth", 1.1, ...
            "DisplayName", "Before LPF");
        hold on;
        plot( ...
            FFTFrequency / 1e9, ...
            OutputMagnitude_dBV, ...
            "LineStyle", "--", ...
            "LineWidth", 1.1, ...
            "DisplayName", "After LPF");
        xline(InterferenceFrequency / 1e9, ":", "Interferer", ...
            "HandleVisibility", "off");
        grid on;
        xlim([5.8, 6.6]);
        xlabel("Frequency (GHz)");
        ylabel("Magnitude (dBV)");
        title("Hamming FFT: 6.2 GHz Interference Rejection");
        legend("Location", "best");

        title(SpectrumLayout, ...
            "Received Signal Before and After Anti-Aliasing LPF");

        %% ==========================================
        %% PHASE-DELAY ZOOM AROUND DESIRED TONES
        %% ==========================================

        figure( ...
            "Name", "Anti-Aliasing LPF - Phase Delay Desired-Tone Zoom", ...
            "Color", "w");

        plot( ...
            ResponseFrequency / 1e9, ...
            PhaseDelay_samples, ...
            "LineWidth", 1.5);
        hold on;

        xline(P.getValue("FData") / 1e9, ":", "Data 1");
        xline(P.getValue("FData2") / 1e9, ":", "Data 2");

        grid on;
        xlim([0.995, 1.006]);

        xlabel("Frequency (GHz)");
        ylabel("Phase Delay (samples)");
        title("LPF Phase Delay Around Desired Tones");

        %% ==========================================
        %% MATLAB FILTER ANALYZER
        %% ==========================================

        FilterVisualization = FiltWinAnalyzer();
        FilterVisualization.AnalyzeSOSFilter( ...
            LPFSOS, ...
            LPFGain, ...
            Fs, ...
            "Anti-Aliasing Butterworth LPF");


        %% ==========================================
        %% LPF POLE-ZERO STABILITY FIGURE
        %% ==========================================

        [LPFB, LPFA] = sos2tf(LPFSOS, LPFGain);

        figure( ...
            "Name", "Anti-Aliasing LPF - Pole-Zero Stability", ...
            "Color", "w");

        zplane(LPFB, LPFA);
        grid on;

        title(sprintf( ...
            "Anti-Aliasing LPF Pole-Zero Stability: " + ...
            "Max Pole Radius = %.5f", ...
            AntiAliasingMetrics.MaximumPoleRadius));

        xlabel("Real Part");
        ylabel("Imaginary Part");

        exportgraphics( ...
            gcf, ...
            "Anti-Aliasing-LPF-Pole-Zero-Stability.png", ...
            "Resolution", 300);
    end


    %% ==========================================
    %% STORE LPF STAGE OUTPUT AND MEASUREMENTS
    %% ==========================================

    State.LPF = struct();
    State.LPF.OutputSignal = LPFOutputSignal;
    State.LPF.SOS = LPFSOS;
    State.LPF.Gain = LPFGain;

    State.LPF.Design = struct();
    State.LPF.Design.MinimumOrder = MinimumOrder;
    State.LPF.Design.ConfiguredOrder = ConfiguredOrder;
    State.LPF.Design.MinimumCutoffHz = MinimumCutoffHz;
    State.LPF.Design.ConfiguredCutoffHz = P.getValue("FcLow");
    State.LPF.Design.TransitionWidthHz = TransitionWidthHz;
    State.LPF.Design.RollOff_dBPerOctave = RollOff_dBPerOctave;
    State.LPF.Design.RollOff_dBPerDecade = RollOff_dBPerDecade;
    State.LPF.Design.OrderOK = OrderOK;

    State.LPF.Response = struct();
    State.LPF.Response.PassbandRipple_dB = PassbandRipple_dB;
    State.LPF.Response.WorstPassbandLoss_dB = ...
        WorstPassbandLoss_dB;
    State.LPF.Response.StopbandAttenuation_dB = ...
        StopbandAttenuation_dB;
    State.LPF.Response.WorstStopbandFrequencyHz = ...
        WorstStopbandFrequencyHz;
    State.LPF.Response.PassbandOK = PassbandOK;
    State.LPF.Response.StopbandOK = StopbandOK;
    State.LPF.Response.OverallOK = ResponseOverallOK;

    State.LPF.AntiAliasing = AntiAliasingMetrics;

    State.LPF.Intermodulation = struct();
    State.LPF.Intermodulation.Input = InputIMDMetrics;
    State.LPF.Intermodulation.Output = OutputIMDMetrics;
    State.LPF.Intermodulation.Comparison = IMDComparisonSummary;
    State.LPF.Intermodulation.IM2Change_dB = IM2Change_dB;
    State.LPF.Intermodulation.IM3Change_dB = IM3Change_dB;

    State.LPF.PowerRatios = struct();
    State.LPF.PowerRatios.Summary = PowerRatioSummary;
    State.LPF.PowerRatios.InputComponentMeasurements = ...
        InputComponentMeasurements;
    State.LPF.PowerRatios.OutputComponentMeasurements = ...
        OutputComponentMeasurements;
    State.LPF.PowerRatios.InputBroadbandNoisePSD_V2PerHz = ...
        InputBroadbandNoisePSD;
    State.LPF.PowerRatios.OutputBroadbandNoisePSD_V2PerHz = ...
        OutputBroadbandNoisePSD;
    State.LPF.PowerRatios.InputDesiredSignalPower_V2 = ...
        InputDesiredSignalPower;
    State.LPF.PowerRatios.OutputDesiredSignalPower_V2 = ...
        OutputDesiredSignalPower;
    State.LPF.PowerRatios.InputBroadbandNoisePower_V2 = ...
        InputBroadbandNoisePower;
    State.LPF.PowerRatios.OutputBroadbandNoisePower_V2 = ...
        OutputBroadbandNoisePower;
    State.LPF.PowerRatios.InputInterferencePower_V2 = ...
        InputInterferencePower;
    State.LPF.PowerRatios.OutputInterferencePower_V2 = ...
        OutputInterferencePower;
    State.LPF.PowerRatios.NoisePowerReduction_dB = ...
        NoisePowerReduction_dB;
    State.LPF.PowerRatios.InputSNR_dB = InputSNR_dB;
    State.LPF.PowerRatios.OutputSNR_dB = OutputSNR_dB;
    State.LPF.PowerRatios.SNRChange_dB = SNRChange_dB;
    State.LPF.PowerRatios.InputSINR_dB = InputSINR_dB;
    State.LPF.PowerRatios.OutputSINR_dB = OutputSINR_dB;
    State.LPF.PowerRatios.SINRChange_dB = SINRChange_dB;

    State.LPF.OverallOK = OverallLPFOK;
    State.CurrentSignal = LPFOutputSignal;
end
