function State = RunDemoQuantizer(State, ShowPlots)
%% =======================================================
%% BIPOLAR MIDTREAD QUANTIZER DEMONSTRATION
%% =======================================================
% Move the actual low-SNR sampler output through ADC.Midtread in frames,
% characterize quantization and unsigned-code use, verify Data 1 / Data 2
% preservation and two-tone intermodulation behavior, and pass the complete
% quantized record downstream.
% Sampling-clock behavior was characterized by RunDemoSampler and is not
% repeated here.


    %% ==========================================
    %% VALIDATE INTERSTAGE INPUT CONTRACT
    %% ==========================================

    if nargin < 1 || nargin > 2 || ~isstruct(State)
        error('RunDemoQuantizer:InvalidState', ...
            ['RunDemoQuantizer requires a State structure input and ', ...
             'an optional logical ShowPlots input.']);
    end

    if nargin < 2 || isempty(ShowPlots)
        ShowPlots = true;
    end

    if ~islogical(ShowPlots) || ~isscalar(ShowPlots)
        error('RunDemoQuantizer:InvalidPlotVisibility', ...
            'ShowPlots must be a logical scalar.');
    end

    RequiredFields = [ ...
        "Parameters"; ...
        "Fs"; ...
        "Time"; ...
        "CurrentSignal"; ...
        "Sampler"; ...
        "SignalGenerator"];

    for k = 1:numel(RequiredFields)
        if ~isfield(State, RequiredFields(k))
            error('RunDemoQuantizer:MissingStateField', ...
                'State.%s is required.', RequiredFields(k));
        end
    end

    RequiredSamplerFields = [ ...
        "OutputSignal"; ...
        "Time"; ...
        "SampleIndex"; ...
        "ADCSamplingFrequency_Hz"; ...
        "OutputSampleCount"; ...
        "PowerRatios"; ...
        "Aliasing"];

    for k = 1:numel(RequiredSamplerFields)
        if ~isfield(State.Sampler, RequiredSamplerFields(k))
            error('RunDemoQuantizer:MissingSamplerField', ...
                'State.Sampler.%s is required.', ...
                RequiredSamplerFields(k));
        end
    end

    P = State.Parameters;
    SamplingFrequency = double(State.Fs);
    Time = double(State.Time(:));
    InputSignal = double(State.CurrentSignal(:));
    SampleIndex = double(State.Sampler.SampleIndex(:));

    validateattributes( ...
        SamplingFrequency, ...
        {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, ...
        mfilename, ...
        'State.Fs');

    if isempty(InputSignal)
        error('RunDemoQuantizer:EmptyInput', ...
            'The quantizer requires a nonempty sampler output signal.');
    end

    if ~isreal(InputSignal) || any(~isfinite(InputSignal))
        error('RunDemoQuantizer:InvalidInputSignal', ...
            'State.CurrentSignal must be finite and real valued.');
    end

    NumberSamples = numel(InputSignal);

    if numel(Time) ~= NumberSamples || ...
            numel(SampleIndex) ~= NumberSamples
        error('RunDemoQuantizer:StateLengthMismatch', ...
            ['State.Time, State.CurrentSignal, and the sampler index ', ...
             'must have equal lengths.']);
    end

    SamplerOutput = double(State.Sampler.OutputSignal(:));
    SamplerTime = double(State.Sampler.Time(:));

    HandoffSignalOK = isequal(InputSignal, SamplerOutput);
    HandoffTimeOK = isequal(Time, SamplerTime);
    HandoffCountOK = ...
        NumberSamples == double(State.Sampler.OutputSampleCount);

    if ~HandoffSignalOK || ~HandoffTimeOK || ~HandoffCountOK
        error('RunDemoQuantizer:SamplerHandoffMismatch', ...
            ['State.CurrentSignal and State.Time must be the complete ', ...
             'output record produced by RunDemoSampler.']);
    end

    ExpectedSamplingFrequency = double( ...
        State.Sampler.ADCSamplingFrequency_Hz);
    RateTolerance = max( ...
        1e-3, 32 * eps(ExpectedSamplingFrequency));
    InputRateOK = abs( ...
        SamplingFrequency - ExpectedSamplingFrequency) <= ...
        RateTolerance;

    if ~InputRateOK
        error('RunDemoQuantizer:SamplerRateMismatch', ...
            ['State.Fs must match the ADC sampling frequency reported ', ...
             'by RunDemoSampler.']);
    end


    %% ==========================================
    %% QUANTIZER DESIGN AND FRAME CONFIGURATION
    %% ==========================================

    NumBits = P.getValue("NumBits");
    Vfs = P.getValue("Vfs");
    DownsamplingFactor = P.getValue("DF");
    HighRateFrameLength = P.getValue("FrameLength");

    validateattributes( ...
        NumBits, ...
        {'numeric'}, ...
        {'scalar', 'integer', 'finite', '>=', 2}, ...
        mfilename, ...
        'NumBits');
    validateattributes( ...
        Vfs, ...
        {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, ...
        mfilename, ...
        'Vfs');
    validateattributes( ...
        DownsamplingFactor, ...
        {'numeric'}, ...
        {'scalar', 'integer', 'finite', 'positive'}, ...
        mfilename, ...
        'DF');
    validateattributes( ...
        HighRateFrameLength, ...
        {'numeric'}, ...
        {'scalar', 'integer', 'finite', 'positive'}, ...
        mfilename, ...
        'FrameLength');

    if mod(HighRateFrameLength, DownsamplingFactor) ~= 0
        error('RunDemoQuantizer:NonintegralFrameLength', ...
            ['The configured high-rate frame length must be divisible ', ...
             'by DF at the ADC-rate quantizer boundary.']);
    end

    FrameLength = HighRateFrameLength / DownsamplingFactor;
    NumberFrames = ceil(NumberSamples / FrameLength);

    NumberCodes = 2^NumBits;
    MinimumCode = 0;
    MaximumCode = NumberCodes - 1;
    ZeroVoltCode = NumberCodes / 2;
    QuantizationStep = Vfs / NumberCodes;
    MinimumInputLevel = -Vfs / 2;
    MaximumInputLevel = Vfs / 2;
    MinimumReconstructedLevel = MinimumInputLevel;
    MaximumReconstructedLevel = ...
        MinimumInputLevel + MaximumCode * QuantizationStep;


    %% ==========================================
    %% FRAME-BASED BIPOLAR MIDTREAD QUANTIZATION
    %% ==========================================
    % ADC.Midtread is memoryless. Framing controls working-set size while
    % preserving exactly the same code decision at every sample as a
    % single full-record call.

    QuantizerModel = ADC(P);

    QuantizedSignal = zeros(NumberSamples, 1);
    Indices = zeros(NumberSamples, 1);
    QuantizationError = zeros(NumberSamples, 1);

    FramesProcessed = 0;

    for FrameIndex = 1:NumberFrames
        FrameStart = (FrameIndex - 1) * FrameLength + 1;
        FrameEnd = min(FrameStart + FrameLength - 1, NumberSamples);
        FrameIndices = FrameStart:FrameEnd;

        [QuantizedFrame, IndexFrame, ErrorFrame] = ...
            QuantizerModel.Midtread(InputSignal(FrameIndices));

        if numel(QuantizedFrame) ~= numel(FrameIndices) || ...
                numel(IndexFrame) ~= numel(FrameIndices) || ...
                numel(ErrorFrame) ~= numel(FrameIndices)
            error('RunDemoQuantizer:FrameLengthMismatch', ...
                'ADC.Midtread changed the number of samples in a frame.');
        end

        QuantizedSignal(FrameIndices) = QuantizedFrame;
        Indices(FrameIndices) = IndexFrame;
        QuantizationError(FrameIndices) = ErrorFrame;
        FramesProcessed = FramesProcessed + 1;
    end


    %% ==========================================
    %% STRUCTURAL AND QUANTIZATION MEASUREMENTS
    %% ==========================================

    OutputRateOK = InputRateOK;
    SampleCountOK = numel(QuantizedSignal) == NumberSamples;
    TimeRecordOK = numel(Time) == NumberSamples;
    FiniteOutputOK = ...
        all(isfinite(QuantizedSignal)) && ...
        all(isfinite(QuantizationError));
    IntegerCodeOK = all(Indices == fix(Indices));
    CodeRangeOK = ...
        all(Indices >= MinimumCode & Indices <= MaximumCode);

    ReconstructedFromCode = ...
        MinimumInputLevel + Indices * QuantizationStep;
    ArithmeticTolerance = max( ...
        1e-15, 32 * eps(max(1, max(abs(QuantizedSignal)))));
    ReconstructionOK = all(abs( ...
        QuantizedSignal - ReconstructedFromCode) <= ...
        ArithmeticTolerance);
    ErrorOutputOK = all(abs( ...
        QuantizationError - (QuantizedSignal - InputSignal)) <= ...
        ArithmeticTolerance);

    % Use the quantization and code-usage measurements directly. The
    % single-sinusoid SNR/SINAD/THD routine remains intentionally excluded
    % from this noisy two-data-tone record because it would classify Data 2
    % as a spur. Two-tone IMD is characterized separately below.
    QuantizationMetrics = ...
        MeasureQuantizationPerformance( ...
            InputSignal, QuantizedSignal, P);
    CodeMetrics = ...
        MeasureADCCodeUsage(InputSignal, Indices, P);

    InteriorCodeMask = ...
        Indices > MinimumCode & Indices < MaximumCode;

    if any(InteriorCodeMask)
        MaximumInteriorAbsoluteError = max(abs( ...
            QuantizationError(InteriorCodeMask)));
    else
        MaximumInteriorAbsoluteError = NaN;
    end

    MaximumIdealError = QuantizationStep / 2;
    ErrorBoundTolerance = max( ...
        1e-15, 32 * eps(QuantizationStep));
    InteriorErrorBoundOK = ...
        any(InteriorCodeMask) && ...
        MaximumInteriorAbsoluteError <= ...
        MaximumIdealError + ErrorBoundTolerance;

    MinimumSQNR_dB = P.getValue("MinQuantizerSQNR");
    MaximumOverloadPercentage = ...
        P.getValue("MaxQuantizerOverloadPercentage");

    SQNROK = ...
        QuantizationMetrics.SQNR >= MinimumSQNR_dB;
    OverloadOK = ...
        CodeMetrics.OverloadPercentage <= ...
        MaximumOverloadPercentage;


    %% ==========================================
    %% RECEIVER-MEASURED COMPONENT FREQUENCIES
    %% ==========================================

    if ~isfield(State.SignalGenerator, "AnalysisRecord") || ...
            ~isfield(State.SignalGenerator, "Measurements") || ...
            ~isfield( ...
                State.SignalGenerator.Measurements, ...
                "DesiredFrequencies_Hz") || ...
            ~isfield(State.Sampler.Aliasing, ...
                "PredictedAliasFrequency_Hz")
        error('RunDemoQuantizer:MissingSignalAnalysisState', ...
            ['The signal-generator analysis record, detected data-tone ', ...
             'frequencies, and sampler alias observation are required.']);
    end

    DesiredFrequencies = double( ...
        State.SignalGenerator.Measurements.DesiredFrequencies_Hz(:));
    AliasFrequency = double( ...
        State.Sampler.Aliasing.PredictedAliasFrequency_Hz);

    if numel(DesiredFrequencies) ~= 2 || ...
            any(~isfinite(DesiredFrequencies)) || ...
            ~isscalar(AliasFrequency) || ...
            ~isfinite(AliasFrequency)
        error('RunDemoQuantizer:InvalidMeasuredFrequencies', ...
            ['Exactly two finite desired frequencies and one finite ', ...
             'alias frequency are required.']);
    end

    if any(DesiredFrequencies <= 0 | ...
            DesiredFrequencies >= SamplingFrequency / 2) || ...
            AliasFrequency < 0 || ...
            AliasFrequency > SamplingFrequency / 2
        error('RunDemoQuantizer:FrequencyAboveNyquist', ...
            'All component frequencies must lie in the ADC Nyquist zone.');
    end


    %% ==========================================
    %% FULL-RECORD HAMMING-FFT TONE PRESERVATION
    %% ==========================================

    Spectrum = SpectrumAnalyzer(P, SamplingFrequency);

    [InputFFTFrequency, InputMagnitude] = ...
        Spectrum.HammingFFT(InputSignal);
    [OutputFFTFrequency, OutputMagnitude] = ...
        Spectrum.HammingFFT(QuantizedSignal);

    FFTGridTolerance = max( ...
        1e-3, 32 * eps(SamplingFrequency));

    if numel(InputFFTFrequency) ~= numel(OutputFFTFrequency) || ...
            any(abs( ...
                InputFFTFrequency - OutputFFTFrequency) > ...
                FFTGridTolerance)
        error('RunDemoQuantizer:FFTGridMismatch', ...
            'Input and output Hamming-FFT frequency grids must match.');
    end

    TrueFrequencyResolution = ...
        SamplingFrequency / NumberSamples;
    FFTDisplayBinSpacing = ...
        InputFFTFrequency(2) - InputFFTFrequency(1);

    SortedDesiredFrequencies = sort(DesiredFrequencies);
    MinimumToneSeparation = min(diff(SortedDesiredFrequencies));

    if MinimumToneSeparation <= 0
        error('RunDemoQuantizer:UnresolvedDesiredFrequencies', ...
            'The two desired frequencies must be distinct.');
    end

    ToneSearchHalfWidth = 0.4 * MinimumToneSeparation;

    [InputMeasuredToneFrequency, InputMeasuredToneMagnitude] = ...
        LocalMeasureFFTPeaks( ...
            InputFFTFrequency, ...
            InputMagnitude, ...
            DesiredFrequencies, ...
            ToneSearchHalfWidth);

    [OutputMeasuredToneFrequency, OutputMeasuredToneMagnitude] = ...
        LocalMeasureFFTPeaks( ...
            OutputFFTFrequency, ...
            OutputMagnitude, ...
            DesiredFrequencies, ...
            ToneSearchHalfWidth);

    FrequencyChange_Hz = ...
        OutputMeasuredToneFrequency - InputMeasuredToneFrequency;
    FrequencyError_Bins = ...
        abs(FrequencyChange_Hz) / TrueFrequencyResolution;

    InputToneLevel_dBV = 20 * log10(max( ...
        InputMeasuredToneMagnitude, realmin("double")));
    OutputToneLevel_dBV = 20 * log10(max( ...
        OutputMeasuredToneMagnitude, realmin("double")));
    ToneLevelChange_dB = ...
        OutputToneLevel_dBV - InputToneLevel_dBV;

    MaximumFrequencyErrorBins = ...
        P.getValue("MaxQuantizerFrequencyErrorBins");
    MaximumToneLevelChange_dB = ...
        P.getValue("MaxQuantizerToneLevelChange");

    ToneFrequencyPreservationOK = ...
        all(FrequencyError_Bins <= MaximumFrequencyErrorBins);
    ToneLevelPreservationOK = ...
        all(abs(ToneLevelChange_dB) <= ...
        MaximumToneLevelChange_dB);

    TonePreservationSummary = table( ...
        ["Data Signal 1"; "Data Signal 2"], ...
        DesiredFrequencies, ...
        InputMeasuredToneFrequency, ...
        OutputMeasuredToneFrequency, ...
        FrequencyChange_Hz, ...
        FrequencyError_Bins, ...
        InputToneLevel_dBV, ...
        OutputToneLevel_dBV, ...
        ToneLevelChange_dB, ...
        'VariableNames', { ...
            'Component', ...
            'ReceiverTargetFrequency_Hz', ...
            'BeforeQuantizerFrequency_Hz', ...
            'AfterQuantizerFrequency_Hz', ...
            'FrequencyChange_Hz', ...
            'FrequencyError_Bins', ...
            'BeforeQuantizerLevel_dBV', ...
            'AfterQuantizerLevel_dBV', ...
            'LevelChange_dB'});


    %% ==========================================
    %% TWO-TONE INTERMODULATION DISTORTION
    %% ==========================================
    % Measure the same IM2 / IM3 products before and after quantization.
    % This reports the intermodulation already present at the sampler output
    % separately from any change observed after quantization.

    InputIMDMetrics = ...
        MeasureADCIntermodulationPerformance( ...
            InputSignal, DesiredFrequencies, P);

    OutputIMDMetrics = ...
        MeasureADCIntermodulationPerformance( ...
            QuantizedSignal, DesiredFrequencies, P);

    IM2Change_dB = ...
        OutputIMDMetrics.WorstIM2_dBc - ...
        InputIMDMetrics.WorstIM2_dBc;

    IM3Change_dB = ...
        OutputIMDMetrics.WorstIM3_dBc - ...
        InputIMDMetrics.WorstIM3_dBc;

    IMDComparisonSummary = table( ...
        ["Worst IM2"; "Worst IM3"], ...
        [InputIMDMetrics.WorstIM2_dBc; ...
         InputIMDMetrics.WorstIM3_dBc], ...
        [OutputIMDMetrics.WorstIM2_dBc; ...
         OutputIMDMetrics.WorstIM3_dBc], ...
        [IM2Change_dB; IM3Change_dB], ...
        'VariableNames', { ...
            'Metric', ...
            'BeforeQuantizer_dBc', ...
            'AfterQuantizer_dBc', ...
            'Change_dB'});


    %% ==========================================
    %% MATCHED-RECORD HAMMING-WELCH SNR / SINR
    %% ==========================================
    % Use the same finite physical-time record propagated by the signal
    % generator and sampler. Input and output therefore share the same
    % samples, estimator, window, grid, and exclusion masks.

    AnalysisStartIndex = ...
        State.SignalGenerator.AnalysisRecord.StartIndex;
    AnalysisEndIndex = ...
        State.SignalGenerator.AnalysisRecord.EndIndex;

    if ~isscalar(AnalysisStartIndex) || ...
            ~isscalar(AnalysisEndIndex) || ...
            AnalysisStartIndex < 1 || ...
            AnalysisStartIndex ~= fix(AnalysisStartIndex) || ...
            AnalysisEndIndex ~= fix(AnalysisEndIndex) || ...
            AnalysisEndIndex < AnalysisStartIndex
        error('RunDemoQuantizer:InvalidSignalAnalysisRecord', ...
            'The signal-generator analysis-record indices are invalid.');
    end

    AnalysisMask = ...
        SampleIndex >= AnalysisStartIndex - 1 & ...
        SampleIndex <= AnalysisEndIndex - 1;
    InputAnalysisRecord = InputSignal(AnalysisMask);
    OutputAnalysisRecord = QuantizedSignal(AnalysisMask);

    HighRatePSDWindowLength = P.getValue("PSDWindowLength");
    HighRatePSDOverlapLength = P.getValue("PSDOverlapLength");
    HighRatePSDFFTLength = P.getValue("PSDFFTLength");

    HighRatePSDLengths = [ ...
        HighRatePSDWindowLength, ...
        HighRatePSDOverlapLength, ...
        HighRatePSDFFTLength];

    if any(mod(HighRatePSDLengths, DownsamplingFactor) ~= 0)
        error('RunDemoQuantizer:UnmatchedPSDConfiguration', ...
            ['PSD window, overlap, and FFT lengths must be divisible ', ...
             'by DF at the quantizer sampling rate.']);
    end

    PSDWindowLength = ...
        HighRatePSDWindowLength / DownsamplingFactor;
    PSDOverlapLength = ...
        HighRatePSDOverlapLength / DownsamplingFactor;
    PSDFFTLength = ...
        HighRatePSDFFTLength / DownsamplingFactor;

    if numel(InputAnalysisRecord) < PSDWindowLength || ...
            numel(OutputAnalysisRecord) < PSDWindowLength
        error('RunDemoQuantizer:AnalysisRecordTooShort', ...
            ['The quantizer input and output analysis records must each ', ...
             'contain one complete Welch window.']);
    end

    [PSDFrequency, InputPowerPSD] = ...
        LocalHammingPSD( ...
            InputAnalysisRecord, ...
            SamplingFrequency, ...
            PSDWindowLength, ...
            PSDOverlapLength, ...
            PSDFFTLength);

    [OutputPSDFrequency, OutputPowerPSD] = ...
        LocalHammingPSD( ...
            OutputAnalysisRecord, ...
            SamplingFrequency, ...
            PSDWindowLength, ...
            PSDOverlapLength, ...
            PSDFFTLength);

    if numel(PSDFrequency) ~= numel(OutputPSDFrequency) || ...
            any(abs(PSDFrequency - OutputPSDFrequency) > ...
            FFTGridTolerance)
        error('RunDemoQuantizer:PSDGridMismatch', ...
            'Input and output Hamming-Welch PSD grids must match.');
    end

    ComponentNames = [ ...
        "Data Signal 1"; ...
        "Data Signal 2"; ...
        "Predicted Interference Alias"];
    ComponentFrequencies = [ ...
        DesiredFrequencies; ...
        AliasFrequency];

    InputComponentMeasurements = ...
        Spectrum.MeasureComponentPowerAmplitude( ...
            InputPowerPSD, ...
            PSDFrequency, ...
            PSDWindowLength, ...
            ComponentFrequencies, ...
            ComponentNames);

    OutputComponentMeasurements = ...
        Spectrum.MeasureComponentPowerAmplitude( ...
            OutputPowerPSD, ...
            PSDFrequency, ...
            PSDWindowLength, ...
            ComponentFrequencies, ...
            ComponentNames);

    PSDSpacing = PSDFrequency(2) - PSDFrequency(1);
    DesiredBandLower = min(DesiredFrequencies) - 50e6;
    DesiredBandUpper = max(DesiredFrequencies) + 50e6;
    AliasGuardHalfWidth = 50e6;
    DCGuardBandwidth = ...
        2 * SamplingFrequency / PSDWindowLength;

    BroadbandNoiseMask = ...
        PSDFrequency > DCGuardBandwidth & ...
        ~(PSDFrequency >= DesiredBandLower & ...
        PSDFrequency <= DesiredBandUpper) & ...
        abs(PSDFrequency - AliasFrequency) > ...
        AliasGuardHalfWidth;

    if ~any(BroadbandNoiseMask)
        error('RunDemoQuantizer:EmptyNoiseMeasurementBand', ...
            'No ADC-band PSD bins remain for noise measurement.');
    end

    InputBroadbandNoisePower = sum( ...
        InputPowerPSD(BroadbandNoiseMask)) * PSDSpacing;
    OutputBroadbandNoisePower = sum( ...
        OutputPowerPSD(BroadbandNoiseMask)) * PSDSpacing;

    InputDesiredSignalPower = sum( ...
        InputComponentMeasurements.ComponentPower_V2(1:2));
    OutputDesiredSignalPower = sum( ...
        OutputComponentMeasurements.ComponentPower_V2(1:2));

    InputInterferencePower = ...
        InputComponentMeasurements.ComponentPower_V2(3);
    OutputInterferencePower = ...
        OutputComponentMeasurements.ComponentPower_V2(3);

    InputSNR_dB = 10 * log10( ...
        max(InputDesiredSignalPower, realmin("double")) / ...
        max(InputBroadbandNoisePower, realmin("double")));
    OutputSNR_dB = 10 * log10( ...
        max(OutputDesiredSignalPower, realmin("double")) / ...
        max(OutputBroadbandNoisePower, realmin("double")));

    InputSINR_dB = 10 * log10( ...
        max(InputDesiredSignalPower, realmin("double")) / ...
        max( ...
            InputBroadbandNoisePower + InputInterferencePower, ...
            realmin("double")));
    OutputSINR_dB = 10 * log10( ...
        max(OutputDesiredSignalPower, realmin("double")) / ...
        max( ...
            OutputBroadbandNoisePower + OutputInterferencePower, ...
            realmin("double")));

    SNRChange_dB = OutputSNR_dB - InputSNR_dB;
    SINRChange_dB = OutputSINR_dB - InputSINR_dB;

    MaximumSNRDegradation_dB = ...
        P.getValue("MaxQuantizerSNRDegradation");
    MaximumSINRDegradation_dB = ...
        P.getValue("MaxQuantizerSINRDegradation");

    SNRPreservationOK = ...
        SNRChange_dB >= -MaximumSNRDegradation_dB;
    SINRPreservationOK = ...
        SINRChange_dB >= -MaximumSINRDegradation_dB;

    PowerRatioSummary = table( ...
        ["Quantizer Input (0-5 GHz)"; ...
         "Quantizer Output (0-5 GHz)"], ...
        [InputDesiredSignalPower; OutputDesiredSignalPower], ...
        [InputBroadbandNoisePower; OutputBroadbandNoisePower], ...
        [InputInterferencePower; OutputInterferencePower], ...
        [InputSNR_dB; OutputSNR_dB], ...
        [InputSINR_dB; OutputSINR_dB], ...
        'VariableNames', { ...
            'Observation', ...
            'DesiredSignalPower_V2', ...
            'CommonBandNoisePower_V2', ...
            'InterferenceAliasPower_V2', ...
            'SNR_dB', ...
            'SINR_dB'});

    %% ==========================================
    %% OVERALL QUANTIZER PERFORMANCE DECISION
    %% ==========================================

    OverallQuantizerOK = ...
        InputRateOK && ...
        OutputRateOK && ...
        HandoffSignalOK && ...
        HandoffTimeOK && ...
        HandoffCountOK && ...
        SampleCountOK && ...
        TimeRecordOK && ...
        FiniteOutputOK && ...
        IntegerCodeOK && ...
        CodeRangeOK && ...
        ReconstructionOK && ...
        ErrorOutputOK && ...
        InteriorErrorBoundOK && ...
        SQNROK && ...
        OverloadOK && ...
        ToneFrequencyPreservationOK && ...
        ToneLevelPreservationOK && ...
        SNRPreservationOK && ...
        SINRPreservationOK;


    %% ==========================================
    %% COMMAND-WINDOW PERFORMANCE SUMMARY
    %% ==========================================

    fprintf("\n");
    fprintf("===============================================================\n");
    fprintf("BIPOLAR MIDTREAD QUANTIZER PERFORMANCE SUMMARY\n");
    fprintf("===============================================================\n");

    fprintf("Design\n");
    fprintf("  Input                            : Actual sampler output\n");
    fprintf("  Quantizer                        : Uniform bipolar midtread\n");
    fprintf("  Sampling frequency              : %.6f GS/s\n", ...
        SamplingFrequency / 1e9);
    fprintf("  Resolution / available codes    : %d bits / %d\n", ...
        NumBits, NumberCodes);
    fprintf("  Unsigned code range             : %d to %d\n", ...
        MinimumCode, MaximumCode);
    fprintf("  Zero-volt code                  : %d\n", ...
        ZeroVoltCode);
    fprintf("  Full-scale input range          : %.6f Vpp\n", Vfs);
    fprintf("  Nominal input limits            : %.6f to %+.6f V\n", ...
        MinimumInputLevel, MaximumInputLevel);
    fprintf("  Reconstructed level range       : %.7f to %+.7f V\n", ...
        MinimumReconstructedLevel, MaximumReconstructedLevel);
    fprintf("  Quantization step (Delta)        : %.7f mV\n", ...
        QuantizationStep * 1e3);
    fprintf("  Saturation policy               : Clamp endpoint codes; drop none\n");

    fprintf("\nMeasured quantization performance\n");
    fprintf("  RMS quantization error          : %.9e V\n", ...
        QuantizationMetrics.RMSQuantizationError);
    fprintf("  Maximum interior-code abs. error: %.9e V\n", ...
        MaximumInteriorAbsoluteError);
    fprintf("  Quantization-noise power        : %.9e V^2\n", ...
        QuantizationMetrics.QuantizationNoisePower);
    fprintf("  Quantization-only SQNR          : %.6f dB\n", ...
        QuantizationMetrics.SQNR);
    fprintf("  Input overload samples          : %d of %d (%.9f %%)\n", ...
        CodeMetrics.OverloadSampleCount, ...
        NumberSamples, ...
        CodeMetrics.OverloadPercentage);

    fprintf("\nMeasured Data 1 / Data 2 preservation\n");
    disp(TonePreservationSummary);
    fprintf("  True full-record resolution     : %.6f kHz\n", ...
        TrueFrequencyResolution / 1e3);

    fprintf("\nTwo-tone intermodulation comparison\n");
    disp(IMDComparisonSummary);
    fprintf( ...
        "  Positive change means the IM product became stronger after quantization.\n");

    fprintf("\nQuantizer common-band power-ratio comparison\n");
    disp(PowerRatioSummary);
    fprintf("  SNR change (after - before)     : %+.6f dB\n", ...
        SNRChange_dB);
    fprintf("  SINR change (after - before)    : %+.6f dB\n", ...
        SINRChange_dB);

    fprintf("\nQuantizer compliance\n");
    fprintf("  Sampler handoff                 : %s\n", ...
        LocalPassFail( ...
        HandoffSignalOK && HandoffTimeOK && HandoffCountOK));
    fprintf("  Rate / sample-count preservation: %s\n", ...
        LocalPassFail(OutputRateOK && SampleCountOK));
    fprintf("  Unsigned code validity          : %s\n", ...
        LocalPassFail(IntegerCodeOK && CodeRangeOK));
    fprintf("  Code-to-voltage reconstruction  : %s\n", ...
        LocalPassFail(ReconstructionOK && ErrorOutputOK));
    fprintf("  Interior-code error bound       : %s\n", ...
        LocalPassFail(InteriorErrorBoundOK));
    fprintf("  Minimum quantization SQNR       : %s\n", ...
        LocalPassFail(SQNROK));
    fprintf("  Maximum input overload          : %s\n", ...
        LocalPassFail(OverloadOK));
    fprintf("  Desired-tone frequency          : %s\n", ...
        LocalPassFail(ToneFrequencyPreservationOK));
    fprintf("  Desired-tone level              : %s\n", ...
        LocalPassFail(ToneLevelPreservationOK));
    fprintf("  SNR preservation                : %s\n", ...
        LocalPassFail(SNRPreservationOK));
    fprintf("  SINR preservation               : %s\n", ...
        LocalPassFail(SINRPreservationOK));

    if OverallQuantizerOK
        fprintf("\nOverall quantizer performance     : PASS\n");
    else
        fprintf("\nOverall quantizer performance     : FAIL\n");
    end


    %% ==========================================
    %% APPROVED QUANTIZER FIGURES
    %% ==========================================

    if ShowPlots
        PerformanceAnalyzer = ADCPerformanceAnalyzer(P);

        DisplaySampleCount = min(512, NumberSamples);
        [~, DisplayCentre] = min(abs( ...
            Time - P.getValue("mu")));
        DisplayStart = max( ...
            1, DisplayCentre - floor(DisplaySampleCount / 2));
        DisplayEnd = min( ...
            NumberSamples, DisplayStart + DisplaySampleCount - 1);
        DisplayStart = max( ...
            1, DisplayEnd - DisplaySampleCount + 1);
        DisplayIndices = DisplayStart:DisplayEnd;

        PerformanceAnalyzer.PlotADCResponse( ...
            Time(DisplayIndices), ...
            InputSignal(DisplayIndices), ...
            QuantizedSignal(DisplayIndices), ...
            Indices(DisplayIndices));

        PerformanceAnalyzer.PlotCodeHistogram(Indices);

        PlotData = struct();
        PlotData.FFTFrequency = InputFFTFrequency;
        PlotData.InputMagnitude = InputMagnitude;
        PlotData.OutputMagnitude = OutputMagnitude;
        PlotData.PSDFrequency = PSDFrequency;
        PlotData.InputPSD = InputPowerPSD;
        PlotData.OutputPSD = OutputPowerPSD;
        PlotData.DesiredFrequencies = DesiredFrequencies;
        PlotData.AliasFrequency = AliasFrequency;
        PlotData.SamplingFrequency = SamplingFrequency;

        PerformanceAnalyzer.PlotSpectralPreservation(PlotData);
    end


    %% ==========================================
    %% STORE QUANTIZER OUTPUT AND MEASUREMENTS
    %% ==========================================

    State.Quantizer = struct();
    State.Quantizer.InputSignal = InputSignal;
    State.Quantizer.OutputSignal = QuantizedSignal;
    State.Quantizer.Time = Time;
    State.Quantizer.Indices = Indices;
    State.Quantizer.UnsignedIndices = Indices;
    State.Quantizer.QuantizationError = QuantizationError;
    State.Quantizer.Method = "Uniform bipolar midtread";
    State.Quantizer.SamplingFrequency_Hz = SamplingFrequency;
    State.Quantizer.NumBits = NumBits;
    State.Quantizer.NumberCodes = NumberCodes;
    State.Quantizer.ZeroVoltCode = ZeroVoltCode;
    State.Quantizer.FullScaleRange_Vpp = Vfs;
    State.Quantizer.QuantizationStep_V = QuantizationStep;
    State.Quantizer.InputLimits_V = [ ...
        MinimumInputLevel, MaximumInputLevel];
    State.Quantizer.ReconstructedLimits_V = [ ...
        MinimumReconstructedLevel, MaximumReconstructedLevel];
    State.Quantizer.FrameLength = FrameLength;
    State.Quantizer.FramesProcessed = FramesProcessed;
    State.Quantizer.InputSampleCount = NumberSamples;
    State.Quantizer.OutputSampleCount = numel(QuantizedSignal);
    State.Quantizer.TrueFrequencyResolution_Hz = ...
        TrueFrequencyResolution;
    State.Quantizer.FFTDisplayBinSpacing_Hz = ...
        FFTDisplayBinSpacing;

    State.Quantizer.QuantizationMetrics = QuantizationMetrics;
    State.Quantizer.CodeMetrics = CodeMetrics;
    State.Quantizer.MaximumInteriorAbsoluteError_V = ...
        MaximumInteriorAbsoluteError;

    State.Quantizer.TonePreservation = struct();
    State.Quantizer.TonePreservation.Summary = ...
        TonePreservationSummary;
    State.Quantizer.TonePreservation.FrequencyPreservationOK = ...
        ToneFrequencyPreservationOK;
    State.Quantizer.TonePreservation.LevelPreservationOK = ...
        ToneLevelPreservationOK;

    State.Quantizer.Intermodulation = struct();
    State.Quantizer.Intermodulation.Input = InputIMDMetrics;
    State.Quantizer.Intermodulation.Output = OutputIMDMetrics;
    State.Quantizer.Intermodulation.Comparison = ...
        IMDComparisonSummary;
    State.Quantizer.Intermodulation.IM2Change_dB = IM2Change_dB;
    State.Quantizer.Intermodulation.IM3Change_dB = IM3Change_dB;

    State.Quantizer.PowerRatios = struct();
    State.Quantizer.PowerRatios.Summary = PowerRatioSummary;
    State.Quantizer.PowerRatios.InputComponentMeasurements = ...
        InputComponentMeasurements;
    State.Quantizer.PowerRatios.OutputComponentMeasurements = ...
        OutputComponentMeasurements;
    State.Quantizer.PowerRatios.InputBroadbandNoisePower_V2 = ...
        InputBroadbandNoisePower;
    State.Quantizer.PowerRatios.OutputBroadbandNoisePower_V2 = ...
        OutputBroadbandNoisePower;
    State.Quantizer.PowerRatios.InputSNR_dB = InputSNR_dB;
    State.Quantizer.PowerRatios.OutputSNR_dB = OutputSNR_dB;
    State.Quantizer.PowerRatios.SNRChange_dB = SNRChange_dB;
    State.Quantizer.PowerRatios.InputSINR_dB = InputSINR_dB;
    State.Quantizer.PowerRatios.OutputSINR_dB = OutputSINR_dB;
    State.Quantizer.PowerRatios.SINRChange_dB = SINRChange_dB;
    State.Quantizer.PowerRatios.SNRPreservationOK = ...
        SNRPreservationOK;
    State.Quantizer.PowerRatios.SINRPreservationOK = ...
        SINRPreservationOK;

    State.Quantizer.AnalysisRecord = struct();
    State.Quantizer.AnalysisRecord.InputStartIndex = ...
        AnalysisStartIndex;
    State.Quantizer.AnalysisRecord.InputEndIndex = ...
        AnalysisEndIndex;
    State.Quantizer.AnalysisRecord.OutputSampleCount = ...
        numel(InputAnalysisRecord);
    State.Quantizer.AnalysisRecord.PSDWindowLength = ...
        PSDWindowLength;
    State.Quantizer.AnalysisRecord.PSDOverlapLength = ...
        PSDOverlapLength;
    State.Quantizer.AnalysisRecord.PSDFFTLength = ...
        PSDFFTLength;

    State.Quantizer.Compliance = struct();
    State.Quantizer.Compliance.SamplerHandoffOK = ...
        HandoffSignalOK && HandoffTimeOK && HandoffCountOK;
    State.Quantizer.Compliance.OutputRateOK = OutputRateOK;
    State.Quantizer.Compliance.SampleCountOK = SampleCountOK;
    State.Quantizer.Compliance.FiniteOutputOK = FiniteOutputOK;
    State.Quantizer.Compliance.IntegerCodeOK = IntegerCodeOK;
    State.Quantizer.Compliance.CodeRangeOK = CodeRangeOK;
    State.Quantizer.Compliance.ReconstructionOK = ReconstructionOK;
    State.Quantizer.Compliance.ErrorOutputOK = ErrorOutputOK;
    State.Quantizer.Compliance.InteriorErrorBoundOK = ...
        InteriorErrorBoundOK;
    State.Quantizer.Compliance.SQNROK = SQNROK;
    State.Quantizer.Compliance.OverloadOK = OverloadOK;
    State.Quantizer.Compliance.ToneFrequencyPreservationOK = ...
        ToneFrequencyPreservationOK;
    State.Quantizer.Compliance.ToneLevelPreservationOK = ...
        ToneLevelPreservationOK;
    State.Quantizer.Compliance.SNRPreservationOK = ...
        SNRPreservationOK;
    State.Quantizer.Compliance.SINRPreservationOK = ...
        SINRPreservationOK;
    State.Quantizer.OverallOK = OverallQuantizerOK;

    State.CurrentSignal = QuantizedSignal;
    State.Time = Time;
    State.Fs = SamplingFrequency;
end


function [MeasuredFrequency, PeakMagnitude] = LocalMeasureFFTPeaks( ...
        Frequency, Magnitude, TargetFrequencies, SearchHalfWidth)
%% Measure the strongest Hamming-FFT bin in each local search band.

    Frequency = Frequency(:);
    Magnitude = Magnitude(:);
    TargetFrequencies = TargetFrequencies(:);

    if numel(Frequency) ~= numel(Magnitude)
        error('RunDemoQuantizer:FFTLengthMismatch', ...
            'FFT frequency and magnitude vectors must have equal lengths.');
    end

    MeasuredFrequency = zeros(size(TargetFrequencies));
    PeakMagnitude = zeros(size(TargetFrequencies));

    for k = 1:numel(TargetFrequencies)
        SearchMask = abs( ...
            Frequency - TargetFrequencies(k)) <= SearchHalfWidth;

        if ~any(SearchMask)
            error('RunDemoQuantizer:EmptyToneSearchBand', ...
                'No Hamming-FFT bins lie inside a data-tone search band.');
        end

        CandidateIndices = find(SearchMask);
        [PeakMagnitude(k), LocalPeakIndex] = ...
            max(Magnitude(SearchMask));
        MeasuredFrequency(k) = ...
            Frequency(CandidateIndices(LocalPeakIndex));
    end
end


function [PSDFrequency, PowerPSD] = LocalHammingPSD( ...
        InputSignal, SamplingFrequency, ...
        WindowLength, OverlapLength, FFTLength)
%% Hamming-Welch PSD using the sampler-rate analysis lengths.

    InputSignal = InputSignal(:);

    if numel(InputSignal) < WindowLength
        error('RunDemoQuantizer:PSDRecordTooShort', ...
            'The signal is shorter than the Hamming-Welch window.');
    end

    if OverlapLength >= WindowLength
        error('RunDemoQuantizer:InvalidPSDOverlap', ...
            'PSDOverlapLength must be less than PSDWindowLength.');
    end

    if FFTLength < WindowLength
        error('RunDemoQuantizer:InvalidPSDFFTLength', ...
            'PSDFFTLength must be at least PSDWindowLength.');
    end

    HammingWindow = hamming(WindowLength, "periodic");

    [PowerPSD, PSDFrequency] = pwelch( ...
        InputSignal, ...
        HammingWindow, ...
        OverlapLength, ...
        FFTLength, ...
        SamplingFrequency, ...
        "onesided");
end


function Result = LocalPassFail(Condition)
%% Convert a scalar compliance decision to a readable label.

    if Condition
        Result = "PASS";
    else
        Result = "FAIL";
    end
end
