function State = RunDemoDecimator(State, ShowPlots)
%% =======================================================
%% FIXED-POINT POLYPHASE FIR DECIMATOR DEMONSTRATION
%% =======================================================
% Move the ADC encoder's complete signed two's-complement record through
% the floating-point reference and fixed-point polyphase decimators. This
% design stage establishes the coefficient, product, and accumulator
% formats and produces the 2.5 GS/s target-rate digital output. The same
% received record is then used to characterize filter response, alias
% protection, fixed-point error, tone preservation, SNR, and SINR.


    %% ==========================================
    %% VALIDATE INTERSTAGE INPUT CONTRACT
    %% ==========================================

    if nargin < 1 || nargin > 2 || ~isstruct(State)
        error('RunDemoDecimator:InvalidState', ...
            ['RunDemoDecimator requires a State structure input and ', ...
             'an optional logical ShowPlots input.']);
    end

    if nargin < 2 || isempty(ShowPlots)
        ShowPlots = true;
    end

    if ~islogical(ShowPlots) || ~isscalar(ShowPlots)
        error('RunDemoDecimator:InvalidPlotVisibility', ...
            'ShowPlots must be a logical scalar.');
    end

    RequiredStateFields = [ ...
        "Config"; ...
        "Parameters"; ...
        "Fs"; ...
        "Time"; ...
        "InputSignal"; ...
        "CurrentSignal"; ...
        "ADCEncoder"; ...
        "Sampler"; ...
        "SignalGenerator"];

    for k = 1:numel(RequiredStateFields)
        if ~isfield(State, RequiredStateFields(k))
            error('RunDemoDecimator:MissingStateField', ...
                'State.%s is required.', RequiredStateFields(k));
        end
    end

    RequiredEncoderFields = [ ...
        "TwosComplement"; ...
        "DecodedVoltage"; ...
        "InputFormat"; ...
        "LSBWeight_V"; ...
        "SamplingFrequency_Hz"; ...
        "FrameLength"; ...
        "OutputSampleCount"; ...
        "PowerRatios"; ...
        "AnalysisRecord"];

    for k = 1:numel(RequiredEncoderFields)
        if ~isfield(State.ADCEncoder, RequiredEncoderFields(k))
            error('RunDemoDecimator:MissingEncoderField', ...
                'State.ADCEncoder.%s is required.', ...
                RequiredEncoderFields(k));
        end
    end

    RequiredPowerRatioFields = [ ...
        "OutputComponentMeasurements"; ...
        "OutputBroadbandNoisePower_V2"; ...
        "OutputSNR_dB"; ...
        "OutputSINR_dB"];

    for k = 1:numel(RequiredPowerRatioFields)
        if ~isfield( ...
                State.ADCEncoder.PowerRatios, ...
                RequiredPowerRatioFields(k))
            error('RunDemoDecimator:MissingEncoderPowerRatioField', ...
                'State.ADCEncoder.PowerRatios.%s is required.', ...
                RequiredPowerRatioFields(k));
        end
    end

    RequiredAnalysisFields = [ ...
        "InputStartIndex"; ...
        "InputEndIndex"; ...
        "OutputSampleCount"; ...
        "PSDWindowLength"; ...
        "PSDOverlapLength"; ...
        "PSDFFTLength"];

    for k = 1:numel(RequiredAnalysisFields)
        if ~isfield( ...
                State.ADCEncoder.AnalysisRecord, ...
                RequiredAnalysisFields(k))
            error('RunDemoDecimator:MissingEncoderAnalysisField', ...
                'State.ADCEncoder.AnalysisRecord.%s is required.', ...
                RequiredAnalysisFields(k));
        end
    end

    if ~isfield(State.Sampler, "SampleIndex") || ...
            ~isfield(State.Sampler, "Aliasing") || ...
            ~isfield( ...
                State.Sampler.Aliasing, ...
                "PredictedAliasFrequency_Hz")
        error('RunDemoDecimator:MissingSamplerState', ...
            ['The sampler source indices and predicted ADC-rate ', ...
             'interference alias are required.']);
    end

    if ~isfield(State.SignalGenerator, "Measurements") || ...
            ~isfield( ...
                State.SignalGenerator.Measurements, ...
                "DesiredFrequencies_Hz") || ...
            ~isfield( ...
                State.SignalGenerator.Measurements, ...
                "InterferenceFrequency_Hz")
        error('RunDemoDecimator:MissingSignalMeasurements', ...
            ['The two receiver-measured data frequencies and the ', ...
             'measured interference frequency are required.']);
    end

    if ~isprop(State.Config, "DSPParams") || ...
            ~isprop(State.Config, "DecimatorRequirements")
        error('RunDemoDecimator:MissingDesignConfiguration', ...
            ['State.Config must provide DSPParams and ', ...
             'DecimatorRequirements.']);
    end

    DSPP = State.Config.DSPParams;
    Requirements = State.Config.DecimatorRequirements;
    P = State.Parameters;

    InputSamplingFrequency = double(State.Fs);
    InputTime = double(State.Time(:));
    InputCodes = State.CurrentSignal(:);
    EncoderCodes = State.ADCEncoder.TwosComplement(:);
    InputVoltage = double(State.ADCEncoder.DecodedVoltage(:));
    InputFormat = State.ADCEncoder.InputFormat;
    LSBWeight = double(State.ADCEncoder.LSBWeight_V);
    InputSourceSampleIndex = ...
        double(State.Sampler.SampleIndex(:));

    validateattributes( ...
        InputSamplingFrequency, ...
        {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, ...
        mfilename, ...
        'State.Fs');

    validateattributes( ...
        LSBWeight, ...
        {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, ...
        mfilename, ...
        'State.ADCEncoder.LSBWeight_V');

    if ~isa(InputCodes, 'int8') || isempty(InputCodes)
        error('RunDemoDecimator:InvalidInputCodes', ...
            ['State.CurrentSignal must be the nonempty signed int8 ', ...
             'two''s-complement stream produced by RunDemoADCEncoder.']);
    end

    NumberInputSamples = numel(InputCodes);

    if numel(InputTime) ~= NumberInputSamples || ...
            numel(InputVoltage) ~= NumberInputSamples || ...
            numel(EncoderCodes) ~= NumberInputSamples || ...
            numel(InputSourceSampleIndex) ~= NumberInputSamples
        error('RunDemoDecimator:StateLengthMismatch', ...
            ['The encoder codes, decoded voltage, input time, and ', ...
             'sampler source-index records must have equal lengths.']);
    end

    HandoffCodesOK = isequal(InputCodes, EncoderCodes);
    HandoffCountOK = NumberInputSamples == ...
        double(State.ADCEncoder.OutputSampleCount);
    VoltageScaleTolerance = max( ...
        1e-12, 32 * eps(max(abs(InputVoltage))));
    HandoffVoltageScaleOK = max(abs( ...
        InputVoltage - double(InputCodes) * LSBWeight)) <= ...
        VoltageScaleTolerance;

    if ~HandoffCodesOK || ~HandoffCountOK || ...
            ~HandoffVoltageScaleOK
        error('RunDemoDecimator:EncoderHandoffMismatch', ...
            ['State.CurrentSignal must be the complete encoder output ', ...
             'with the reported ADC voltage scale.']);
    end


    %% ==========================================
    %% APPROVED DECIMATOR CONFIGURATION
    %% ==========================================

    ConfiguredInputSamplingFrequency = ...
        double(DSPP.getValue("Fs_DSP"));
    DecimationFactor = double(DSPP.getValue("DcF"));
    FrameLength = double(DSPP.getValue("FrameLength"));
    Fpass = double(DSPP.getValue("Fpass"));
    Fstop = double(DSPP.getValue("Fstop"));
    Apass = double(DSPP.getValue("Apass"));
    Astop = double(DSPP.getValue("Astop"));

    validateattributes( ...
        DecimationFactor, ...
        {'numeric'}, ...
        {'scalar', 'integer', 'finite', 'positive'}, ...
        mfilename, ...
        'DcF');
    validateattributes( ...
        FrameLength, ...
        {'numeric'}, ...
        {'scalar', 'integer', 'finite', 'positive'}, ...
        mfilename, ...
        'FrameLength');

    RequiredRequirementFields = [ ...
        "HeadroomBits"; ...
        "MaxCoefficientWordLength"; ...
        "MaxAccumulatorWordLength"; ...
        "MaxGroupDelay_s"; ...
        "MaxDesiredToneLoss_dB"; ...
        "MaxFrequencyErrorBins"; ...
        "MinAliasAttenuation_dB"; ...
        "MinFixedPointErrorSNR_dB"; ...
        "MinMACReductionPercent"; ...
        "MinSNRImprovement_dB"; ...
        "MinSINRImprovement_dB"];

    for k = 1:numel(RequiredRequirementFields)
        if ~isfield(Requirements, RequiredRequirementFields(k))
            error('RunDemoDecimator:MissingRequirement', ...
                'DecimatorRequirements.%s is required.', ...
                RequiredRequirementFields(k));
        end
    end

    HeadroomBits = double(Requirements.HeadroomBits);
    validateattributes( ...
        HeadroomBits, ...
        {'numeric'}, ...
        {'scalar', 'integer', 'finite', 'nonnegative'}, ...
        mfilename, ...
        'DecimatorRequirements.HeadroomBits');

    OutputSamplingFrequency = ...
        InputSamplingFrequency / DecimationFactor;
    OutputNyquistFrequency = OutputSamplingFrequency / 2;

    RateTolerance = max( ...
        1e-3, 32 * eps(ConfiguredInputSamplingFrequency));
    InputRateOK = abs( ...
        InputSamplingFrequency - ...
        ConfiguredInputSamplingFrequency) <= RateTolerance;
    EncoderRateOK = abs( ...
        InputSamplingFrequency - ...
        double(State.ADCEncoder.SamplingFrequency_Hz)) <= ...
        RateTolerance;
    FrameLengthOK = FrameLength == ...
        double(State.ADCEncoder.FrameLength);
    FrequencyPlanOK = ...
        Fpass > 0 && ...
        Fpass < Fstop && ...
        Fstop <= OutputNyquistFrequency && ...
        OutputNyquistFrequency < InputSamplingFrequency / 2;

    if ~InputRateOK || ~EncoderRateOK || ...
            ~FrameLengthOK || ~FrequencyPlanOK
        error('RunDemoDecimator:ConfigurationMismatch', ...
            ['The DSP input rate, frame length, or anti-alias ', ...
             'frequency plan does not match the encoder handoff.']);
    end


    %% ==========================================
    %% FIXED FIR COEFFICIENT DESIGN
    %% ==========================================

    ReferenceDecimator = FixedDSPDecimator(DSPP);

    CoefficientFormat.WL = ReferenceDecimator.CoeffWL;
    CoefficientFormat.IWL = ReferenceDecimator.CoeffIWL;
    CoefficientFormat.FWL = ReferenceDecimator.CoeffFWL;

    FilterLength = numel(ReferenceDecimator.FilterCoefficients);
    GroupDelayInputSamples = (FilterLength - 1) / 2;
    GroupDelaySeconds = ...
        GroupDelayInputSamples / InputSamplingFrequency;

    NumberBranches = size( ...
        ReferenceDecimator.BranchCoefficients, 1);
    LongestBranchLength = size( ...
        ReferenceDecimator.BranchCoefficients, 2);
    RectangularBranchSlots = numel( ...
        ReferenceDecimator.BranchCoefficients);
    BranchTapCounts = LocalBranchTapCounts( ...
        FilterLength, DecimationFactor);

    ImplementedMACsPerInputSample = ...
        RectangularBranchSlots / DecimationFactor;
    MACReductionPercent = 100 * (1 - ...
        ImplementedMACsPerInputSample / FilterLength);


    %% ==========================================
    %% PASS 1: FULL-PRECISION INTEGER REFERENCE
    %% ==========================================

    [ReferenceCodes, ReferenceMACData, ReferenceFrames] = ...
        LocalProcessFixedStream( ...
            ReferenceDecimator, ...
            InputCodes, ...
            FrameLength, ...
            InputFormat, ...
            CoefficientFormat, ...
            []);


    %% ==========================================
    %% SAFE MAC FORMAT SELECTION
    %% ==========================================

    MACFormat = FindMACFormat( ...
        InputFormat, ...
        CoefficientFormat, ...
        ReferenceDecimator.BranchCoefficients, ...
        ReferenceMACData, ...
        HeadroomBits);


    %% ==========================================
    %% PASS 2: BOUNDED FIXED-POINT MAC
    %% ==========================================

    FixedDecimator = FixedDSPDecimator(DSPP);

    SameCoefficientDesignOK = ...
        isequal( ...
            FixedDecimator.FixedFilterCoefficients, ...
            ReferenceDecimator.FixedFilterCoefficients) && ...
        FixedDecimator.CoeffScale == ...
            ReferenceDecimator.CoeffScale;

    if ~SameCoefficientDesignOK
        error('RunDemoDecimator:CoefficientDesignChanged', ...
            ['The reference and bounded fixed-point paths must use ', ...
             'the same represented FIR coefficients.']);
    end

    [OutputCodes, MACData, FixedFrames] = ...
        LocalProcessFixedStream( ...
            FixedDecimator, ...
            InputCodes, ...
            FrameLength, ...
            InputFormat, ...
            CoefficientFormat, ...
            MACFormat);

    [OutputCodeDomainSignal, MACData] = ...
        FixedToRealConverter(OutputCodes, MACData);
    OutputVoltage = ...
        OutputCodeDomainSignal(:) * LSBWeight;

    ReferenceScale = ...
        2^(-ReferenceMACData.ProductFormat.FWL);
    ReferenceFixedVoltage = ...
        double(ReferenceCodes(:)) * ...
        ReferenceScale * LSBWeight;


    %% ==========================================
    %% FLOATING-POINT DESIGN REFERENCE
    %% ==========================================

    FloatingDecimator = DSP(DSPP);
    [FloatingOutput, FloatingFrames] = ...
        LocalProcessFloatingStream( ...
            FloatingDecimator, ...
            InputVoltage, ...
            FrameLength);


    %% ==========================================
    %% TARGET-RATE TIME BASE
    %% ==========================================

    OutputSampleIndex = FixedFrames.OutputSampleIndex;
    OutputInputSampleIndex = ...
        (OutputSampleIndex + 1) * DecimationFactor;
    OutputTime = InputTime(1) + ...
        (OutputInputSampleIndex - 1) / ...
        InputSamplingFrequency;


    %% ==========================================
    %% DESIGN-INTEGRATION CHECKS
    %% ==========================================

    ExpectedOutputSamples = ...
        ceil(NumberInputSamples / DecimationFactor);
    OutputSampleCountOK = ...
        numel(OutputCodes) == ExpectedOutputSamples && ...
        numel(OutputVoltage) == ExpectedOutputSamples && ...
        numel(FloatingOutput) == ExpectedOutputSamples;
    OutputIndexOK = isequal( ...
        OutputSampleIndex, ...
        (0:ExpectedOutputSamples - 1)');
    NoPaddingRequiredOK = ...
        ReferenceFrames.TotalPaddingSamples == 0 && ...
        FixedFrames.TotalPaddingSamples == 0 && ...
        FloatingFrames.TotalPaddingSamples == 0;
    ReferenceAgreementOK = isequal( ...
        OutputCodes(:), ReferenceCodes(:));
    ZeroOverflowOK = ...
        MACData.TotalAccumulatorOverflowCount == 0;
    CoefficientWordLengthOK = ...
        CoefficientFormat.WL <= ...
        double(Requirements.MaxCoefficientWordLength);
    AccumulatorWordLengthOK = ...
        MACFormat.WL <= ...
        double(Requirements.MaxAccumulatorWordLength);
    GroupDelayOK = ...
        GroupDelaySeconds <= ...
        double(Requirements.MaxGroupDelay_s);
    TypeILinearPhaseOK = ...
        mod(FilterLength, 2) == 1 && ...
        max(abs( ...
            ReferenceDecimator.FilterCoefficients(:) - ...
            flipud(ReferenceDecimator.FilterCoefficients(:)))) <= ...
        128 * eps;
    BranchStructureOK = ...
        NumberBranches == DecimationFactor && ...
        sum(BranchTapCounts) == FilterLength;

    OverallDesignOK = ...
        HandoffCodesOK && ...
        HandoffCountOK && ...
        HandoffVoltageScaleOK && ...
        InputRateOK && ...
        EncoderRateOK && ...
        FrameLengthOK && ...
        FrequencyPlanOK && ...
        SameCoefficientDesignOK && ...
        OutputSampleCountOK && ...
        OutputIndexOK && ...
        NoPaddingRequiredOK && ...
        ReferenceAgreementOK && ...
        ZeroOverflowOK && ...
        CoefficientWordLengthOK && ...
        AccumulatorWordLengthOK && ...
        GroupDelayOK && ...
        TypeILinearPhaseOK && ...
        BranchStructureOK;


    %% ==========================================
    %% DESIGN IMPLEMENTATION SUMMARY
    %% ==========================================

    fprintf("\n");
    fprintf("============================================================\n");
    fprintf("FIXED-POINT POLYPHASE FIR DECIMATOR DESIGN SUMMARY\n");
    fprintf("============================================================\n");
    fprintf("Input representation             : signed int8, Q%d.%d\n", ...
        InputFormat.IWL, InputFormat.FWL);
    fprintf("ADC voltage scale                : %.9f V/code\n", ...
        LSBWeight);
    fprintf("Input / output sample rate       : %.6f / %.6f GS/s\n", ...
        InputSamplingFrequency / 1e9, ...
        OutputSamplingFrequency / 1e9);
    fprintf("Decimation factor                : %d\n", ...
        DecimationFactor);
    fprintf("Input / output frame length      : %d / %d samples\n", ...
        FrameLength, FrameLength / DecimationFactor);
    fprintf("Input / output record length     : %d / %d samples\n", ...
        NumberInputSamples, numel(OutputCodes));
    fprintf("Passband / stopband edge         : %.6f / %.6f GHz\n", ...
        Fpass / 1e9, Fstop / 1e9);
    fprintf("Required ripple / attenuation    : %.4f / %.4f dB\n", ...
        Apass, Astop);
    fprintf("Kaiser Type-I FIR length         : %d taps\n", ...
        FilterLength);
    fprintf("Group delay                      : %d samples (%.4f ns)\n", ...
        GroupDelayInputSamples, GroupDelaySeconds * 1e9);
    fprintf("Polyphase branch tap counts      : %s\n", ...
        mat2str(BranchTapCounts));
    fprintf("Longest branch / padded slots    : %d / %d\n", ...
        LongestBranchLength, RectangularBranchSlots - FilterLength);
    fprintf("Implemented MACs per input       : %.3f\n", ...
        ImplementedMACsPerInputSample);
    fprintf("MAC reduction versus direct FIR  : %.3f %%\n", ...
        MACReductionPercent);
    fprintf("Coefficient format               : Q%d.%d (%d bits)\n", ...
        CoefficientFormat.IWL, ...
        CoefficientFormat.FWL, ...
        CoefficientFormat.WL);
    fprintf("Product format                   : Q%d.%d (%d bits)\n", ...
        MACFormat.ProductIWL, ...
        MACFormat.ProductFWL, ...
        MACFormat.ProductWL);
    fprintf("Accumulator format               : Q%d.%d (%d bits)\n", ...
        MACFormat.IWL, MACFormat.FWL, MACFormat.WL);
    fprintf("Headroom / rounding / overflow   : %d bit / %s / %s\n", ...
        HeadroomBits, ...
        MACFormat.RoundingMethod, ...
        MACFormat.OverflowAction);
    fprintf("Accumulator overflow events      : %d\n", ...
        MACData.TotalAccumulatorOverflowCount);
    fprintf("Reference / bounded code match   : %s\n", ...
        LocalPassFail(ReferenceAgreementOK));
    fprintf("Overall decimator design         : %s\n", ...
        LocalPassFail(OverallDesignOK));


    %% ==========================================
    %% FIXED FIR RESPONSE AND ALIAS PROTECTION
    %% ==========================================

    MaximumDesiredToneLoss_dB = ...
        double(Requirements.MaxDesiredToneLoss_dB);
    MaximumFrequencyErrorBins = ...
        double(Requirements.MaxFrequencyErrorBins);
    MinimumAliasAttenuation_dB = ...
        double(Requirements.MinAliasAttenuation_dB);
    MinimumFixedPointErrorSNR_dB = ...
        double(Requirements.MinFixedPointErrorSNR_dB);
    MinimumMACReductionPercent = ...
        double(Requirements.MinMACReductionPercent);
    MinimumSNRImprovement_dB = ...
        double(Requirements.MinSNRImprovement_dB);
    MinimumSINRImprovement_dB = ...
        double(Requirements.MinSINRImprovement_dB);

    PerformanceRequirementValues = [ ...
        MaximumDesiredToneLoss_dB, ...
        MaximumFrequencyErrorBins, ...
        MinimumAliasAttenuation_dB, ...
        MinimumFixedPointErrorSNR_dB, ...
        MinimumMACReductionPercent, ...
        MinimumSNRImprovement_dB, ...
        MinimumSINRImprovement_dB];

    if any(~isfinite(PerformanceRequirementValues)) || ...
            any(PerformanceRequirementValues < 0)
        error('RunDemoDecimator:InvalidPerformanceRequirement', ...
            ['Every decimator performance requirement must be a ', ...
             'finite nonnegative scalar.']);
    end

    FloatingCoefficients = double( ...
        ReferenceDecimator.FilterCoefficients(:));
    FixedCoefficientCodes = double( ...
        ReferenceDecimator.FixedFilterCoefficients(:));
    CoefficientScale = double(ReferenceDecimator.CoeffScale);
    FixedCoefficients = FixedCoefficientCodes / CoefficientScale;
    ResponsePointCount = double(FixedDecimator.NPoint);

    [ResponsePassbandOK, ResponseStopbandOK, ...
        ResponseOverallOK, PassbandRipple_dB, ...
        StopbandAttenuation_dB, TransitionWidth_Hz, ...
        WorstStopbandFrequency_Hz] = ...
        CheckFIRResponse( ...
            FixedCoefficients, DSPP, ResponsePointCount);

    [AliasProtectionOK, StopbandPlacementOK, ...
        AliasResponseOK, CheckedOutputRate_Hz, ...
        CheckedOutputNyquist_Hz, CheckedStopbandEdge_Hz, ...
        AliasBandAttenuation_dB, ...
        WorstAliasFrequency_Hz] = ...
        CheckDecimatorAliasProtection( ...
            FixedCoefficients, DSPP, ResponsePointCount);

    [CoefficientRMSE, MaximumCoefficientError, ...
        MaximumComplexResponseError, ...
        FloatingPassbandRipple_dB, ...
        FixedPassbandRipple_dB, ...
        PassbandRippleChange_dB, ...
        FloatingStopbandAttenuation_dB, ...
        FixedStopbandAttenuation_dB, ...
        StopbandAttenuationChange_dB, ...
        ComparisonPassbandOK, ComparisonStopbandOK, ...
        ComparisonOverallOK] = ...
        CompareFIRResponses( ...
            FloatingCoefficients, ...
            FixedCoefficientCodes, ...
            CoefficientScale, ...
            DSPP, ...
            ResponsePointCount);

    AliasAttenuationRequirementOK = ...
        AliasBandAttenuation_dB >= MinimumAliasAttenuation_dB;


    %% ==========================================
    %% FIXED-POINT AND POLYPHASE CHARACTERIZATION
    %% ==========================================

    PerformanceAnalyzer = DecimatorAnalyzer(DSPP);
    FixedPointMetrics = ...
        PerformanceAnalyzer.CharacterizeFixedPointDesign( ...
            FloatingOutput, ...
            OutputVoltage, ...
            FixedDecimator, ...
            InputFormat, ...
            MACFormat, ...
            MACData);
    ArchitectureMetrics = ...
        PerformanceAnalyzer.CharacterizePolyphaseArchitecture( ...
            FixedDecimator);

    FixedPointErrorSNR_dB = ...
        FixedPointMetrics.OutputError.ErrorSNRdB;
    FixedPointErrorSNROK = ...
        isinf(FixedPointErrorSNR_dB) || ...
        (isfinite(FixedPointErrorSNR_dB) && ...
        FixedPointErrorSNR_dB >= MinimumFixedPointErrorSNR_dB);
    MeasuredMACReductionPercent = ...
        ArchitectureMetrics.Computation.ImplementedMACReductionPercent;
    MACReductionOK = ...
        MeasuredMACReductionPercent >= ...
        MinimumMACReductionPercent;


    %% ==========================================
    %% FULL-RECORD HAMMING-FFT TONE PRESERVATION
    %% ==========================================

    DesiredFrequencies = double( ...
        State.SignalGenerator.Measurements.DesiredFrequencies_Hz(:));
    InputInterferenceAliasFrequency = double( ...
        State.Sampler.Aliasing.PredictedAliasFrequency_Hz);

    if numel(DesiredFrequencies) ~= 2 || ...
            any(~isfinite(DesiredFrequencies)) || ...
            ~isscalar(InputInterferenceAliasFrequency) || ...
            ~isfinite(InputInterferenceAliasFrequency)
        error('RunDemoDecimator:InvalidMeasuredFrequencies', ...
            ['Exactly two finite desired frequencies and one finite ', ...
             'ADC-rate interference alias are required.']);
    end

    DesiredBandBelowOutputNyquistOK = ...
        all(DesiredFrequencies > 0 & ...
        DesiredFrequencies < OutputNyquistFrequency);

    if ~DesiredBandBelowOutputNyquistOK
        error('RunDemoDecimator:DesiredBandAboveOutputNyquist', ...
            ['Both receiver-measured data tones must lie below the ', ...
             'target-rate Nyquist frequency.']);
    end

    OutputAliasFrequency = LocalFoldToFirstNyquist( ...
        InputInterferenceAliasFrequency, ...
        OutputSamplingFrequency);

    InputSpectrum = SpectrumAnalyzer(P, InputSamplingFrequency);
    OutputSpectrum = SpectrumAnalyzer(P, OutputSamplingFrequency);

    [InputFFTFrequency, InputMagnitude] = ...
        InputSpectrum.HammingFFT(InputVoltage);
    [OutputFFTFrequency, OutputMagnitude] = ...
        OutputSpectrum.HammingFFT(OutputVoltage);

    InputTrueFrequencyResolution = ...
        InputSamplingFrequency / NumberInputSamples;
    OutputTrueFrequencyResolution = ...
        OutputSamplingFrequency / numel(OutputVoltage);
    TrueResolutionTolerance = max( ...
        1e-9, 32 * eps(InputTrueFrequencyResolution));
    MatchedTrueResolutionOK = abs( ...
        OutputTrueFrequencyResolution - ...
        InputTrueFrequencyResolution) <= ...
        TrueResolutionTolerance;
    TrueFrequencyResolution = max( ...
        InputTrueFrequencyResolution, ...
        OutputTrueFrequencyResolution);

    FFTGridTolerance = max( ...
        1e-3, 32 * eps(OutputSamplingFrequency));
    InputComparisonFFTMask = ...
        InputFFTFrequency <= ...
        OutputNyquistFrequency + FFTGridTolerance;
    InputComparisonFFTFrequency = ...
        InputFFTFrequency(InputComparisonFFTMask);
    InputComparisonMagnitude = ...
        InputMagnitude(InputComparisonFFTMask);

    OutputComparisonIndices = ...
        (1:DecimationFactor:numel(OutputFFTFrequency))';
    OutputComparisonFFTFrequency = ...
        OutputFFTFrequency(OutputComparisonIndices);
    OutputComparisonMagnitude = ...
        OutputMagnitude(OutputComparisonIndices);

    if numel(InputComparisonFFTFrequency) ~= ...
            numel(OutputComparisonFFTFrequency) || ...
            any(abs( ...
                InputComparisonFFTFrequency - ...
                OutputComparisonFFTFrequency) > ...
                FFTGridTolerance)
        error('RunDemoDecimator:FFTGridMismatch', ...
            ['Input and output Hamming-FFT comparison grids must ', ...
             'match through the target-rate Nyquist frequency.']);
    end

    MinimumToneSeparation = min(diff(sort(DesiredFrequencies)));

    if MinimumToneSeparation <= 0
        error('RunDemoDecimator:UnresolvedDesiredFrequencies', ...
            'The two desired frequencies must be distinct.');
    end

    ToneSearchHalfWidth = 0.4 * MinimumToneSeparation;

    [InputMeasuredToneFrequency, InputMeasuredToneMagnitude] = ...
        LocalMeasureFFTPeaks( ...
            InputComparisonFFTFrequency, ...
            InputComparisonMagnitude, ...
            DesiredFrequencies, ...
            ToneSearchHalfWidth);
    [OutputMeasuredToneFrequency, OutputMeasuredToneMagnitude] = ...
        LocalMeasureFFTPeaks( ...
            OutputComparisonFFTFrequency, ...
            OutputComparisonMagnitude, ...
            DesiredFrequencies, ...
            ToneSearchHalfWidth);

    ToneFrequencyChange_Hz = ...
        OutputMeasuredToneFrequency - ...
        InputMeasuredToneFrequency;
    ToneFrequencyError_Bins = ...
        abs(ToneFrequencyChange_Hz) / ...
        TrueFrequencyResolution;
    InputToneLevel_dBV = 20 * log10(max( ...
        InputMeasuredToneMagnitude, realmin("double")));
    OutputToneLevel_dBV = 20 * log10(max( ...
        OutputMeasuredToneMagnitude, realmin("double")));
    ToneLevelChange_dB = ...
        OutputToneLevel_dBV - InputToneLevel_dBV;
    ToneLoss_dB = max(0, -ToneLevelChange_dB);

    ToneFrequencyPreservationOK = ...
        all(ToneFrequencyError_Bins <= ...
        MaximumFrequencyErrorBins);
    ToneLevelPreservationOK = ...
        all(ToneLoss_dB <= MaximumDesiredToneLoss_dB);

    TonePreservationSummary = table( ...
        ["Data Signal 1"; "Data Signal 2"], ...
        DesiredFrequencies, ...
        InputMeasuredToneFrequency, ...
        OutputMeasuredToneFrequency, ...
        ToneFrequencyChange_Hz, ...
        ToneFrequencyError_Bins, ...
        InputToneLevel_dBV, ...
        OutputToneLevel_dBV, ...
        ToneLevelChange_dB, ...
        ToneLoss_dB, ...
        'VariableNames', { ...
            'Component', ...
            'ReceiverTargetFrequency_Hz', ...
            'BeforeDecimatorFrequency_Hz', ...
            'AfterDecimatorFrequency_Hz', ...
            'FrequencyChange_Hz', ...
            'FrequencyError_Bins', ...
            'BeforeDecimatorLevel_dBV', ...
            'AfterDecimatorLevel_dBV', ...
            'LevelChange_dB', ...
            'ToneLoss_dB'});


    %% ==========================================
    %% MATCHED-TIME HAMMING-WELCH SNR / SINR
    %% ==========================================
    % The ADC-rate and target-rate Welch windows contain the same amount
    % of physical time. The input SNR integrates the complete 0-5 GHz ADC
    % band; the output SNR integrates the complete 0-1.25 GHz target band.
    % Their difference therefore measures the useful noise-band reduction
    % created by the anti-alias FIR and factor-of-four decimation.

    AnalysisStartIndex = double( ...
        State.ADCEncoder.AnalysisRecord.InputStartIndex);
    AnalysisEndIndex = double( ...
        State.ADCEncoder.AnalysisRecord.InputEndIndex);

    if ~isscalar(AnalysisStartIndex) || ...
            ~isscalar(AnalysisEndIndex) || ...
            AnalysisStartIndex < 1 || ...
            AnalysisStartIndex ~= fix(AnalysisStartIndex) || ...
            AnalysisEndIndex ~= fix(AnalysisEndIndex) || ...
            AnalysisEndIndex < AnalysisStartIndex
        error('RunDemoDecimator:InvalidAnalysisRecord', ...
            'The ADC-encoder analysis-record indices are invalid.');
    end

    InputAnalysisMask = ...
        InputSourceSampleIndex >= AnalysisStartIndex - 1 & ...
        InputSourceSampleIndex <= AnalysisEndIndex - 1;
    InputAnalysisRecord = InputVoltage(InputAnalysisMask);

    if numel(InputAnalysisRecord) ~= double( ...
            State.ADCEncoder.AnalysisRecord.OutputSampleCount)
        error('RunDemoDecimator:EncoderAnalysisRecordMismatch', ...
            ['The reconstructed decimator-input analysis record must ', ...
             'match the ADC encoder measurement record.']);
    end

    if any(OutputInputSampleIndex < 1) || ...
            any(OutputInputSampleIndex > NumberInputSamples) || ...
            any(OutputInputSampleIndex ~= fix(OutputInputSampleIndex))
        error('RunDemoDecimator:InvalidOutputSourceIndex', ...
            'A target-rate sample maps outside the ADC input record.');
    end

    OutputSourceSampleIndex = ...
        InputSourceSampleIndex(OutputInputSampleIndex);
    OutputAnalysisMask = ...
        OutputSourceSampleIndex >= AnalysisStartIndex - 1 & ...
        OutputSourceSampleIndex <= AnalysisEndIndex - 1;
    OutputAnalysisRecord = OutputVoltage(OutputAnalysisMask);

    InputPSDWindowLength = double( ...
        State.ADCEncoder.AnalysisRecord.PSDWindowLength);
    InputPSDOverlapLength = double( ...
        State.ADCEncoder.AnalysisRecord.PSDOverlapLength);
    InputPSDFFTLength = double( ...
        State.ADCEncoder.AnalysisRecord.PSDFFTLength);

    InputPSDLengths = [ ...
        InputPSDWindowLength, ...
        InputPSDOverlapLength, ...
        InputPSDFFTLength];

    if any(mod(InputPSDLengths, DecimationFactor) ~= 0)
        error('RunDemoDecimator:UnmatchedPSDConfiguration', ...
            ['The ADC-rate Welch window, overlap, and FFT lengths ', ...
             'must be divisible by the decimation factor.']);
    end

    OutputPSDWindowLength = ...
        InputPSDWindowLength / DecimationFactor;
    OutputPSDOverlapLength = ...
        InputPSDOverlapLength / DecimationFactor;
    OutputPSDFFTLength = ...
        InputPSDFFTLength / DecimationFactor;

    if numel(InputAnalysisRecord) < InputPSDWindowLength || ...
            numel(OutputAnalysisRecord) < OutputPSDWindowLength
        error('RunDemoDecimator:AnalysisRecordTooShort', ...
            ['The matched input/output analysis records must each ', ...
             'contain one complete Welch window.']);
    end

    [InputPSDFrequency, InputPowerPSD] = ...
        LocalHammingPSD( ...
            InputAnalysisRecord, ...
            InputSamplingFrequency, ...
            InputPSDWindowLength, ...
            InputPSDOverlapLength, ...
            InputPSDFFTLength);
    [OutputPSDFrequency, OutputPowerPSD] = ...
        LocalHammingPSD( ...
            OutputAnalysisRecord, ...
            OutputSamplingFrequency, ...
            OutputPSDWindowLength, ...
            OutputPSDOverlapLength, ...
            OutputPSDFFTLength);

    InputCommonPSDMask = ...
        InputPSDFrequency <= ...
        OutputNyquistFrequency + FFTGridTolerance;
    InputCommonPSDFrequency = ...
        InputPSDFrequency(InputCommonPSDMask);

    if numel(InputCommonPSDFrequency) ~= ...
            numel(OutputPSDFrequency) || ...
            any(abs( ...
                InputCommonPSDFrequency - ...
                OutputPSDFrequency) > FFTGridTolerance)
        error('RunDemoDecimator:PSDGridMismatch', ...
            ['Matched-time input and output Welch PSD grids must ', ...
             'agree through the target-rate Nyquist frequency.']);
    end

    InputComponentFrequencies = [ ...
        DesiredFrequencies; ...
        InputInterferenceAliasFrequency];
    OutputComponentFrequencies = [ ...
        DesiredFrequencies; ...
        OutputAliasFrequency];
    InputComponentNames = [ ...
        "Data Signal 1"; ...
        "Data Signal 2"; ...
        "ADC-Rate Interference Alias"];
    OutputComponentNames = [ ...
        "Data Signal 1"; ...
        "Data Signal 2"; ...
        "Target-Rate Interference Alias"];

    InputComponentMeasurements = ...
        InputSpectrum.MeasureComponentPowerAmplitude( ...
            InputPowerPSD, ...
            InputPSDFrequency, ...
            InputPSDWindowLength, ...
            InputComponentFrequencies, ...
            InputComponentNames);
    OutputComponentMeasurements = ...
        OutputSpectrum.MeasureComponentPowerAmplitude( ...
            OutputPowerPSD, ...
            OutputPSDFrequency, ...
            OutputPSDWindowLength, ...
            OutputComponentFrequencies, ...
            OutputComponentNames);

    InputPSDSpacing = ...
        InputPSDFrequency(2) - InputPSDFrequency(1);
    OutputPSDSpacing = ...
        OutputPSDFrequency(2) - OutputPSDFrequency(1);
    PSDSpacingTolerance = max( ...
        1e-9, 32 * eps(InputPSDSpacing));

    if abs(InputPSDSpacing - OutputPSDSpacing) > ...
            PSDSpacingTolerance
        error('RunDemoDecimator:PSDSpacingMismatch', ...
            ['Matched-time input and output Welch analyses must have ', ...
             'the same frequency-bin spacing.']);
    end

    DesiredBandLower = min(DesiredFrequencies) - 50e6;
    DesiredBandUpper = max(DesiredFrequencies) + 50e6;
    AliasGuardHalfWidth = 50e6;
    DCGuardBandwidth = ...
        2 * InputSamplingFrequency / InputPSDWindowLength;

    InputBroadbandNoiseMask = ...
        InputPSDFrequency > DCGuardBandwidth & ...
        ~(InputPSDFrequency >= DesiredBandLower & ...
        InputPSDFrequency <= DesiredBandUpper) & ...
        abs(InputPSDFrequency - ...
        InputInterferenceAliasFrequency) > AliasGuardHalfWidth;
    OutputBroadbandNoiseMask = ...
        OutputPSDFrequency > DCGuardBandwidth & ...
        ~(OutputPSDFrequency >= DesiredBandLower & ...
        OutputPSDFrequency <= DesiredBandUpper) & ...
        abs(OutputPSDFrequency - ...
        OutputAliasFrequency) > AliasGuardHalfWidth;

    if ~any(InputBroadbandNoiseMask) || ...
            ~any(OutputBroadbandNoiseMask)
        error('RunDemoDecimator:EmptyNoiseMeasurementBand', ...
            ['No PSD bins remain in an input or output broadband-noise ', ...
             'measurement region.']);
    end

    InputDesiredSignalPower = sum( ...
        InputComponentMeasurements.ComponentPower_V2(1:2));
    OutputDesiredSignalPower = sum( ...
        OutputComponentMeasurements.ComponentPower_V2(1:2));
    InputBroadbandNoisePower = sum( ...
        InputPowerPSD(InputBroadbandNoiseMask)) * ...
        InputPSDSpacing;
    OutputBroadbandNoisePower = sum( ...
        OutputPowerPSD(OutputBroadbandNoiseMask)) * ...
        OutputPSDSpacing;
    InputInterferencePower = ...
        InputComponentMeasurements.ComponentPower_V2(3);
    OutputAliasPower = ...
        OutputComponentMeasurements.ComponentPower_V2(3);

    InputSNR_dB = 10 * log10( ...
        max(InputDesiredSignalPower, realmin("double")) / ...
        max(InputBroadbandNoisePower, realmin("double")));
    OutputSNR_dB = 10 * log10( ...
        max(OutputDesiredSignalPower, realmin("double")) / ...
        max(OutputBroadbandNoisePower, realmin("double")));
    InputSINR_dB = 10 * log10( ...
        max(InputDesiredSignalPower, realmin("double")) / ...
        max( ...
            InputBroadbandNoisePower + InputInterferencePower, ...
            realmin("double")));
    OutputSINR_dB = 10 * log10( ...
        max(OutputDesiredSignalPower, realmin("double")) / ...
        max( ...
            OutputBroadbandNoisePower + OutputAliasPower, ...
            realmin("double")));

    SNRImprovement_dB = OutputSNR_dB - InputSNR_dB;
    SINRImprovement_dB = OutputSINR_dB - InputSINR_dB;
    ReceivedAliasSuppression_dB = 10 * log10( ...
        max(InputInterferencePower, realmin("double")) / ...
        max(OutputAliasPower, realmin("double")));

    UpstreamSNR_dB = double( ...
        State.ADCEncoder.PowerRatios.OutputSNR_dB);
    UpstreamSINR_dB = double( ...
        State.ADCEncoder.PowerRatios.OutputSINR_dB);
    UpstreamBroadbandNoisePower = double( ...
        State.ADCEncoder.PowerRatios.OutputBroadbandNoisePower_V2);
    UpstreamComponentMeasurements = ...
        State.ADCEncoder.PowerRatios.OutputComponentMeasurements;

    RequiredComponentVariables = { ...
        'MeasuredFrequency_Hz', ...
        'ComponentPower_V2'};

    if ~istable(UpstreamComponentMeasurements) || ...
            height(UpstreamComponentMeasurements) < 3 || ...
            any(~ismember( ...
                RequiredComponentVariables, ...
                UpstreamComponentMeasurements.Properties.VariableNames))
        error('RunDemoDecimator:InvalidEncoderPowerMeasurements', ...
            ['The ADC-encoder component-power table must contain ', ...
             'Data 1, Data 2, and the ADC-rate interference alias.']);
    end

    HandoffMetricScale = max(1, max(abs([ ...
        InputSNR_dB, InputSINR_dB, ...
        UpstreamSNR_dB, UpstreamSINR_dB])));
    HandoffMetricTolerance_dB = max( ...
        1e-10, 256 * eps(HandoffMetricScale));
    HandoffPowerScale = max(1, max(abs([ ...
        InputDesiredSignalPower; ...
        InputBroadbandNoisePower; ...
        InputInterferencePower])));
    HandoffPowerTolerance = max( ...
        1e-14, 256 * eps(HandoffPowerScale));
    PowerRatioHandoffOK = ...
        abs(InputSNR_dB - UpstreamSNR_dB) <= ...
        HandoffMetricTolerance_dB && ...
        abs(InputSINR_dB - UpstreamSINR_dB) <= ...
        HandoffMetricTolerance_dB && ...
        abs(InputBroadbandNoisePower - ...
        UpstreamBroadbandNoisePower) <= ...
        HandoffPowerTolerance && ...
        all(abs( ...
            InputComponentMeasurements.MeasuredFrequency_Hz - ...
            UpstreamComponentMeasurements.MeasuredFrequency_Hz(1:3)) <= ...
            FFTGridTolerance) && ...
        all(abs( ...
            InputComponentMeasurements.ComponentPower_V2 - ...
            UpstreamComponentMeasurements.ComponentPower_V2(1:3)) <= ...
            HandoffPowerTolerance);
    SNRImprovementOK = ...
        SNRImprovement_dB >= MinimumSNRImprovement_dB;
    SINRImprovementOK = ...
        SINRImprovement_dB >= MinimumSINRImprovement_dB;

    InputNoiseMeasurementBandwidth_Hz = ...
        nnz(InputBroadbandNoiseMask) * InputPSDSpacing;
    OutputNoiseMeasurementBandwidth_Hz = ...
        nnz(OutputBroadbandNoiseMask) * OutputPSDSpacing;

    PowerRatioSummary = table( ...
        ["Decimator Input (0-5 GHz)"; ...
         "Decimator Output (0-1.25 GHz)"], ...
        [InputNoiseMeasurementBandwidth_Hz; ...
         OutputNoiseMeasurementBandwidth_Hz] / 1e9, ...
        [InputDesiredSignalPower; OutputDesiredSignalPower], ...
        [InputBroadbandNoisePower; OutputBroadbandNoisePower], ...
        [InputInterferencePower; OutputAliasPower], ...
        [InputSNR_dB; OutputSNR_dB], ...
        [InputSINR_dB; OutputSINR_dB], ...
        'VariableNames', { ...
            'Observation', ...
            'NoiseMeasurementBandwidth_GHz', ...
            'DesiredSignalPower_V2', ...
            'BroadbandNoisePower_V2', ...
            'InterferenceOrAliasPower_V2', ...
            'SNR_dB', ...
            'SINR_dB'});


    %% ==========================================
    %% OVERALL DECIMATOR PERFORMANCE DECISION
    %% ==========================================

    OverallPerformanceOK = ...
        ResponsePassbandOK && ...
        ResponseStopbandOK && ...
        ResponseOverallOK && ...
        ComparisonPassbandOK && ...
        ComparisonStopbandOK && ...
        ComparisonOverallOK && ...
        StopbandPlacementOK && ...
        AliasResponseOK && ...
        AliasProtectionOK && ...
        AliasAttenuationRequirementOK && ...
        FixedPointErrorSNROK && ...
        MACReductionOK && ...
        DesiredBandBelowOutputNyquistOK && ...
        MatchedTrueResolutionOK && ...
        ToneFrequencyPreservationOK && ...
        ToneLevelPreservationOK && ...
        PowerRatioHandoffOK && ...
        SNRImprovementOK && ...
        SINRImprovementOK;
    OverallDecimatorOK = OverallDesignOK && OverallPerformanceOK;


    %% ==========================================
    %% RECEIVED-SIGNAL PERFORMANCE SUMMARY
    %% ==========================================

    fprintf("\n");
    fprintf("============================================================\n");
    fprintf("FIXED-POINT POLYPHASE FIR DECIMATOR PERFORMANCE SUMMARY\n");
    fprintf("============================================================\n");

    fprintf("Filter and alias response\n");
    fprintf("  Fixed passband ripple           : %.6f dB (limit %.6f dB)\n", ...
        PassbandRipple_dB, Apass);
    fprintf("  Fixed stopband attenuation      : %.6f dB (minimum %.6f dB)\n", ...
        StopbandAttenuation_dB, Astop);
    fprintf("  Transition width                : %.6f MHz\n", ...
        TransitionWidth_Hz / 1e6);
    fprintf("  Worst stopband frequency        : %.6f GHz\n", ...
        WorstStopbandFrequency_Hz / 1e9);
    fprintf("  Alias-band attenuation          : %.6f dB (minimum %.6f dB)\n", ...
        AliasBandAttenuation_dB, MinimumAliasAttenuation_dB);
    fprintf("  Worst alias-band frequency      : %.6f GHz\n", ...
        WorstAliasFrequency_Hz / 1e9);

    fprintf("\nFloating / fixed response tradeoff\n");
    fprintf("  Coefficient RMSE                : %.9e\n", ...
        CoefficientRMSE);
    fprintf("  Maximum coefficient error       : %.9e\n", ...
        MaximumCoefficientError);
    fprintf("  Maximum complex-response error  : %.9e\n", ...
        MaximumComplexResponseError);
    fprintf("  Passband-ripple change          : %+.9f dB\n", ...
        PassbandRippleChange_dB);
    fprintf("  Stopband-attenuation change     : %+.9f dB\n", ...
        StopbandAttenuationChange_dB);
    fprintf("  Fixed-point output-error SNR    : %.6f dB\n", ...
        FixedPointErrorSNR_dB);

    fprintf("\nMeasured Data 1 / Data 2 preservation\n");
    disp(TonePreservationSummary);
    fprintf("  Allowed frequency error         : %.3f true-resolution bin(s)\n", ...
        MaximumFrequencyErrorBins);
    fprintf("  Allowed desired-tone loss       : %.3f dB\n", ...
        MaximumDesiredToneLoss_dB);
    fprintf("  True full-record resolution     : %.6f kHz\n", ...
        TrueFrequencyResolution / 1e3);

    fprintf("\nInterference-alias observation\n");
    fprintf("  ADC-rate interference alias     : %.6f GHz\n", ...
        InputInterferenceAliasFrequency / 1e9);
    fprintf("  Target-rate folded alias        : %.6f GHz\n", ...
        OutputAliasFrequency / 1e9);
    fprintf("  Input interference power        : %.9e V^2\n", ...
        InputInterferencePower);
    fprintf("  Output alias power              : %.9e V^2\n", ...
        OutputAliasPower);
    fprintf("  Received alias suppression      : %.6f dB\n", ...
        ReceivedAliasSuppression_dB);

    fprintf("\nMatched-time full-band power-ratio comparison\n");
    fprintf("  ADC / target Welch windows      : %d / %d samples\n", ...
        InputPSDWindowLength, OutputPSDWindowLength);
    fprintf("  Common physical window duration : %.6f microseconds\n", ...
        InputPSDWindowLength / InputSamplingFrequency * 1e6);
    fprintf("  Shared PSD-bin spacing          : %.6f kHz\n", ...
        InputPSDSpacing / 1e3);
    fprintf("  Upstream encoder SNR / SINR     : %.6f / %.6f dB\n", ...
        UpstreamSNR_dB, UpstreamSINR_dB);
    disp(PowerRatioSummary);
    fprintf("  SNR improvement                 : %+.6f dB (minimum %.6f dB)\n", ...
        SNRImprovement_dB, MinimumSNRImprovement_dB);
    fprintf("  SINR improvement                : %+.6f dB (minimum %.6f dB)\n", ...
        SINRImprovement_dB, MinimumSINRImprovement_dB);

    fprintf("\nArchitecture tradeoff\n");
    fprintf("  Implemented MAC reduction       : %.6f %% (minimum %.6f %%)\n", ...
        MeasuredMACReductionPercent, MinimumMACReductionPercent);
    fprintf("  Coefficient / accumulator width : %d / %d bits\n", ...
        CoefficientFormat.WL, MACFormat.WL);
    fprintf("  Group delay                     : %.6f ns (maximum %.6f ns)\n", ...
        GroupDelaySeconds * 1e9, ...
        double(Requirements.MaxGroupDelay_s) * 1e9);

    fprintf("\nDecimator compliance\n");
    fprintf("  Fixed FIR passband              : %s\n", ...
        LocalPassFail(ResponsePassbandOK && ComparisonPassbandOK));
    fprintf("  Fixed FIR stopband              : %s\n", ...
        LocalPassFail(ResponseStopbandOK && ComparisonStopbandOK));
    fprintf("  Alias protection                : %s\n", ...
        LocalPassFail( ...
        AliasProtectionOK && AliasAttenuationRequirementOK));
    fprintf("  Fixed-point numeric accuracy    : %s\n", ...
        LocalPassFail(FixedPointErrorSNROK));
    fprintf("  Polyphase MAC reduction         : %s\n", ...
        LocalPassFail(MACReductionOK));
    fprintf("  Desired-tone frequency          : %s\n", ...
        LocalPassFail(ToneFrequencyPreservationOK));
    fprintf("  Desired-tone level              : %s\n", ...
        LocalPassFail(ToneLevelPreservationOK));
    fprintf("  Encoder power-ratio handoff     : %s\n", ...
        LocalPassFail(PowerRatioHandoffOK));
    fprintf("  SNR improvement                 : %s\n", ...
        LocalPassFail(SNRImprovementOK));
    fprintf("  SINR improvement                : %s\n", ...
        LocalPassFail(SINRImprovementOK));
    fprintf("\nOverall decimator performance    : %s\n", ...
        LocalPassFail(OverallDecimatorOK));


    %% ==========================================
    %% APPROVED DECIMATOR FIGURES
    %% ==========================================

    if ShowPlots

        %% FIXED/FLOATING FIR RESPONSE AND LINEAR-PHASE DELAY

        ResponseFrequency = linspace( ...
            0, InputSamplingFrequency / 2, 65537);
        ResponseFrequency = unique([ ...
            ResponseFrequency, Fpass, Fstop, ...
            OutputNyquistFrequency]);
        [FloatingResponse, ResponseFrequency] = freqz( ...
            FloatingCoefficients, 1, ...
            ResponseFrequency, InputSamplingFrequency);
        [FixedResponse, ~] = freqz( ...
            FixedCoefficients, 1, ...
            ResponseFrequency, InputSamplingFrequency);

        FloatingResponse_dB = 20 * log10(max( ...
            abs(FloatingResponse), realmin("double")));
        FixedResponse_dB = 20 * log10(max( ...
            abs(FixedResponse), realmin("double")));
        DigitalAngularFrequency = ...
            2 * pi * ResponseFrequency / InputSamplingFrequency;
        FixedGroupDelay_samples = -gradient( ...
            unwrap(angle(FixedResponse)), ...
            DigitalAngularFrequency);
        FixedGroupDelay_ns = ...
            FixedGroupDelay_samples / ...
            InputSamplingFrequency * 1e9;
        GroupDelayPlotMask = ...
            ResponseFrequency <= Fpass & ...
            isfinite(FixedGroupDelay_ns);

        figure( ...
            "Name", "Decimator - FIR Response and Group Delay", ...
            "Color", "w");
        ResponseLayout = tiledlayout(2, 1, ...
            "TileSpacing", "compact", ...
            "Padding", "compact");

        nexttile;
        plot( ...
            ResponseFrequency / 1e9, ...
            FloatingResponse_dB, ...
            "LineWidth", 1.2, ...
            "DisplayName", "Floating coefficients");
        hold on;
        plot( ...
            ResponseFrequency / 1e9, ...
            FixedResponse_dB, ...
            "--", ...
            "LineWidth", 1.2, ...
            "DisplayName", sprintf( ...
                "Fixed coefficients (Q%d.%d)", ...
                CoefficientFormat.IWL, CoefficientFormat.FWL));
        yline(-Apass, "g--", "Passband-ripple limit", ...
            "HandleVisibility", "off");
        yline(-Astop, "r--", "Stopband limit", ...
            "HandleVisibility", "off");
        xline(Fpass / 1e9, ":", "Fpass", ...
            "HandleVisibility", "off");
        xline(Fstop / 1e9, ":", "Fstop / target Nyquist", ...
            "HandleVisibility", "off");
        grid on;
        xlim([0, InputSamplingFrequency / 2e9]);
        ylim([-140, 2]);
        xlabel("Frequency (GHz)");
        ylabel("Magnitude (dB)");
        title("Kaiser FIR Magnitude Response");
        legend("Location", "southwest");
        hold off;

        nexttile;
        plot( ...
            ResponseFrequency(GroupDelayPlotMask) / 1e9, ...
            FixedGroupDelay_ns(GroupDelayPlotMask), ...
            "LineWidth", 1.3, ...
            "DisplayName", "Measured fixed-FIR group delay");
        hold on;
        yline( ...
            GroupDelaySeconds * 1e9, ...
            "b--", ...
            "Analytical delay", ...
            "HandleVisibility", "off");
        yline( ...
            double(Requirements.MaxGroupDelay_s) * 1e9, ...
            "r--", ...
            "Maximum delay", ...
            "HandleVisibility", "off");
        xline(DesiredFrequencies(1) / 1e9, ":", "Data 1", ...
            "HandleVisibility", "off");
        xline(DesiredFrequencies(2) / 1e9, ":", "Data 2", ...
            "HandleVisibility", "off");
        grid on;
        xlim([0, Fpass / 1e9]);
        xlabel("Frequency (GHz)");
        ylabel("Group delay (ns)");
        title("Linear-Phase Delay Across the Passband");
        legend("Location", "best");
        hold off;

        title(ResponseLayout, ...
            "Floating and Fixed-Point Decimator FIR");


        %% FOUR-BRANCH POLYPHASE COEFFICIENT BANK

        BranchRows = floor(sqrt(NumberBranches));
        BranchColumns = ceil(NumberBranches / BranchRows);
        RealBranchCoefficients = double( ...
            ReferenceDecimator.BranchCoefficients) / ...
            CoefficientScale;

        figure( ...
            "Name", "Decimator - Polyphase Branch Coefficients", ...
            "Color", "w");
        BranchLayout = tiledlayout( ...
            BranchRows, BranchColumns, ...
            "TileSpacing", "compact", ...
            "Padding", "compact");

        for BranchNumber = 1:NumberBranches
            nexttile;
            stem( ...
                0:LongestBranchLength - 1, ...
                RealBranchCoefficients(BranchNumber, :), ...
                "filled", ...
                "MarkerSize", 3, ...
                "LineWidth", 0.8);
            hold on;

            if BranchTapCounts(BranchNumber) < ...
                    LongestBranchLength
                xline( ...
                    BranchTapCounts(BranchNumber) - 0.5, ...
                    "r:", ...
                    "Zero-padded slot", ...
                    "HandleVisibility", "off");
            end

            grid on;
            xlim([-1, LongestBranchLength]);
            xlabel("Branch delay index");
            ylabel("Coefficient");
            title(sprintf( ...
                "Phase %d: %d real taps", ...
                BranchNumber - 1, ...
                BranchTapCounts(BranchNumber)));
            hold off;
        end

        title(BranchLayout, sprintf( ...
            "%d-Tap FIR Decomposed into %d Polyphase Branches", ...
            FilterLength, NumberBranches));


        %% FIXED/FLOATING RECEIVED-WAVEFORM COMPARISON

        DisplaySampleCount = min(1024, numel(OutputVoltage));
        DisplayCentreTime = ...
            P.getValue("mu") + GroupDelaySeconds;
        [~, DisplayCentre] = min(abs( ...
            OutputTime - DisplayCentreTime));
        DisplayStart = max( ...
            1, DisplayCentre - floor(DisplaySampleCount / 2));
        DisplayEnd = min( ...
            numel(OutputVoltage), ...
            DisplayStart + DisplaySampleCount - 1);
        DisplayStart = max( ...
            1, DisplayEnd - DisplaySampleCount + 1);
        DisplayIndices = DisplayStart:DisplayEnd;
        OutputError_mV = ...
            (OutputVoltage - FloatingOutput(:)) * 1e3;

        figure( ...
            "Name", "Decimator - Fixed and Floating Output", ...
            "Color", "w");
        WaveformLayout = tiledlayout(2, 1, ...
            "TileSpacing", "compact", ...
            "Padding", "compact");

        nexttile;
        plot( ...
            OutputTime(DisplayIndices) * 1e6, ...
            FloatingOutput(DisplayIndices), ...
            "LineWidth", 1.2, ...
            "DisplayName", "Floating reference");
        hold on;
        stairs( ...
            OutputTime(DisplayIndices) * 1e6, ...
            OutputVoltage(DisplayIndices), ...
            "--", ...
            "LineWidth", 1.0, ...
            "DisplayName", "Fixed-point output");
        grid on;
        xlabel("Time (microseconds)");
        ylabel("Amplitude (V)");
        title("Target-Rate Received Waveform");
        legend("Location", "best");
        hold off;

        nexttile;
        stairs( ...
            OutputTime(DisplayIndices) * 1e6, ...
            OutputError_mV(DisplayIndices), ...
            "LineWidth", 1.0, ...
            "DisplayName", "Fixed minus floating");
        yline(0, "k:", "Zero error", ...
            "HandleVisibility", "off");
        grid on;
        xlabel("Time (microseconds)");
        ylabel("Error (mV)");
        title(sprintf( ...
            "Fixed-Point Error: %.2f dB Error SNR", ...
            FixedPointErrorSNR_dB));
        legend("Location", "best");

        title(WaveformLayout, ...
            "Floating-Point Reference versus Bounded Fixed-Point MAC");


        %% RECEIVED-SIGNAL SPECTRUM AND POWER-RATIO CHANGE

        figure( ...
            "Name", "Decimator - Received-Signal Performance", ...
            "Color", "w");
        SpectrumLayout = tiledlayout(3, 1, ...
            "TileSpacing", "compact", ...
            "Padding", "compact");

        nexttile;
        plot( ...
            InputPSDFrequency / 1e9, ...
            10 * log10(max( ...
                InputPowerPSD, realmin("double"))), ...
            "LineWidth", 1.0, ...
            "DisplayName", "Before decimator (0-5 GHz)");
        hold on;
        plot( ...
            OutputPSDFrequency / 1e9, ...
            10 * log10(max( ...
                OutputPowerPSD, realmin("double"))), ...
            "--", ...
            "LineWidth", 1.0, ...
            "DisplayName", "After decimator (0-1.25 GHz)");
        xline( ...
            OutputNyquistFrequency / 1e9, ...
            ":", ...
            "Target Nyquist", ...
            "HandleVisibility", "off");
        xline( ...
            InputInterferenceAliasFrequency / 1e9, ...
            ":", ...
            "ADC-rate alias", ...
            "HandleVisibility", "off");
        xline( ...
            OutputAliasFrequency / 1e9, ...
            ":", ...
            "Target-rate alias", ...
            "HandleVisibility", "off");
        grid on;
        xlim([0, InputSamplingFrequency / 2e9]);
        xlabel("Frequency (GHz)");
        ylabel("PSD (dB V^2/Hz)");
        title("Matched-Time Welch PSD and Noise-Band Reduction");
        legend("Location", "best");
        hold off;

        nexttile;
        plot( ...
            InputComparisonFFTFrequency / 1e9, ...
            20 * log10(max( ...
                InputComparisonMagnitude, realmin("double"))), ...
            "LineWidth", 1.0, ...
            "DisplayName", "Before decimator");
        hold on;
        plot( ...
            OutputComparisonFFTFrequency / 1e9, ...
            20 * log10(max( ...
                OutputComparisonMagnitude, realmin("double"))), ...
            "--", ...
            "LineWidth", 1.0, ...
            "DisplayName", "After decimator");
        xline(DesiredFrequencies(1) / 1e9, ":", "Data 1", ...
            "HandleVisibility", "off");
        xline(DesiredFrequencies(2) / 1e9, ":", "Data 2", ...
            "HandleVisibility", "off");
        grid on;
        xlim([ ...
            min(DesiredFrequencies) - 4e6, ...
            max(DesiredFrequencies) + 4e6] / 1e9);
        xlabel("Frequency (GHz)");
        ylabel("Magnitude (dBV)");
        title("Hamming FFT: Adjacent Data-Tone Preservation");
        legend("Location", "best");
        hold off;

        nexttile;
        bar([ ...
            InputSNR_dB, OutputSNR_dB; ...
            InputSINR_dB, OutputSINR_dB]);
        yline(0, "k:", "0 dB", ...
            "HandleVisibility", "off");
        grid on;
        xticks([1, 2]);
        xticklabels({"SNR", "SINR"});
        ylabel("Power ratio (dB)");
        title(sprintf( ...
            "Full-Band Improvement: SNR %+.2f dB, SINR %+.2f dB", ...
            SNRImprovement_dB, SINRImprovement_dB));
        legend( ...
            "Before decimator", ...
            "After decimator", ...
            "Location", "best");

        title(SpectrumLayout, ...
            "Received Signal Through the Fixed-Point Decimator");


        %% END-TO-END HAMMING-FFT SPECTRAL BENCHMARK

        GeneratorSignal = double(State.InputSignal(:));
        GeneratorSamplingFrequency = double(P.getValue("Fs"));
        GeneratorInterferenceFrequency = double( ...
            State.SignalGenerator.Measurements.InterferenceFrequency_Hz);

        if isempty(GeneratorSignal) || ...
                ~isreal(GeneratorSignal) || ...
                any(~isfinite(GeneratorSignal))
            error('RunDemoDecimator:InvalidGeneratorSignal', ...
                ['State.InputSignal must contain the finite, real ', ...
                 'signal-generator output record.']);
        end

        validateattributes( ...
            GeneratorSamplingFrequency, ...
            {'numeric'}, ...
            {'scalar', 'real', 'finite', 'positive'}, ...
            mfilename, ...
            'GeneratorSamplingFrequency');
        validateattributes( ...
            GeneratorInterferenceFrequency, ...
            {'numeric'}, ...
            {'scalar', 'real', 'finite', 'nonnegative'}, ...
            mfilename, ...
            'GeneratorInterferenceFrequency');

        GeneratorSpectrum = SpectrumAnalyzer( ...
            P, GeneratorSamplingFrequency);
        [GeneratorFFTFrequency, GeneratorMagnitude] = ...
            GeneratorSpectrum.HammingFFT(GeneratorSignal);

        GeneratorMagnitude_dBV = 20 * log10(max( ...
            GeneratorMagnitude, realmin("double")));
        FinalOutputMagnitude_dBV = 20 * log10(max( ...
            OutputMagnitude, realmin("double")));

        % Use one vertical scale so the two panels form a defensible
        % end-to-end magnitude comparison rather than two independently
        % autoscaled views.
        EndToEndMaximum_dBV = max([ ...
            GeneratorMagnitude_dBV; ...
            FinalOutputMagnitude_dBV]);
        EndToEndUpperLimit_dBV = ...
            10 * ceil((EndToEndMaximum_dBV + 3) / 10);
        EndToEndLowerLimit_dBV = ...
            EndToEndUpperLimit_dBV - 120;

        figure( ...
            "Name", "End-to-End - Hamming-FFT Benchmark", ...
            "Color", "w");
        EndToEndLayout = tiledlayout(2, 1, ...
            "TileSpacing", "compact", ...
            "Padding", "compact");

        nexttile;
        plot( ...
            GeneratorFFTFrequency / 1e9, ...
            GeneratorMagnitude_dBV, ...
            "LineWidth", 1.0, ...
            "DisplayName", "Signal-generator composite");
        hold on;
        xline(0, ":", "DC", ...
            "LabelHorizontalAlignment", "left", ...
            "HandleVisibility", "off");
        xline(DesiredFrequencies(1) / 1e9, ":", "Data 1", ...
            "LabelVerticalAlignment", "bottom", ...
            "HandleVisibility", "off");
        xline(DesiredFrequencies(2) / 1e9, ":", "Data 2", ...
            "LabelVerticalAlignment", "top", ...
            "HandleVisibility", "off");
        xline( ...
            GeneratorInterferenceFrequency / 1e9, ...
            ":", ...
            "Interference", ...
            "HandleVisibility", "off");
        grid on;
        xlim([0, GeneratorSamplingFrequency / 2e9]);
        ylim([EndToEndLowerLimit_dBV, EndToEndUpperLimit_dBV]);
        xlabel("Frequency (GHz)");
        ylabel("Magnitude (dBV)");
        title(sprintf( ...
            "Signal-Generator Output: %.1f GS/s, 0-%.1f GHz", ...
            GeneratorSamplingFrequency / 1e9, ...
            GeneratorSamplingFrequency / 2e9));
        legend("Location", "best");
        hold off;

        nexttile;
        plot( ...
            OutputFFTFrequency / 1e9, ...
            FinalOutputMagnitude_dBV, ...
            "LineWidth", 1.0, ...
            "DisplayName", "Final fixed-point output");
        hold on;
        xline(DesiredFrequencies(1) / 1e9, ":", "Data 1", ...
            "LabelVerticalAlignment", "bottom", ...
            "HandleVisibility", "off");
        xline(DesiredFrequencies(2) / 1e9, ":", "Data 2", ...
            "LabelVerticalAlignment", "top", ...
            "HandleVisibility", "off");
        xline(OutputAliasFrequency / 1e9, ":", ...
            "Possible interference alias", ...
            "HandleVisibility", "off");
        grid on;
        xlim([0, OutputNyquistFrequency / 1e9]);
        ylim([EndToEndLowerLimit_dBV, EndToEndUpperLimit_dBV]);
        xlabel("Frequency (GHz)");
        ylabel("Magnitude (dBV)");
        title(sprintf( ...
            "Final Decimator Output: %.1f GS/s, 0-%.2f GHz", ...
            OutputSamplingFrequency / 1e9, ...
            OutputNyquistFrequency / 1e9));
        legend("Location", "best");
        hold off;

        title(EndToEndLayout, ...
            "End-to-End Hamming-FFT Spectral Benchmark");


        %% MATLAB FILTER ANALYZER

        FilterVisualization = FiltWinAnalyzer();
        FilterVisualization.AnalyzeFIRFilter( ...
            FixedCoefficients, ...
            InputSamplingFrequency, ...
            "Fixed-Point Kaiser Polyphase Decimator FIR");
    end


    %% ==========================================
    %% STORE DECIMATOR OUTPUT AND DESIGN DATA
    %% ==========================================

    State.Decimator = struct();
    State.Decimator.Parameters = DSPP;
    State.Decimator.Requirements = Requirements;
    State.Decimator.ShowPlotsRequested = ShowPlots;

    State.Decimator.InputCodes = InputCodes;
    State.Decimator.InputVoltage = InputVoltage;
    State.Decimator.InputFormat = InputFormat;
    State.Decimator.LSBWeight_V = LSBWeight;

    State.Decimator.OutputCodes = OutputCodes(:);
    State.Decimator.OutputCodeDomainSignal = ...
        OutputCodeDomainSignal(:);
    State.Decimator.OutputSignal_V = OutputVoltage;
    State.Decimator.ReferenceFixedSignal_V = ...
        ReferenceFixedVoltage;
    State.Decimator.FloatingReferenceSignal_V = ...
        FloatingOutput(:);
    State.Decimator.Time = OutputTime;
    State.Decimator.OutputSampleIndex = OutputSampleIndex;
    State.Decimator.OutputInputSampleIndex = ...
        OutputInputSampleIndex;
    State.Decimator.OutputSourceSampleIndex = ...
        OutputSourceSampleIndex;

    State.Decimator.InputSamplingFrequency_Hz = ...
        InputSamplingFrequency;
    State.Decimator.OutputSamplingFrequency_Hz = ...
        OutputSamplingFrequency;
    State.Decimator.OutputNyquistFrequency_Hz = ...
        OutputNyquistFrequency;
    State.Decimator.DecimationFactor = DecimationFactor;
    State.Decimator.InputFrameLength = FrameLength;
    State.Decimator.OutputFrameLength = ...
        FrameLength / DecimationFactor;
    State.Decimator.FramesProcessed = ...
        FixedFrames.FramesProcessed;
    State.Decimator.InputSampleCount = NumberInputSamples;
    State.Decimator.OutputSampleCount = numel(OutputCodes);

    State.Decimator.Filter = struct();
    State.Decimator.Filter.FloatingCoefficients = ...
        ReferenceDecimator.FilterCoefficients(:);
    State.Decimator.Filter.FixedCoefficientCodes = ...
        ReferenceDecimator.FixedFilterCoefficients(:);
    State.Decimator.Filter.FixedCoefficients = ...
        FixedCoefficients;
    State.Decimator.Filter.CoefficientScale = ...
        ReferenceDecimator.CoeffScale;
    State.Decimator.Filter.BranchCoefficientCodes = ...
        ReferenceDecimator.BranchCoefficients;
    State.Decimator.Filter.FilterLength = FilterLength;
    State.Decimator.Filter.GroupDelayInputSamples = ...
        GroupDelayInputSamples;
    State.Decimator.Filter.GroupDelay_s = GroupDelaySeconds;
    State.Decimator.Filter.BranchTapCounts = BranchTapCounts;

    State.Decimator.Filter.Response = struct();
    State.Decimator.Filter.Response.PassbandRipple_dB = ...
        PassbandRipple_dB;
    State.Decimator.Filter.Response.StopbandAttenuation_dB = ...
        StopbandAttenuation_dB;
    State.Decimator.Filter.Response.TransitionWidth_Hz = ...
        TransitionWidth_Hz;
    State.Decimator.Filter.Response.WorstStopbandFrequency_Hz = ...
        WorstStopbandFrequency_Hz;
    State.Decimator.Filter.Response.PassbandOK = ...
        ResponsePassbandOK;
    State.Decimator.Filter.Response.StopbandOK = ...
        ResponseStopbandOK;
    State.Decimator.Filter.Response.OverallOK = ...
        ResponseOverallOK;

    State.Decimator.Filter.AliasProtection = struct();
    State.Decimator.Filter.AliasProtection.OutputSampleRate_Hz = ...
        CheckedOutputRate_Hz;
    State.Decimator.Filter.AliasProtection.OutputNyquist_Hz = ...
        CheckedOutputNyquist_Hz;
    State.Decimator.Filter.AliasProtection.StopbandEdge_Hz = ...
        CheckedStopbandEdge_Hz;
    State.Decimator.Filter.AliasProtection.Attenuation_dB = ...
        AliasBandAttenuation_dB;
    State.Decimator.Filter.AliasProtection.WorstFrequency_Hz = ...
        WorstAliasFrequency_Hz;
    State.Decimator.Filter.AliasProtection.StopbandPlacementOK = ...
        StopbandPlacementOK;
    State.Decimator.Filter.AliasProtection.AttenuationOK = ...
        AliasResponseOK && AliasAttenuationRequirementOK;
    State.Decimator.Filter.AliasProtection.OverallOK = ...
        AliasProtectionOK && AliasAttenuationRequirementOK;

    State.Decimator.Filter.FixedPointComparison = struct();
    State.Decimator.Filter.FixedPointComparison.CoefficientRMSE = ...
        CoefficientRMSE;
    State.Decimator.Filter.FixedPointComparison.MaximumCoefficientError = ...
        MaximumCoefficientError;
    State.Decimator.Filter.FixedPointComparison.MaximumComplexResponseError = ...
        MaximumComplexResponseError;
    State.Decimator.Filter.FixedPointComparison.FloatingPassbandRipple_dB = ...
        FloatingPassbandRipple_dB;
    State.Decimator.Filter.FixedPointComparison.FixedPassbandRipple_dB = ...
        FixedPassbandRipple_dB;
    State.Decimator.Filter.FixedPointComparison.PassbandRippleChange_dB = ...
        PassbandRippleChange_dB;
    State.Decimator.Filter.FixedPointComparison.FloatingStopbandAttenuation_dB = ...
        FloatingStopbandAttenuation_dB;
    State.Decimator.Filter.FixedPointComparison.FixedStopbandAttenuation_dB = ...
        FixedStopbandAttenuation_dB;
    State.Decimator.Filter.FixedPointComparison.StopbandAttenuationChange_dB = ...
        StopbandAttenuationChange_dB;
    State.Decimator.Filter.FixedPointComparison.OverallOK = ...
        ComparisonOverallOK;

    State.Decimator.FixedPoint = struct();
    State.Decimator.FixedPoint.CoefficientFormat = ...
        CoefficientFormat;
    State.Decimator.FixedPoint.MACFormat = MACFormat;
    State.Decimator.FixedPoint.ReferenceMACData = ...
        ReferenceMACData;
    State.Decimator.FixedPoint.MACData = MACData;
    State.Decimator.FixedPoint.Metrics = FixedPointMetrics;

    State.Decimator.Architecture = struct();
    State.Decimator.Architecture.NumberBranches = ...
        NumberBranches;
    State.Decimator.Architecture.LongestBranchLength = ...
        LongestBranchLength;
    State.Decimator.Architecture.RectangularBranchSlots = ...
        RectangularBranchSlots;
    State.Decimator.Architecture.ImplementedMACsPerInputSample = ...
        ImplementedMACsPerInputSample;
    State.Decimator.Architecture.MACReductionPercent = ...
        MACReductionPercent;
    State.Decimator.Architecture.Metrics = ...
        ArchitectureMetrics;

    State.Decimator.FrameProcessing = struct();
    State.Decimator.FrameProcessing.Reference = ReferenceFrames;
    State.Decimator.FrameProcessing.Fixed = FixedFrames;
    State.Decimator.FrameProcessing.Floating = FloatingFrames;

    State.Decimator.TonePreservation = struct();
    State.Decimator.TonePreservation.Summary = ...
        TonePreservationSummary;
    State.Decimator.TonePreservation.TrueFrequencyResolution_Hz = ...
        TrueFrequencyResolution;
    State.Decimator.TonePreservation.FrequencyPreservationOK = ...
        ToneFrequencyPreservationOK;
    State.Decimator.TonePreservation.LevelPreservationOK = ...
        ToneLevelPreservationOK;

    State.Decimator.Aliasing = struct();
    State.Decimator.Aliasing.InputAliasFrequency_Hz = ...
        InputInterferenceAliasFrequency;
    State.Decimator.Aliasing.OutputAliasFrequency_Hz = ...
        OutputAliasFrequency;
    State.Decimator.Aliasing.InputInterferencePower_V2 = ...
        InputInterferencePower;
    State.Decimator.Aliasing.OutputAliasPower_V2 = ...
        OutputAliasPower;
    State.Decimator.Aliasing.ReceivedSuppression_dB = ...
        ReceivedAliasSuppression_dB;

    State.Decimator.PowerRatios = struct();
    State.Decimator.PowerRatios.Summary = PowerRatioSummary;
    State.Decimator.PowerRatios.InputComponentMeasurements = ...
        InputComponentMeasurements;
    State.Decimator.PowerRatios.OutputComponentMeasurements = ...
        OutputComponentMeasurements;
    State.Decimator.PowerRatios.InputBroadbandNoisePower_V2 = ...
        InputBroadbandNoisePower;
    State.Decimator.PowerRatios.OutputBroadbandNoisePower_V2 = ...
        OutputBroadbandNoisePower;
    State.Decimator.PowerRatios.InputSNR_dB = InputSNR_dB;
    State.Decimator.PowerRatios.OutputSNR_dB = OutputSNR_dB;
    State.Decimator.PowerRatios.SNRImprovement_dB = ...
        SNRImprovement_dB;
    State.Decimator.PowerRatios.InputSINR_dB = InputSINR_dB;
    State.Decimator.PowerRatios.OutputSINR_dB = OutputSINR_dB;
    State.Decimator.PowerRatios.SINRImprovement_dB = ...
        SINRImprovement_dB;
    State.Decimator.PowerRatios.InputNoiseMeasurementBandwidth_Hz = ...
        InputNoiseMeasurementBandwidth_Hz;
    State.Decimator.PowerRatios.OutputNoiseMeasurementBandwidth_Hz = ...
        OutputNoiseMeasurementBandwidth_Hz;
    State.Decimator.PowerRatios.HandoffOK = PowerRatioHandoffOK;
    State.Decimator.PowerRatios.SNRImprovementOK = ...
        SNRImprovementOK;
    State.Decimator.PowerRatios.SINRImprovementOK = ...
        SINRImprovementOK;

    State.Decimator.AnalysisRecord = struct();
    State.Decimator.AnalysisRecord.InputStartIndex = ...
        AnalysisStartIndex;
    State.Decimator.AnalysisRecord.InputEndIndex = ...
        AnalysisEndIndex;
    State.Decimator.AnalysisRecord.InputSampleCount = ...
        numel(InputAnalysisRecord);
    State.Decimator.AnalysisRecord.OutputSampleCount = ...
        numel(OutputAnalysisRecord);
    State.Decimator.AnalysisRecord.InputPSDWindowLength = ...
        InputPSDWindowLength;
    State.Decimator.AnalysisRecord.OutputPSDWindowLength = ...
        OutputPSDWindowLength;
    State.Decimator.AnalysisRecord.InputPSDOverlapLength = ...
        InputPSDOverlapLength;
    State.Decimator.AnalysisRecord.OutputPSDOverlapLength = ...
        OutputPSDOverlapLength;
    State.Decimator.AnalysisRecord.InputPSDFFTLength = ...
        InputPSDFFTLength;
    State.Decimator.AnalysisRecord.OutputPSDFFTLength = ...
        OutputPSDFFTLength;

    State.Decimator.Compliance = struct();
    State.Decimator.Compliance.EncoderHandoffOK = ...
        HandoffCodesOK && HandoffCountOK && HandoffVoltageScaleOK;
    State.Decimator.Compliance.InputRateOK = ...
        InputRateOK && EncoderRateOK;
    State.Decimator.Compliance.FrameLengthOK = FrameLengthOK;
    State.Decimator.Compliance.FrequencyPlanOK = FrequencyPlanOK;
    State.Decimator.Compliance.OutputSampleCountOK = ...
        OutputSampleCountOK;
    State.Decimator.Compliance.OutputIndexOK = OutputIndexOK;
    State.Decimator.Compliance.NoPaddingRequiredOK = ...
        NoPaddingRequiredOK;
    State.Decimator.Compliance.ReferenceAgreementOK = ...
        ReferenceAgreementOK;
    State.Decimator.Compliance.ZeroOverflowOK = ZeroOverflowOK;
    State.Decimator.Compliance.CoefficientWordLengthOK = ...
        CoefficientWordLengthOK;
    State.Decimator.Compliance.AccumulatorWordLengthOK = ...
        AccumulatorWordLengthOK;
    State.Decimator.Compliance.GroupDelayOK = GroupDelayOK;
    State.Decimator.Compliance.TypeILinearPhaseOK = ...
        TypeILinearPhaseOK;
    State.Decimator.Compliance.BranchStructureOK = ...
        BranchStructureOK;
    State.Decimator.Compliance.ResponsePassbandOK = ...
        ResponsePassbandOK && ComparisonPassbandOK;
    State.Decimator.Compliance.ResponseStopbandOK = ...
        ResponseStopbandOK && ComparisonStopbandOK;
    State.Decimator.Compliance.AliasProtectionOK = ...
        AliasProtectionOK && AliasAttenuationRequirementOK;
    State.Decimator.Compliance.FixedPointErrorSNROK = ...
        FixedPointErrorSNROK;
    State.Decimator.Compliance.MACReductionOK = MACReductionOK;
    State.Decimator.Compliance.MatchedTrueResolutionOK = ...
        MatchedTrueResolutionOK;
    State.Decimator.Compliance.ToneFrequencyPreservationOK = ...
        ToneFrequencyPreservationOK;
    State.Decimator.Compliance.ToneLevelPreservationOK = ...
        ToneLevelPreservationOK;
    State.Decimator.Compliance.PowerRatioHandoffOK = ...
        PowerRatioHandoffOK;
    State.Decimator.Compliance.SNRImprovementOK = ...
        SNRImprovementOK;
    State.Decimator.Compliance.SINRImprovementOK = ...
        SINRImprovementOK;
    State.Decimator.DesignOverallOK = OverallDesignOK;
    State.Decimator.PerformanceOverallOK = OverallPerformanceOK;
    State.Decimator.OverallOK = OverallDecimatorOK;
    State.Decimator.PerformanceAnalysisComplete = true;

    % Preserve the hardware-oriented fixed-point result as the final
    % target-rate digital stream. OutputSignal_V remains available for
    % physical-domain analysis and plotting.
    State.CurrentSignal = OutputCodes(:);
    State.Time = OutputTime;
    State.Fs = OutputSamplingFrequency;
end


function [OutputCodes, FinalMACData, Summary] = ...
        LocalProcessFixedStream( ...
        Decimator, InputCodes, FrameLength, ...
        InputFormat, CoefficientFormat, MACFormat)
%% Process one complete integer stream without padding intermediate frames.

    NumberInputSamples = numel(InputCodes);
    NumberFrames = ceil(NumberInputSamples / FrameLength);
    OutputCodes = zeros(0, 1, 'int64');
    OutputSampleIndex = zeros(0, 1);
    FinalMACData = [];
    TotalPaddingSamples = 0;

    for FrameNumber = 1:NumberFrames
        FrameStart = (FrameNumber - 1) * FrameLength + 1;
        FrameEnd = min( ...
            FrameNumber * FrameLength, NumberInputSamples);
        IsLastFrame = FrameNumber == NumberFrames;

        if isempty(MACFormat)
            [OutputFrame, FinalMACData, FrameInfo] = ...
                Decimator.ProcessFrame( ...
                    InputCodes(FrameStart:FrameEnd), ...
                    IsLastFrame, ...
                    InputFormat, ...
                    CoefficientFormat);
        else
            [OutputFrame, FinalMACData, FrameInfo] = ...
                Decimator.ProcessFrame( ...
                    InputCodes(FrameStart:FrameEnd), ...
                    IsLastFrame, ...
                    InputFormat, ...
                    CoefficientFormat, ...
                    MACFormat);
        end

        OutputCodes = [ ...
            OutputCodes; OutputFrame(:)]; %#ok<AGROW>
        OutputSampleIndex = [ ...
            OutputSampleIndex; ...
            FrameInfo.OutputSampleIndex(:)]; %#ok<AGROW>
        TotalPaddingSamples = ...
            TotalPaddingSamples + FrameInfo.NumPaddingSamples;
    end

    Summary.FramesProcessed = NumberFrames;
    Summary.TotalPaddingSamples = TotalPaddingSamples;
    Summary.OutputSampleIndex = OutputSampleIndex;
    Summary.StreamFinalized = Decimator.StreamFinalized;
end


function [OutputSignal, Summary] = ...
        LocalProcessFloatingStream( ...
        Decimator, InputSignal, FrameLength)
%% Process the matching floating-point reference using identical framing.

    NumberInputSamples = numel(InputSignal);
    NumberFrames = ceil(NumberInputSamples / FrameLength);
    OutputSignal = zeros(0, 1);
    OutputSampleIndex = zeros(0, 1);
    TotalPaddingSamples = 0;

    for FrameNumber = 1:NumberFrames
        FrameStart = (FrameNumber - 1) * FrameLength + 1;
        FrameEnd = min( ...
            FrameNumber * FrameLength, NumberInputSamples);
        IsLastFrame = FrameNumber == NumberFrames;

        [OutputFrame, FrameInfo] = ...
            Decimator.ProcessFrame( ...
                InputSignal(FrameStart:FrameEnd), ...
                IsLastFrame);

        OutputSignal = [ ...
            OutputSignal; OutputFrame(:)]; %#ok<AGROW>
        OutputSampleIndex = [ ...
            OutputSampleIndex; ...
            FrameInfo.OutputSampleIndex(:)]; %#ok<AGROW>
        TotalPaddingSamples = ...
            TotalPaddingSamples + FrameInfo.NumPaddingSamples;
    end

    Summary.FramesProcessed = NumberFrames;
    Summary.TotalPaddingSamples = TotalPaddingSamples;
    Summary.OutputSampleIndex = OutputSampleIndex;
    Summary.StreamFinalized = Decimator.StreamFinalized;
end


function BranchTapCounts = ...
        LocalBranchTapCounts(FilterLength, DecimationFactor)
%% Return the number of real prototype coefficients in each branch.

    PhaseIndex = 0:DecimationFactor - 1;
    BranchTapCounts = max( ...
        0, ...
        floor((FilterLength - 1 - PhaseIndex) / ...
        DecimationFactor) + 1);
end


function [MeasuredFrequency, PeakMagnitude] = ...
        LocalMeasureFFTPeaks( ...
        Frequency, Magnitude, TargetFrequencies, SearchHalfWidth)
%% Measure the strongest Hamming-FFT bin in each local tone-search band.

    Frequency = Frequency(:);
    Magnitude = Magnitude(:);
    TargetFrequencies = TargetFrequencies(:);

    if numel(Frequency) ~= numel(Magnitude)
        error('RunDemoDecimator:FFTLengthMismatch', ...
            'FFT frequency and magnitude vectors must have equal lengths.');
    end

    MeasuredFrequency = zeros(size(TargetFrequencies));
    PeakMagnitude = zeros(size(TargetFrequencies));

    for k = 1:numel(TargetFrequencies)
        SearchMask = abs( ...
            Frequency - TargetFrequencies(k)) <= SearchHalfWidth;

        if ~any(SearchMask)
            error('RunDemoDecimator:EmptyToneSearchBand', ...
                ['No Hamming-FFT bins lie inside a desired-tone ', ...
                 'search band.']);
        end

        CandidateIndices = find(SearchMask);
        [PeakMagnitude(k), LocalPeakIndex] = ...
            max(Magnitude(SearchMask));
        MeasuredFrequency(k) = ...
            Frequency(CandidateIndices(LocalPeakIndex));
    end
end


function AliasFrequency = LocalFoldToFirstNyquist( ...
        InputFrequency, SamplingFrequency)
%% Fold a nonnegative frequency into the real-signal first Nyquist zone.

    AliasFrequency = abs(mod( ...
        InputFrequency + SamplingFrequency / 2, ...
        SamplingFrequency) - SamplingFrequency / 2);
end


function [PSDFrequency, PowerPSD] = LocalHammingPSD( ...
        InputSignal, SamplingFrequency, ...
        WindowLength, OverlapLength, FFTLength)
%% Hamming-Welch PSD using decimator-specific matched-time lengths.

    InputSignal = InputSignal(:);

    if numel(InputSignal) < WindowLength
        error('RunDemoDecimator:PSDRecordTooShort', ...
            'The signal is shorter than its Hamming-Welch window.');
    end

    if OverlapLength >= WindowLength
        error('RunDemoDecimator:InvalidPSDOverlap', ...
            'PSD overlap must be shorter than its Welch window.');
    end

    if FFTLength < WindowLength
        error('RunDemoDecimator:InvalidPSDFFTLength', ...
            'PSD FFT length must be at least the Welch window length.');
    end

    HammingWindow = hamming(WindowLength, "periodic");
    [PowerPSD, PSDFrequency] = pwelch( ...
        InputSignal, ...
        HammingWindow, ...
        OverlapLength, ...
        FFTLength, ...
        SamplingFrequency, ...
        "onesided");
end


function Result = LocalPassFail(Condition)
%% Convert a scalar compliance decision to a readable label.

    if Condition
        Result = "PASS";
    else
        Result = "FAIL";
    end
end
