function State = RunDemoAGC(State, ShowPlots)
%% =======================================================
%% AUTOMATIC GAIN CONTROL PERFORMANCE DEMONSTRATION
%% =======================================================
% Process the actual low-SNR LPF output through the frame-based AGC and
% noise gate. Characterize regulation, ADC full-scale use, desired-tone
% preservation, and two-tone intermodulation change without introducing a
% separate gate stimulus or relying on variables in the base workspace.


    %% ==========================================
    %% VALIDATE INTERSTAGE INPUT CONTRACT
    %% ==========================================

    if nargin < 1 || nargin > 2 || ~isstruct(State)
        error('RunDemoAGC:InvalidState', ...
            ['RunDemoAGC requires a State structure input and an ', ...
             'optional logical ShowPlots input.']);
    end

    if nargin < 2 || isempty(ShowPlots)
        ShowPlots = true;
    end

    if ~islogical(ShowPlots) || ~isscalar(ShowPlots)
        error('RunDemoAGC:InvalidPlotVisibility', ...
            'ShowPlots must be a logical scalar.');
    end

    RequiredFields = [ ...
        "Parameters", ...
        "Fs", ...
        "Time", ...
        "CurrentSignal", ...
        "SignalGenerator", ...
        "LPF"];

    for k = 1:numel(RequiredFields)
        if ~isfield(State, RequiredFields(k))
            error('RunDemoAGC:MissingStateField', ...
                'State.%s is required.', RequiredFields(k));
        end
    end

    P = State.Parameters;
    Fs = State.Fs;
    Time = State.Time(:);
    InputSignal = double(State.CurrentSignal(:));

    if numel(Time) ~= numel(InputSignal)
        error('RunDemoAGC:StateLengthMismatch', ...
            'State.Time and State.CurrentSignal must have equal lengths.');
    end

    FrameLength = P.getValue("FrameLength");
    NumberSamples = numel(InputSignal);
    NumberFrames = ceil(NumberSamples / FrameLength);


    %% ==========================================
    %% FRAME-BASED AGC PROCESSING
    %% ==========================================

    GainController = AGC(P);

    OutputSignal = zeros(NumberSamples, 1);
    AGCTime = zeros(NumberSamples, 1);

    History.Gain = zeros(NumberSamples, 1);
    History.EffectiveGain = zeros(NumberSamples, 1);
    History.Envelope = zeros(NumberSamples, 1);
    History.ProjectedEnvelope = zeros(NumberSamples, 1);
    History.AGCSignal = zeros(NumberSamples, 1);
    History.GateGain = zeros(NumberSamples, 1);
    History.SampleIndex = zeros(NumberSamples, 1);

    for FrameIndex = 1:NumberFrames
        FrameStart = (FrameIndex - 1) * FrameLength + 1;
        FrameEnd = min(FrameStart + FrameLength - 1, NumberSamples);
        FrameIndices = FrameStart:FrameEnd;

        [OutputFrame, TimeFrame, FrameHistory] = ...
            GainController.GainControl(InputSignal(FrameIndices));

        OutputSignal(FrameIndices) = OutputFrame;
        AGCTime(FrameIndices) = TimeFrame;

        History.Gain(FrameIndices) = FrameHistory.Gain;
        History.EffectiveGain(FrameIndices) = ...
            FrameHistory.EffectiveGain;
        History.Envelope(FrameIndices) = FrameHistory.Envelope;
        History.ProjectedEnvelope(FrameIndices) = ...
            FrameHistory.ProjectedEnvelope;
        History.AGCSignal(FrameIndices) = FrameHistory.AGCSignal;
        History.GateGain(FrameIndices) = FrameHistory.GateGain;
        History.SampleIndex(FrameIndices) = FrameHistory.SampleIndex;
    end

    if ~isequal(AGCTime, Time)
        error('RunDemoAGC:TimeBaseMismatch', ...
            ['The AGC global frame time does not match the upstream ', ...
             'signal-chain time base.']);
    end


    %% ==========================================
    %% AGC REGULATION MEASUREMENTS
    %% ==========================================

    AGCMetrics = MeasureAGCResponse(History, P);

    MinimumRequiredOccupancy = ...
        P.getValue("MinAGCTargetOccupancy");
    MaximumReleaseTime = P.getValue("MaxAGCReleaseTime");

    TargetOccupancyOK = ...
        isfinite(AGCMetrics.TargetWindowOccupancyPercentage) && ...
        AGCMetrics.TargetWindowOccupancyPercentage >= ...
        MinimumRequiredOccupancy;

    ReleaseObserved = isfinite(AGCMetrics.MaximumReleaseTime);

    % This received record starts at minimum gain and therefore exercises
    % the gain-release path as the AGC acquires its operating level.
    ReleaseTimeOK = ...
        ~ReleaseObserved || ...
        AGCMetrics.MaximumReleaseTime <= MaximumReleaseTime;

    MinimumConfiguredGain = P.getValue("MinAGCGain");
    MaximumConfiguredGain = P.getValue("MaxAGCGain");

    GainTolerance = 10 * eps(MaximumConfiguredGain);

    GainBoundsOK = ...
        AGCMetrics.MinimumGainObserved >= ...
        MinimumConfiguredGain - GainTolerance && ...
        AGCMetrics.MaximumGainObserved <= ...
        MaximumConfiguredGain + GainTolerance;



    %% ==========================================
    %% ADC FULL-SCALE AND CLIPPING MEASUREMENTS
    %% ==========================================

    Vfs = P.getValue("Vfs");
    QuantizerPeak = abs(Vfs) / 2;

    InputPeak = max(abs(InputSignal));
    OutputPeak = max(abs(OutputSignal));

    ClippedMask = abs(OutputSignal) > QuantizerPeak;
    ClippedSampleCount = sum(ClippedMask);
    ClippingPercentage = ...
        100 * ClippedSampleCount / NumberSamples;

    MaximumClippingPercentage = ...
        P.getValue("MaxAGCClippingPercentage");

    ClippingOK = ...
        ClippingPercentage <= MaximumClippingPercentage;

    PeakFullScaleUtilizationPercentage = ...
        100 * OutputPeak / QuantizerPeak;

    if OutputPeak == 0
        PeakHeadroom_dB = Inf;
    else
        PeakHeadroom_dB = ...
            20 * log10(QuantizerPeak / OutputPeak);
    end

    FiniteOutputOK = all(isfinite(OutputSignal));


    %% ==========================================
    %% MEASURED INPUT/OUTPUT SNR AND SINR
    %% ==========================================
    % Reuse the signal-generator observation record and detected component
    % frequencies so the AGC input and output use identical estimators,
    % frequency grids, and exclusion bands.

    if ~isfield(State.SignalGenerator, "AnalysisRecord") || ...
            ~isfield(State.SignalGenerator, "Measurements") || ...
            ~isfield( ...
                State.SignalGenerator.Measurements, ...
                "DesiredFrequencies_Hz") || ...
            ~isfield( ...
                State.SignalGenerator.Measurements, ...
                "InterferenceFrequency_Hz")

        error('RunDemoAGC:MissingSignalAnalysisState', ...
            ['The signal-generator analysis record and detected ', ...
             'component frequencies are required for AGC SNR/SINR ', ...
             'measurement.']);
    end

    AnalysisStartIndex = ...
        State.SignalGenerator.AnalysisRecord.StartIndex;
    AnalysisEndIndex = ...
        State.SignalGenerator.AnalysisRecord.EndIndex;

    if ~isscalar(AnalysisStartIndex) || ...
            ~isscalar(AnalysisEndIndex) || ...
            AnalysisStartIndex < 1 || ...
            AnalysisEndIndex > NumberSamples || ...
            AnalysisStartIndex ~= fix(AnalysisStartIndex) || ...
            AnalysisEndIndex ~= fix(AnalysisEndIndex) || ...
            AnalysisEndIndex < AnalysisStartIndex

        error('RunDemoAGC:InvalidSignalAnalysisRecord', ...
            'The signal-generator analysis-record indices are invalid.');
    end

    AnalysisIndices = AnalysisStartIndex:AnalysisEndIndex;
    InputAnalysisRecord = InputSignal(AnalysisIndices);
    OutputAnalysisRecord = OutputSignal(AnalysisIndices);

    Spectrum = SpectrumAnalyzer(P, Fs);

    [PowerPSDFrequency, InputPowerPSD] = ...
        Spectrum.HammingPSD(InputAnalysisRecord);
    [OutputPowerPSDFrequency, OutputPowerPSD] = ...
        Spectrum.HammingPSD(OutputAnalysisRecord);

    if ~isequal(PowerPSDFrequency, OutputPowerPSDFrequency)
        error('RunDemoAGC:PSDGridMismatch', ...
            'Input and output Welch PSD frequency grids must match.');
    end

    PSDWindowLength = P.getValue("PSDWindowLength");
    DCGuardBandwidth = 2 * Fs / PSDWindowLength;

    DetectedDesiredFrequencies = ...
        State.SignalGenerator.Measurements.DesiredFrequencies_Hz(:);
    DetectedInterferenceFrequency = ...
        State.SignalGenerator.Measurements.InterferenceFrequency_Hz;

    if numel(DetectedDesiredFrequencies) ~= 2
        error('RunDemoAGC:InvalidDesiredFrequencies', ...
            'Exactly two detected desired frequencies are required.');
    end


    %% ==========================================
    %% TWO-TONE INTERMODULATION DISTORTION
    %% ==========================================
    % Measure the same IM2 / IM3 products before and after gain control.
    % The explicit Fs input is required because this stage still operates
    % at the 40 GS/s pre-ADC simulation rate.

    InputIMDMetrics = ...
        MeasureADCIntermodulationPerformance( ...
            InputSignal, DetectedDesiredFrequencies, P, Fs);

    OutputIMDMetrics = ...
        MeasureADCIntermodulationPerformance( ...
            OutputSignal, DetectedDesiredFrequencies, P, Fs);

    IM2Change_dB = ...
        OutputIMDMetrics.WorstIM2_dBc - ...
        InputIMDMetrics.WorstIM2_dBc;

    IM3Change_dB = ...
        OutputIMDMetrics.WorstIM3_dBc - ...
        InputIMDMetrics.WorstIM3_dBc;

    IMDComparisonSummary = table( ...
        ["Worst IM2"; "Worst IM3"], ...
        [InputIMDMetrics.WorstIM2_dBc; ...
         InputIMDMetrics.WorstIM3_dBc], ...
        [OutputIMDMetrics.WorstIM2_dBc; ...
         OutputIMDMetrics.WorstIM3_dBc], ...
        [IM2Change_dB; IM3Change_dB], ...
        'VariableNames', { ...
            'Metric', ...
            'BeforeAGC_dBc', ...
            'AfterAGC_dBc', ...
            'Change_dB'});


    PowerMeasurementNames = [ ...
        "Data Signal 1"; ...
        "Data Signal 2"; ...
        "Detected Interferer"];

    PowerMeasurementFrequencies = [ ...
        DetectedDesiredFrequencies; ...
        DetectedInterferenceFrequency];

    InputComponentMeasurements = ...
        Spectrum.MeasureComponentPowerAmplitude( ...
            InputPowerPSD, ...
            PowerPSDFrequency, ...
            PSDWindowLength, ...
            PowerMeasurementFrequencies, ...
            PowerMeasurementNames);

    OutputComponentMeasurements = ...
        Spectrum.MeasureComponentPowerAmplitude( ...
            OutputPowerPSD, ...
            PowerPSDFrequency, ...
            PSDWindowLength, ...
            PowerMeasurementFrequencies, ...
            PowerMeasurementNames);

    DesiredTonesMeasuredOK = ...
        all(OutputComponentMeasurements.ComponentPower_V2(1:2) > 0);

    DesiredBandLower = ...
        min(P.getValue("FData"), P.getValue("FData2")) - 50e6;
    DesiredBandUpper = ...
        max(P.getValue("FData"), P.getValue("FData2")) + 50e6;

    BroadbandNoiseMask = ...
        PowerPSDFrequency > DCGuardBandwidth & ...
        PowerPSDFrequency <= Fs/2 & ...
        ~(PowerPSDFrequency >= DesiredBandLower & ...
        PowerPSDFrequency <= DesiredBandUpper) & ...
        abs( ...
            PowerPSDFrequency - DetectedInterferenceFrequency) > 50e6;

    if ~any(BroadbandNoiseMask)
        error('RunDemoAGC:EmptyNoiseMeasurementBand', ...
            'No Welch PSD bins remain for broadband-noise measurement.');
    end

    InputBroadbandNoisePSD = ...
        mean(InputPowerPSD(BroadbandNoiseMask));
    OutputBroadbandNoisePSD = ...
        mean(OutputPowerPSD(BroadbandNoiseMask));

    % Retain the same one-sided equivalent-noise convention used by the
    % signal-generator and filter stages for direct comparison.
    NoiseBandwidth = Fs / 2;

    InputBroadbandNoisePower = ...
        InputBroadbandNoisePSD * NoiseBandwidth;
    OutputBroadbandNoisePower = ...
        OutputBroadbandNoisePSD * NoiseBandwidth;

    InputDesiredSignalPower = ...
        sum(InputComponentMeasurements.ComponentPower_V2(1:2));
    OutputDesiredSignalPower = ...
        sum(OutputComponentMeasurements.ComponentPower_V2(1:2));

    InputInterferencePower = ...
        InputComponentMeasurements.ComponentPower_V2(3);
    OutputInterferencePower = ...
        OutputComponentMeasurements.ComponentPower_V2(3);

    InputSNR_dB = 10 * log10( ...
        max(InputDesiredSignalPower, realmin("double")) / ...
        max(InputBroadbandNoisePower, realmin("double")));

    OutputSNR_dB = 10 * log10( ...
        max(OutputDesiredSignalPower, realmin("double")) / ...
        max(OutputBroadbandNoisePower, realmin("double")));

    InputSINR_dB = 10 * log10( ...
        max(InputDesiredSignalPower, realmin("double")) / ...
        max( ...
            InputBroadbandNoisePower + InputInterferencePower, ...
            realmin("double")));

    OutputSINR_dB = 10 * log10( ...
        max(OutputDesiredSignalPower, realmin("double")) / ...
        max( ...
            OutputBroadbandNoisePower + OutputInterferencePower, ...
            realmin("double")));

    SNRChange_dB = OutputSNR_dB - InputSNR_dB;
    SINRChange_dB = OutputSINR_dB - InputSINR_dB;

    MaximumSNRDegradation_dB = ...
        P.getValue("MaxAGCSNRDegradation");
    MaximumSINRDegradation_dB = ...
        P.getValue("MaxAGCSINRDegradation");

    SNRPreservationOK = ...
        SNRChange_dB >= -MaximumSNRDegradation_dB;
    SINRPreservationOK = ...
        SINRChange_dB >= -MaximumSINRDegradation_dB;

    PowerRatioSummary = table( ...
        ["Before AGC"; "After AGC"], ...
        [InputDesiredSignalPower; OutputDesiredSignalPower], ...
        [InputBroadbandNoisePower; OutputBroadbandNoisePower], ...
        [InputInterferencePower; OutputInterferencePower], ...
        [InputSNR_dB; OutputSNR_dB], ...
        [InputSINR_dB; OutputSINR_dB], ...
        'VariableNames', { ...
            'Observation', ...
            'DesiredSignalPower_V2', ...
            'BroadbandNoisePower_V2', ...
            'InterferencePower_V2', ...
            'SNR_dB', ...
            'SINR_dB'});


    %% ==========================================
    %% OVERALL AGC PERFORMANCE DECISION
    %% ==========================================

    OverallAGCOK = ...
        FiniteOutputOK && ...
        GainBoundsOK && ...
        TargetOccupancyOK && ...
        ClippingOK && ...
        ReleaseTimeOK && ...
        DesiredTonesMeasuredOK && ...
        SNRPreservationOK && ...
        SINRPreservationOK;


    %% ==========================================
    %% COMMAND-WINDOW PERFORMANCE SUMMARY
    %% ==========================================

    fprintf("\n");
    fprintf("===============================================================\n");
    fprintf("AUTOMATIC GAIN CONTROL PERFORMANCE SUMMARY\n");
    fprintf("===============================================================\n");

    fprintf("Design and implementation\n");
    fprintf("  Input                            : LPF output\n");
    fprintf("  Input sampling rate              : %.3f GS/s\n", Fs / 1e9);
    fprintf("  Frame length                     : %d samples\n", FrameLength);
    fprintf("  ADC full-scale range             : %.6f Vpp\n", Vfs);
    fprintf("  ADC input limits                 : %.6f to %+.6f V\n", ...
        -QuantizerPeak, QuantizerPeak);
    fprintf("  Initial gain                     : %.9f (%+.3f dB)\n", ...
        P.getValue("InitialAGCGain"), ...
        20 * log10(P.getValue("InitialAGCGain")));
    fprintf("  Configured gain range            : %.6f to %.6f ", ...
        MinimumConfiguredGain, MaximumConfiguredGain);
    fprintf("(%+.3f to %+.3f dB)\n", ...
        20 * log10(MinimumConfiguredGain), ...
        20 * log10(MaximumConfiguredGain));
    fprintf("  Envelope attack / release        : %.3f / %.3f ns\n", ...
        P.getValue("EnvAttack") * 1e9, ...
        P.getValue("EnvRelease") * 1e9);
    fprintf("  Gain attack / release constants  : %.3f / %.3f ns\n", ...
        P.getValue("GainAttack") * 1e9, ...
        P.getValue("GainRelease") * 1e9);
    fprintf("  Noise-gate threshold             : %.6f V\n", ...
        P.getValue("NoiseGateThreshold"));
    fprintf("  Processed frames                 : %d\n", ...
        GainController.FramesProcessed);

    fprintf("\nEnvelope regulation\n");
    fprintf("  Lower / upper target             : %.6f / %.6f V\n", ...
        AGCMetrics.LowerAGCLimit, AGCMetrics.UpperAGCLimit);
    fprintf("  Active samples                   : %d\n", ...
        AGCMetrics.ActiveSampleCount);
    fprintf("  Target-window occupancy          : %.6f %%\n", ...
        AGCMetrics.TargetWindowOccupancyPercentage);
    fprintf("  Required occupancy               : %.6f %%\n", ...
        MinimumRequiredOccupancy);
    fprintf("  Observed gain range              : %.9f to %.9f\n", ...
        AGCMetrics.MinimumGainObserved, ...
        AGCMetrics.MaximumGainObserved);

    if ReleaseObserved
        fprintf("  Maximum measured release time    : %.6f ns\n", ...
            AGCMetrics.MaximumReleaseTime * 1e9);
        fprintf("  Required maximum release time    : %.6f ns\n", ...
            MaximumReleaseTime * 1e9);
    else
        fprintf("  Gain release response            : NOT EXERCISED BY THIS RECORD\n");
    end

    fprintf("\nADC full-scale use\n");
    fprintf("  AGC input peak                   : %.6f V\n", InputPeak);
    fprintf("  AGC output peak                  : %.6f V\n", OutputPeak);
    fprintf("  Peak full-scale utilization      : %.6f %%\n", ...
        PeakFullScaleUtilizationPercentage);
    fprintf("  Peak headroom                    : %+.6f dB\n", ...
        PeakHeadroom_dB);
    fprintf("  Clipped samples                  : %d of %d\n", ...
        ClippedSampleCount, NumberSamples);
    fprintf("  Clipping percentage              : %.9f %%\n", ...
        ClippingPercentage);
    fprintf("  Maximum clipping percentage      : %.9f %%\n", ...
        MaximumClippingPercentage);

    fprintf("\nMeasured Data 1 / Data 2 preservation\n");
    disp(OutputComponentMeasurements(1:2, [ ...
        "Component", ...
        "MeasuredFrequency_Hz", ...
        "ComponentPower_V2", ...
        "EquivalentPeakAmplitude_V"]));

    fprintf("\nTwo-tone intermodulation comparison\n");
    disp(IMDComparisonSummary);
    fprintf( ...
        "  Positive change means the IM product became stronger after AGC.\n");

    fprintf("\nMeasured power-ratio comparison\n");
    disp(PowerRatioSummary);
    fprintf("  SNR change (after - before)      : %+.6f dB\n", ...
        SNRChange_dB);
    fprintf("  Allowed SNR degradation          : %.6f dB\n", ...
        MaximumSNRDegradation_dB);
    fprintf("  SINR change (after - before)     : %+.6f dB\n", ...
        SINRChange_dB);
    fprintf("  Allowed SINR degradation         : %.6f dB\n", ...
        MaximumSINRDegradation_dB);

    if OverallAGCOK
        fprintf("\nOverall AGC performance           : PASS\n");
    else
        fprintf("\nOverall AGC performance           : FAIL\n");
    end


    if ShowPlots

        %% ==========================================
        %% EXISTING AGC ANALYZER PLOTS
        %% ==========================================

        PerformanceAnalyzer = AGCAnalyzer(P);

        PerformanceAnalyzer.PlotGainResponse(Time, History);
        PerformanceAnalyzer.PlotEnvelopeResponse(Time, History);

        % The received record is continuously active. The noise-gate plot
        % therefore verifies open/pass behavior without claiming separate
        % opening, closing, or settled-suppression timing measurements.
        PerformanceAnalyzer.PlotNoiseGateResponse(Time, History);
        PerformanceAnalyzer.PlotSignalResponse( ...
            Time, InputSignal, OutputSignal, History);


        %% ==========================================
        %% ADC FULL-SCALE COMPLIANCE PLOT
        %% ==========================================

        figure( ...
            "Name", "AGC - ADC Full-Scale Compliance", ...
            "Color", "w");

        plot( ...
            Time * 1e6, ...
            OutputSignal, ...
            "LineWidth", 1.0, ...
            "DisplayName", "AGC output");
        hold on;

        yline(QuantizerPeak, "r--", "+ADC limit", ...
            "HandleVisibility", "off");
        yline(-QuantizerPeak, "r--", "-ADC limit", ...
            "HandleVisibility", "off");

        grid on;
        xlabel("Time (microseconds)");
        ylabel("Amplitude (V)");
        title(sprintf( ...
            "AGC Output: %.6g%% of Samples Outside Full Scale", ...
            ClippingPercentage));
        legend("Location", "best");


        %% ==========================================
        %% DATA-TONE SPECTRAL PRESERVATION
        %% ==========================================

        InputPSD_dB = ...
            10 * log10(max(InputPowerPSD, realmin("double")));
        OutputPSD_dB = ...
            10 * log10(max(OutputPowerPSD, realmin("double")));

        [FFTFrequency, InputMagnitude] = ...
            Spectrum.HammingFFT(InputSignal);
        [~, OutputMagnitude] = ...
            Spectrum.HammingFFT(OutputSignal);

        InputMagnitude_dBV = ...
            20 * log10(max(InputMagnitude, realmin("double")));
        OutputMagnitude_dBV = ...
            20 * log10(max(OutputMagnitude, realmin("double")));

        figure( ...
            "Name", "AGC - Data-Tone Spectral Preservation", ...
            "Color", "w");

        SpectrumLayout = tiledlayout(2, 1, ...
            "TileSpacing", "compact", ...
            "Padding", "compact");

        nexttile;
        plot( ...
            PowerPSDFrequency / 1e9, ...
            InputPSD_dB, ...
            "LineWidth", 1.1, ...
            "DisplayName", "Before AGC");
        hold on;
        plot( ...
            PowerPSDFrequency / 1e9, ...
            OutputPSD_dB, ...
            "--", ...
            "LineWidth", 1.1, ...
            "DisplayName", "After AGC");
        xline(P.getValue("FData") / 1e9, ":", "Data 1", ...
            "HandleVisibility", "off");
        xline(P.getValue("FData2") / 1e9, ":", "Data 2", ...
            "HandleVisibility", "off");
        grid on;
        xlim([0.95, 1.05]);
        xlabel("Frequency (GHz)");
        ylabel("PSD (dBV^2/Hz)");
        title("Welch PSD Around the Desired-Signal Band");
        legend("Location", "best");

        nexttile;
        plot( ...
            FFTFrequency / 1e9, ...
            InputMagnitude_dBV, ...
            "LineWidth", 1.1, ...
            "DisplayName", "Before AGC");
        hold on;
        plot( ...
            FFTFrequency / 1e9, ...
            OutputMagnitude_dBV, ...
            "--", ...
            "LineWidth", 1.1, ...
            "DisplayName", "After AGC");
        xline(P.getValue("FData") / 1e9, ":", "Data 1", ...
            "HandleVisibility", "off");
        xline(P.getValue("FData2") / 1e9, ":", "Data 2", ...
            "HandleVisibility", "off");
        grid on;
        xlim([0.995, 1.006]);
        xlabel("Frequency (GHz)");
        ylabel("Magnitude (dBV)");
        title("Hamming FFT: Data 1 and Data 2 After Gain Control");
        legend("Location", "best");

        title(SpectrumLayout, ...
            "Desired-Signal Preservation Through the AGC");
    end


    %% ==========================================
    %% STORE AGC STAGE OUTPUT AND MEASUREMENTS
    %% ==========================================

    State.AGC = struct();
    State.AGC.OutputSignal = OutputSignal;
    State.AGC.Time = AGCTime;
    State.AGC.History = History;
    State.AGC.Metrics = AGCMetrics;

    State.AGC.FullScale = struct();
    State.AGC.FullScale.Vfs = Vfs;
    State.AGC.FullScale.QuantizerPeak = QuantizerPeak;
    State.AGC.FullScale.InputPeak = InputPeak;
    State.AGC.FullScale.OutputPeak = OutputPeak;
    State.AGC.FullScale.PeakFullScaleUtilizationPercentage = ...
        PeakFullScaleUtilizationPercentage;
    State.AGC.FullScale.PeakHeadroom_dB = PeakHeadroom_dB;
    State.AGC.FullScale.ClippedSampleCount = ClippedSampleCount;
    State.AGC.FullScale.ClippingPercentage = ClippingPercentage;
    State.AGC.FullScale.ClippingOK = ClippingOK;

    State.AGC.Intermodulation = struct();
    State.AGC.Intermodulation.Input = InputIMDMetrics;
    State.AGC.Intermodulation.Output = OutputIMDMetrics;
    State.AGC.Intermodulation.Comparison = IMDComparisonSummary;
    State.AGC.Intermodulation.IM2Change_dB = IM2Change_dB;
    State.AGC.Intermodulation.IM3Change_dB = IM3Change_dB;

    State.AGC.PowerRatios = struct();
    State.AGC.PowerRatios.Summary = PowerRatioSummary;
    State.AGC.PowerRatios.InputComponentMeasurements = ...
        InputComponentMeasurements;
    State.AGC.PowerRatios.OutputComponentMeasurements = ...
        OutputComponentMeasurements;
    State.AGC.PowerRatios.InputBroadbandNoisePower_V2 = ...
        InputBroadbandNoisePower;
    State.AGC.PowerRatios.OutputBroadbandNoisePower_V2 = ...
        OutputBroadbandNoisePower;
    State.AGC.PowerRatios.InputSNR_dB = InputSNR_dB;
    State.AGC.PowerRatios.OutputSNR_dB = OutputSNR_dB;
    State.AGC.PowerRatios.SNRChange_dB = SNRChange_dB;
    State.AGC.PowerRatios.InputSINR_dB = InputSINR_dB;
    State.AGC.PowerRatios.OutputSINR_dB = OutputSINR_dB;
    State.AGC.PowerRatios.SINRChange_dB = SINRChange_dB;
    State.AGC.PowerRatios.SNRPreservationOK = SNRPreservationOK;
    State.AGC.PowerRatios.SINRPreservationOK = SINRPreservationOK;

    State.AGC.Compliance = struct();
    State.AGC.Compliance.FiniteOutputOK = FiniteOutputOK;
    State.AGC.Compliance.GainBoundsOK = GainBoundsOK;
    State.AGC.Compliance.TargetOccupancyOK = TargetOccupancyOK;
    State.AGC.Compliance.ReleaseObserved = ReleaseObserved;
    State.AGC.Compliance.ReleaseTimeOK = ReleaseTimeOK;
    State.AGC.Compliance.DesiredTonesMeasuredOK = ...
        DesiredTonesMeasuredOK;

    State.AGC.OverallOK = OverallAGCOK;
    State.CurrentSignal = OutputSignal;
end

