function State = RunDemoADCEncoder(State, ShowPlots)
%% =======================================================
%% OFFSET-BINARY / TWO'S-COMPLEMENT ADC ENCODER DEMO
%% =======================================================
% Encode the complete bipolar-midtread quantizer code stream in frames.
% unsigned offset binary is retained as the ADC-interface output,
% while signed two's-complement codes become the fixed-point decimator
% input. Encoding changes only representation: sample count, rate, time,
% reconstructed voltage, SNR, and SINR must remain unchanged.


    %% ==========================================
    %% VALIDATE INTERSTAGE INPUT CONTRACT
    %% ==========================================

    if nargin < 1 || nargin > 2 || ~isstruct(State)
        error('RunDemoADCEncoder:InvalidState', ...
            ['RunDemoADCEncoder requires a State structure input and ', ...
             'an optional logical ShowPlots input.']);
    end

    if nargin < 2 || isempty(ShowPlots)
        ShowPlots = true;
    end

    if ~islogical(ShowPlots) || ~isscalar(ShowPlots)
        error('RunDemoADCEncoder:InvalidPlotVisibility', ...
            'ShowPlots must be a logical scalar.');
    end

    RequiredStateFields = [ ...
        "Parameters"; ...
        "Fs"; ...
        "Time"; ...
        "CurrentSignal"; ...
        "Quantizer"; ...
        "Sampler"; ...
        "SignalGenerator"];

    for k = 1:numel(RequiredStateFields)
        if ~isfield(State, RequiredStateFields(k))
            error('RunDemoADCEncoder:MissingStateField', ...
                'State.%s is required.', RequiredStateFields(k));
        end
    end

    RequiredQuantizerFields = [ ...
        "OutputSignal"; ...
        "Time"; ...
        "Indices"; ...
        "SamplingFrequency_Hz"; ...
        "NumBits"; ...
        "NumberCodes"; ...
        "ZeroVoltCode"; ...
        "QuantizationStep_V"; ...
        "FrameLength"; ...
        "OutputSampleCount"; ...
        "PowerRatios"; ...
        "AnalysisRecord"];

    for k = 1:numel(RequiredQuantizerFields)
        if ~isfield(State.Quantizer, RequiredQuantizerFields(k))
            error('RunDemoADCEncoder:MissingQuantizerField', ...
                'State.Quantizer.%s is required.', ...
                RequiredQuantizerFields(k));
        end
    end

    RequiredPowerRatioFields = [ ...
        "OutputComponentMeasurements"; ...
        "OutputBroadbandNoisePower_V2"; ...
        "OutputSNR_dB"; ...
        "OutputSINR_dB"];

    for k = 1:numel(RequiredPowerRatioFields)
        if ~isfield( ...
                State.Quantizer.PowerRatios, ...
                RequiredPowerRatioFields(k))
            error('RunDemoADCEncoder:MissingPowerRatioField', ...
                'State.Quantizer.PowerRatios.%s is required.', ...
                RequiredPowerRatioFields(k));
        end
    end

    RequiredAnalysisFields = [ ...
        "InputStartIndex"; ...
        "InputEndIndex"; ...
        "OutputSampleCount"; ...
        "PSDWindowLength"; ...
        "PSDOverlapLength"; ...
        "PSDFFTLength"];

    for k = 1:numel(RequiredAnalysisFields)
        if ~isfield( ...
                State.Quantizer.AnalysisRecord, ...
                RequiredAnalysisFields(k))
            error('RunDemoADCEncoder:MissingAnalysisField', ...
                'State.Quantizer.AnalysisRecord.%s is required.', ...
                RequiredAnalysisFields(k));
        end
    end

    if ~isfield(State.Sampler, "SampleIndex") || ...
            ~isfield(State.Sampler, "Aliasing") || ...
            ~isfield( ...
                State.Sampler.Aliasing, ...
                "PredictedAliasFrequency_Hz")
        error('RunDemoADCEncoder:MissingSamplerState', ...
            ['The sampler index and predicted interference-alias ', ...
             'frequency are required.']);
    end

    if ~isfield(State.SignalGenerator, "Measurements") || ...
            ~isfield( ...
                State.SignalGenerator.Measurements, ...
                "DesiredFrequencies_Hz")
        error('RunDemoADCEncoder:MissingSignalMeasurements', ...
            'The two receiver-measured data frequencies are required.');
    end

    P = State.Parameters;
    SamplingFrequency = double(State.Fs);
    Time = double(State.Time(:));
    QuantizedVoltage = double(State.CurrentSignal(:));
    QuantizerVoltage = double(State.Quantizer.OutputSignal(:));
    QuantizerTime = double(State.Quantizer.Time(:));
    InputIndices = State.Quantizer.Indices(:);
    SampleIndex = double(State.Sampler.SampleIndex(:));

    validateattributes( ...
        SamplingFrequency, ...
        {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, ...
        mfilename, ...
        'State.Fs');

    if isempty(QuantizedVoltage)
        error('RunDemoADCEncoder:EmptyInput', ...
            'The ADC encoder requires a nonempty quantizer output.');
    end

    if ~isreal(QuantizedVoltage) || ...
            any(~isfinite(QuantizedVoltage))
        error('RunDemoADCEncoder:InvalidInputSignal', ...
            'State.CurrentSignal must be finite and real valued.');
    end

    NumberSamples = numel(QuantizedVoltage);

    if numel(Time) ~= NumberSamples || ...
            numel(QuantizerVoltage) ~= NumberSamples || ...
            numel(QuantizerTime) ~= NumberSamples || ...
            numel(InputIndices) ~= NumberSamples || ...
            numel(SampleIndex) ~= NumberSamples
        error('RunDemoADCEncoder:StateLengthMismatch', ...
            ['The quantizer voltage, time, code-index, and sampler-index ', ...
             'records must have equal lengths.']);
    end

    HandoffSignalOK = isequal(QuantizedVoltage, QuantizerVoltage);
    HandoffTimeOK = isequal(Time, QuantizerTime);
    HandoffCountOK = ...
        NumberSamples == double(State.Quantizer.OutputSampleCount);

    if ~HandoffSignalOK || ~HandoffTimeOK || ~HandoffCountOK
        error('RunDemoADCEncoder:QuantizerHandoffMismatch', ...
            ['State.CurrentSignal and State.Time must be the complete ', ...
             'output record produced by RunDemoQuantizer.']);
    end

    QuantizerSamplingFrequency = double( ...
        State.Quantizer.SamplingFrequency_Hz);
    RateTolerance = max( ...
        1e-3, 32 * eps(QuantizerSamplingFrequency));
    InputRateOK = abs( ...
        SamplingFrequency - QuantizerSamplingFrequency) <= ...
        RateTolerance;

    if ~InputRateOK
        error('RunDemoADCEncoder:QuantizerRateMismatch', ...
            ['State.Fs must match the sampling frequency reported by ', ...
             'RunDemoQuantizer.']);
    end


    %% ==========================================
    %% ENCODER DESIGN AND FRAME CONFIGURATION
    %% ==========================================

    NumBits = double(State.Quantizer.NumBits);
    ConfiguredNumBits = double(P.getValue("NumBits"));
    NumberCodes = double(State.Quantizer.NumberCodes);
    HalfScale = double(State.Quantizer.ZeroVoltCode);
    LSBWeight = double(State.Quantizer.QuantizationStep_V);
    FrameLength = double(State.Quantizer.FrameLength);

    validateattributes( ...
        NumBits, ...
        {'numeric'}, ...
        {'scalar', 'integer', 'finite', '>=', 2}, ...
        mfilename, ...
        'State.Quantizer.NumBits');
    validateattributes( ...
        FrameLength, ...
        {'numeric'}, ...
        {'scalar', 'integer', 'finite', 'positive'}, ...
        mfilename, ...
        'State.Quantizer.FrameLength');
    validateattributes( ...
        LSBWeight, ...
        {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, ...
        mfilename, ...
        'State.Quantizer.QuantizationStep_V');

    if NumBits ~= ConfiguredNumBits || ...
            NumberCodes ~= 2^NumBits || ...
            HalfScale ~= 2^(NumBits - 1)
        error('RunDemoADCEncoder:InconsistentQuantizerMetadata', ...
            ['The quantizer bit depth, code count, and zero-volt code ', ...
             'must match the design configuration.']);
    end

    % The currently approved high-speed design is explicitly 8 bit.
    if NumBits ~= 8
        error('RunDemoADCEncoder:UnsupportedDemoResolution', ...
            ['RunDemoADCEncoder is configured for the approved 8-bit ', ...
             'ADC encoder specification.']);
    end

    NumberFrames = ceil(NumberSamples / FrameLength);
    Encoder = ADCEncoder(P);

    OffsetBinary = zeros(NumberSamples, 1, 'uint8');
    TwosComplement = zeros(NumberSamples, 1, 'int8');
    InputFormat = struct();
    FrameFormatOK = true;
    FramesProcessed = 0;

    for FrameNumber = 1:NumberFrames
        FrameStart = (FrameNumber - 1) * FrameLength + 1;
        FrameEnd = min(FrameNumber * FrameLength, NumberSamples);
        FrameIndices = FrameStart:FrameEnd;

        [OffsetFrame, TwosFrame, CurrentInputFormat] = ...
            Encoder.Encode(InputIndices(FrameIndices));

        OffsetBinary(FrameIndices) = OffsetFrame;
        TwosComplement(FrameIndices) = TwosFrame;

        if FrameNumber == 1
            InputFormat = CurrentInputFormat;
        else
            FrameFormatOK = FrameFormatOK && ...
                isequal(CurrentInputFormat, InputFormat);
        end

        FramesProcessed = FramesProcessed + 1;
    end


    %% ==========================================
    %% EXACT CODE-MAPPING AND VOLTAGE RECOVERY
    %% ==========================================

    ExpectedOffsetBinary = uint8(InputIndices);
    ExpectedTwosComplement = int8( ...
        int16(InputIndices) - int16(HalfScale));
    RoundTripOffsetBinary = uint8( ...
        int16(TwosComplement) + int16(HalfScale));

    OffsetTypeOK = isa(OffsetBinary, 'uint8');
    TwosTypeOK = isa(TwosComplement, 'int8');
    OffsetMappingOK = isequal( ...
        OffsetBinary, ExpectedOffsetBinary);
    TwosMappingOK = isequal( ...
        TwosComplement, ExpectedTwosComplement);
    RoundTripMappingOK = isequal( ...
        RoundTripOffsetBinary, OffsetBinary);

    OffsetMappingErrorCount = nnz( ...
        OffsetBinary ~= ExpectedOffsetBinary);
    TwosMappingErrorCount = nnz( ...
        TwosComplement ~= ExpectedTwosComplement);
    RoundTripErrorCount = nnz( ...
        RoundTripOffsetBinary ~= OffsetBinary);

    DecodedOffsetVoltage = ...
        (double(OffsetBinary) - HalfScale) * LSBWeight;
    DecodedTwosVoltage = ...
        double(TwosComplement) * LSBWeight;

    OffsetVoltageError = ...
        DecodedOffsetVoltage - QuantizedVoltage;
    TwosVoltageError = ...
        DecodedTwosVoltage - QuantizedVoltage;

    MaximumOffsetVoltageError = max(abs(OffsetVoltageError));
    MaximumTwosVoltageError = max(abs(TwosVoltageError));
    VoltageTolerance = max( ...
        1e-15, ...
        32 * eps(max(1, max(abs(QuantizedVoltage)))));

    OffsetVoltageRecoveryOK = ...
        MaximumOffsetVoltageError <= VoltageTolerance;
    TwosVoltageRecoveryOK = ...
        MaximumTwosVoltageError <= VoltageTolerance;

    InputFormatOK = ...
        isstruct(InputFormat) && ...
        isfield(InputFormat, "WL") && ...
        isfield(InputFormat, "IWL") && ...
        isfield(InputFormat, "FWL") && ...
        InputFormat.WL == NumBits && ...
        InputFormat.IWL == NumBits && ...
        InputFormat.FWL == 0;

    OutputSampleCountOK = ...
        numel(OffsetBinary) == NumberSamples && ...
        numel(TwosComplement) == NumberSamples;
    OutputTimeOK = numel(Time) == NumberSamples;
    OutputRateOK = InputRateOK;


    %% ==========================================
    %% REPRESENTATIVE BIT-MAPPING TABLE
    %% ==========================================
    % Binary strings are created only for this small display table. The
    % complete signal path remains a compact numeric integer stream.

    RepresentativeIndices = [0; 64; 127; 128; 129; 192; 255];

    [RepresentativeOffset, RepresentativeTwos] = ...
        Encoder.Encode(RepresentativeIndices);
    [RepresentativeOffsetBits, RepresentativeTwosBits] = ...
        Encoder.Binary( ...
            RepresentativeOffset, RepresentativeTwos);

    RepresentativeDecodedVoltage = ...
        double(RepresentativeTwos) * LSBWeight;

    MappingSummary = table( ...
        double(RepresentativeOffset), ...
        string(cellstr(RepresentativeOffsetBits)), ...
        double(RepresentativeTwos), ...
        string(cellstr(RepresentativeTwosBits)), ...
        RepresentativeDecodedVoltage, ...
        'VariableNames', { ...
            'OffsetBinaryCode_uint8', ...
            'OffsetBinaryBits', ...
            'TwosComplementCode_int8', ...
            'TwosComplementBits', ...
            'DecodedVoltage_V'});


    %% ==========================================
    %% MATCHED-RECORD SNR / SINR PRESERVATION
    %% ==========================================
    % Reuse the exact analysis interval and Welch configuration established
    % by the quantizer. The encoder output is decoded with its LSB weight
    % before power measurement so both sides are compared in volts.

    AnalysisStartIndex = double( ...
        State.Quantizer.AnalysisRecord.InputStartIndex);
    AnalysisEndIndex = double( ...
        State.Quantizer.AnalysisRecord.InputEndIndex);
    PSDWindowLength = double( ...
        State.Quantizer.AnalysisRecord.PSDWindowLength);
    PSDOverlapLength = double( ...
        State.Quantizer.AnalysisRecord.PSDOverlapLength);
    PSDFFTLength = double( ...
        State.Quantizer.AnalysisRecord.PSDFFTLength);

    AnalysisMask = ...
        SampleIndex >= AnalysisStartIndex - 1 & ...
        SampleIndex <= AnalysisEndIndex - 1;

    if nnz(AnalysisMask) ~= double( ...
            State.Quantizer.AnalysisRecord.OutputSampleCount)
        error('RunDemoADCEncoder:AnalysisRecordMismatch', ...
            ['The encoder analysis record must match the physical-time ', ...
             'record used by RunDemoQuantizer.']);
    end

    DecodedAnalysisRecord = DecodedTwosVoltage(AnalysisMask);

    [PSDFrequency, OutputPowerPSD] = ...
        LocalHammingPSD( ...
            DecodedAnalysisRecord, ...
            SamplingFrequency, ...
            PSDWindowLength, ...
            PSDOverlapLength, ...
            PSDFFTLength);

    DesiredFrequencies = double( ...
        State.SignalGenerator.Measurements.DesiredFrequencies_Hz(:));
    AliasFrequency = double( ...
        State.Sampler.Aliasing.PredictedAliasFrequency_Hz);

    if numel(DesiredFrequencies) ~= 2 || ...
            any(~isfinite(DesiredFrequencies)) || ...
            ~isscalar(AliasFrequency) || ...
            ~isfinite(AliasFrequency)
        error('RunDemoADCEncoder:InvalidMeasuredFrequencies', ...
            ['Exactly two finite desired frequencies and one finite ', ...
             'alias frequency are required.']);
    end

    ComponentFrequencies = [ ...
        DesiredFrequencies; ...
        AliasFrequency];
    ComponentNames = [ ...
        "Data Signal 1"; ...
        "Data Signal 2"; ...
        "Predicted Interference Alias"];

    Spectrum = SpectrumAnalyzer(P, SamplingFrequency);
    OutputComponentMeasurements = ...
        Spectrum.MeasureComponentPowerAmplitude( ...
            OutputPowerPSD, ...
            PSDFrequency, ...
            PSDWindowLength, ...
            ComponentFrequencies, ...
            ComponentNames);

    InputComponentMeasurements = ...
        State.Quantizer.PowerRatios.OutputComponentMeasurements;

    RequiredComponentVariables = { ...
        'Component', ...
        'MeasuredFrequency_Hz', ...
        'ComponentPower_V2', ...
        'EquivalentPeakAmplitude_V'};

    if ~istable(InputComponentMeasurements) || ...
            height(InputComponentMeasurements) < 3 || ...
            any(~ismember( ...
                RequiredComponentVariables, ...
                InputComponentMeasurements.Properties.VariableNames))
        error('RunDemoADCEncoder:InvalidInputPowerMeasurements', ...
            ['The quantizer output component-power table must contain ', ...
             'Data 1, Data 2, and the interference alias.']);
    end

    DesiredComponentRows = 1:2;
    ToneFrequencyChange_Hz = ...
        OutputComponentMeasurements.MeasuredFrequency_Hz( ...
        DesiredComponentRows) - ...
        InputComponentMeasurements.MeasuredFrequency_Hz( ...
        DesiredComponentRows);
    TonePowerChange_dB = 10 * log10( ...
        max( ...
        OutputComponentMeasurements.ComponentPower_V2( ...
        DesiredComponentRows), realmin("double")) ./ ...
        max( ...
        InputComponentMeasurements.ComponentPower_V2( ...
        DesiredComponentRows), realmin("double")));

    ToneMeasurementsPreservedOK = ...
        isequal( ...
        InputComponentMeasurements.MeasuredFrequency_Hz( ...
        DesiredComponentRows), ...
        OutputComponentMeasurements.MeasuredFrequency_Hz( ...
        DesiredComponentRows)) && ...
        isequal( ...
        InputComponentMeasurements.ComponentPower_V2( ...
        DesiredComponentRows), ...
        OutputComponentMeasurements.ComponentPower_V2( ...
        DesiredComponentRows)) && ...
        isequal( ...
        InputComponentMeasurements.EquivalentPeakAmplitude_V( ...
        DesiredComponentRows), ...
        OutputComponentMeasurements.EquivalentPeakAmplitude_V( ...
        DesiredComponentRows));

    TonePreservationSummary = table( ...
        string(InputComponentMeasurements.Component( ...
        DesiredComponentRows)), ...
        InputComponentMeasurements.MeasuredFrequency_Hz( ...
        DesiredComponentRows), ...
        OutputComponentMeasurements.MeasuredFrequency_Hz( ...
        DesiredComponentRows), ...
        ToneFrequencyChange_Hz, ...
        InputComponentMeasurements.ComponentPower_V2( ...
        DesiredComponentRows), ...
        OutputComponentMeasurements.ComponentPower_V2( ...
        DesiredComponentRows), ...
        TonePowerChange_dB, ...
        'VariableNames', { ...
            'Component', ...
            'BeforeEncoderFrequency_Hz', ...
            'AfterEncoderFrequency_Hz', ...
            'FrequencyChange_Hz', ...
            'BeforeEncoderPower_V2', ...
            'AfterEncoderPower_V2', ...
            'PowerChange_dB'});

    PSDSpacing = PSDFrequency(2) - PSDFrequency(1);
    DesiredBandLower = min(DesiredFrequencies) - 50e6;
    DesiredBandUpper = max(DesiredFrequencies) + 50e6;
    AliasGuardHalfWidth = 50e6;
    DCGuardBandwidth = ...
        2 * SamplingFrequency / PSDWindowLength;

    BroadbandNoiseMask = ...
        PSDFrequency > DCGuardBandwidth & ...
        ~(PSDFrequency >= DesiredBandLower & ...
        PSDFrequency <= DesiredBandUpper) & ...
        abs(PSDFrequency - AliasFrequency) > ...
        AliasGuardHalfWidth;

    if ~any(BroadbandNoiseMask)
        error('RunDemoADCEncoder:EmptyNoiseMeasurementBand', ...
            'No ADC-band PSD bins remain for noise measurement.');
    end

    InputBroadbandNoisePower = double( ...
        State.Quantizer.PowerRatios.OutputBroadbandNoisePower_V2);
    OutputBroadbandNoisePower = sum( ...
        OutputPowerPSD(BroadbandNoiseMask)) * PSDSpacing;

    InputDesiredSignalPower = sum( ...
        InputComponentMeasurements.ComponentPower_V2(1:2));
    OutputDesiredSignalPower = sum( ...
        OutputComponentMeasurements.ComponentPower_V2(1:2));

    InputInterferencePower = ...
        InputComponentMeasurements.ComponentPower_V2(3);
    OutputInterferencePower = ...
        OutputComponentMeasurements.ComponentPower_V2(3);

    InputSNR_dB = 10 * log10( ...
        max(InputDesiredSignalPower, realmin("double")) / ...
        max(InputBroadbandNoisePower, realmin("double")));
    OutputSNR_dB = 10 * log10( ...
        max(OutputDesiredSignalPower, realmin("double")) / ...
        max(OutputBroadbandNoisePower, realmin("double")));

    InputSINR_dB = 10 * log10( ...
        max(InputDesiredSignalPower, realmin("double")) / ...
        max( ...
            InputBroadbandNoisePower + InputInterferencePower, ...
            realmin("double")));
    OutputSINR_dB = 10 * log10( ...
        max(OutputDesiredSignalPower, realmin("double")) / ...
        max( ...
            OutputBroadbandNoisePower + OutputInterferencePower, ...
            realmin("double")));

    SNRChange_dB = OutputSNR_dB - InputSNR_dB;
    SINRChange_dB = OutputSINR_dB - InputSINR_dB;
    MetricScale = max( ...
        1, ...
        max(abs([ ...
            InputSNR_dB, OutputSNR_dB, ...
            InputSINR_dB, OutputSINR_dB])));
    MetricEqualityTolerance_dB = max( ...
        1e-12, 128 * eps(MetricScale));

    PowerRatioHandoffOK = ...
        abs(InputSNR_dB - double( ...
        State.Quantizer.PowerRatios.OutputSNR_dB)) <= ...
        MetricEqualityTolerance_dB && ...
        abs(InputSINR_dB - double( ...
        State.Quantizer.PowerRatios.OutputSINR_dB)) <= ...
        MetricEqualityTolerance_dB;
    SNRPreservationOK = ...
        abs(SNRChange_dB) <= MetricEqualityTolerance_dB;
    SINRPreservationOK = ...
        abs(SINRChange_dB) <= MetricEqualityTolerance_dB;

    PowerRatioSummary = table( ...
        ["ADC Encoder Input (V)"; ...
         "Decoded Two's-Complement Output (V)"], ...
        [InputDesiredSignalPower; OutputDesiredSignalPower], ...
        [InputBroadbandNoisePower; OutputBroadbandNoisePower], ...
        [InputInterferencePower; OutputInterferencePower], ...
        [InputSNR_dB; OutputSNR_dB], ...
        [InputSINR_dB; OutputSINR_dB], ...
        'VariableNames', { ...
            'Observation', ...
            'DesiredSignalPower_V2', ...
            'CommonBandNoisePower_V2', ...
            'InterferenceAliasPower_V2', ...
            'SNR_dB', ...
            'SINR_dB'});


    %% ==========================================
    %% TWO-TONE INTERMODULATION PRESERVATION
    %% ==========================================
    % Compare the quantized-voltage input against the voltage reconstructed
    % from the signed two's-complement stream. Encoding is representational,
    % so these measurements should remain unchanged.

    InputIMDMetrics = ...
        MeasureADCIntermodulationPerformance( ...
            QuantizedVoltage, ...
            DesiredFrequencies, ...
            P, ...
            SamplingFrequency);

    OutputIMDMetrics = ...
        MeasureADCIntermodulationPerformance( ...
            DecodedTwosVoltage, ...
            DesiredFrequencies, ...
            P, ...
            SamplingFrequency);

    IM2Change_dB = ...
        OutputIMDMetrics.WorstIM2_dBc - ...
        InputIMDMetrics.WorstIM2_dBc;

    IM3Change_dB = ...
        OutputIMDMetrics.WorstIM3_dBc - ...
        InputIMDMetrics.WorstIM3_dBc;

    IMDComparisonSummary = table( ...
        ["Worst IM2"; "Worst IM3"], ...
        [InputIMDMetrics.WorstIM2_dBc; ...
         InputIMDMetrics.WorstIM3_dBc], ...
        [OutputIMDMetrics.WorstIM2_dBc; ...
         OutputIMDMetrics.WorstIM3_dBc], ...
        [IM2Change_dB; IM3Change_dB], ...
        'VariableNames', { ...
            'Metric', ...
            'BeforeEncoder_dBc', ...
            'AfterEncoder_dBc', ...
            'Change_dB'});
    %% ==========================================
    %% OVERALL ADC ENCODER PERFORMANCE DECISION
    %% ==========================================

    OverallEncoderOK = ...
        HandoffSignalOK && ...
        HandoffTimeOK && ...
        HandoffCountOK && ...
        InputRateOK && ...
        OutputRateOK && ...
        OutputSampleCountOK && ...
        OutputTimeOK && ...
        OffsetTypeOK && ...
        TwosTypeOK && ...
        OffsetMappingOK && ...
        TwosMappingOK && ...
        RoundTripMappingOK && ...
        OffsetVoltageRecoveryOK && ...
        TwosVoltageRecoveryOK && ...
        InputFormatOK && ...
        FrameFormatOK && ...
        ToneMeasurementsPreservedOK && ...
        PowerRatioHandoffOK && ...
        SNRPreservationOK && ...
        SINRPreservationOK;


    %% ==========================================
    %% COMMAND-WINDOW PERFORMANCE SUMMARY
    %% ==========================================

    fprintf("\n");
    fprintf("===============================================================\n");
    fprintf("ADC ENCODER PERFORMANCE SUMMARY\n");
    fprintf("===============================================================\n");

    fprintf("Design and data-path mapping\n");
    fprintf("  Input                            : Quantizer code indices\n");
    fprintf("  Sampling frequency              : %.6f GS/s\n", ...
        SamplingFrequency / 1e9);
    fprintf("  Frame length / frames processed : %d / %d\n", ...
        FrameLength, FramesProcessed);
    fprintf("  ADC word length                 : %d bits\n", NumBits);
    fprintf("  LSB weight                      : %.7f mV/code\n", ...
        LSBWeight * 1e3);
    fprintf("  Offset-binary output            : uint8, 0 to 255\n");
    fprintf("  Two's-complement output         : int8, -128 to +127\n");
    fprintf("  Fixed-point decimator input     : Two's-complement output\n");
    fprintf("  Fixed-point format              : WL=%d, IWL=%d, FWL=%d\n", ...
        InputFormat.WL, InputFormat.IWL, InputFormat.FWL);
    fprintf("  Samples added / dropped         : 0 / 0\n");

    fprintf("\nRepresentative code mapping\n");
    disp(MappingSummary);

    fprintf("Exact full-record mapping\n");
    fprintf("  Offset-binary mapping errors    : %d\n", ...
        OffsetMappingErrorCount);
    fprintf("  Two's-complement mapping errors : %d\n", ...
        TwosMappingErrorCount);
    fprintf("  Round-trip mapping errors       : %d\n", ...
        RoundTripErrorCount);
    fprintf("  Max offset-binary decode error  : %.9e V\n", ...
        MaximumOffsetVoltageError);
    fprintf("  Max two's-complement decode error: %.9e V\n", ...
        MaximumTwosVoltageError);

    fprintf("\nMeasured Data 1 / Data 2 preservation\n");
    disp(TonePreservationSummary);

    fprintf("\nTwo-tone intermodulation comparison\n");
    disp(IMDComparisonSummary);
    fprintf( ...
        "  Positive change means the IM product became stronger after encoding.\n");

    fprintf("\nADC encoder power-ratio comparison\n");
    disp(PowerRatioSummary);
    fprintf("  SNR change (after - before)     : %+.12f dB\n", ...
        SNRChange_dB);
    fprintf("  SINR change (after - before)    : %+.12f dB\n", ...
        SINRChange_dB);

    fprintf("\nADC encoder compliance\n");
    fprintf("  Quantizer handoff               : %s\n", ...
        LocalPassFail( ...
        HandoffSignalOK && HandoffTimeOK && HandoffCountOK));
    fprintf("  Rate / sample-count preservation: %s\n", ...
        LocalPassFail(OutputRateOK && OutputSampleCountOK));
    fprintf("  offset-binary mapping   : %s\n", ...
        LocalPassFail(OffsetTypeOK && OffsetMappingOK));
    fprintf("  Two's-complement mapping        : %s\n", ...
        LocalPassFail(TwosTypeOK && TwosMappingOK));
    fprintf("  Exact code round trip           : %s\n", ...
        LocalPassFail(RoundTripMappingOK));
    fprintf("  Exact voltage reconstruction    : %s\n", ...
        LocalPassFail( ...
        OffsetVoltageRecoveryOK && TwosVoltageRecoveryOK));
    fprintf("  Fixed-point input format        : %s\n", ...
        LocalPassFail(InputFormatOK && FrameFormatOK));
    fprintf("  Data 1 / Data 2 preservation    : %s\n", ...
        LocalPassFail(ToneMeasurementsPreservedOK));
    fprintf("  Quantizer power-ratio handoff   : %s\n", ...
        LocalPassFail(PowerRatioHandoffOK));
    fprintf("  SNR preservation                : %s\n", ...
        LocalPassFail(SNRPreservationOK));
    fprintf("  SINR preservation               : %s\n", ...
        LocalPassFail(SINRPreservationOK));

    if OverallEncoderOK
        fprintf("\nOverall ADC encoder performance   : PASS\n");
    else
        fprintf("\nOverall ADC encoder performance   : FAIL\n");
    end


    %% ==========================================
    %% APPROVED ADC ENCODER FIGURE
    %% ==========================================

    if ShowPlots
        PerformanceAnalyzer = ADCPerformanceAnalyzer(P);

        DisplaySampleCount = min(512, NumberSamples);
        [~, DisplayCentre] = min(abs( ...
            Time - P.getValue("mu")));
        DisplayStart = max( ...
            1, DisplayCentre - floor(DisplaySampleCount / 2));
        DisplayEnd = min( ...
            NumberSamples, DisplayStart + DisplaySampleCount - 1);
        DisplayStart = max( ...
            1, DisplayEnd - DisplaySampleCount + 1);
        DisplayIndices = DisplayStart:DisplayEnd;

        PerformanceAnalyzer.PlotEncoderResponse( ...
            Time(DisplayIndices), ...
            OffsetBinary(DisplayIndices), ...
            TwosComplement(DisplayIndices), ...
            QuantizedVoltage(DisplayIndices), ...
            DecodedTwosVoltage(DisplayIndices));
    end


    %% ==========================================
    %% STORE ADC ENCODER OUTPUT AND MEASUREMENTS
    %% ==========================================

    State.ADCEncoder = struct();
    State.ADCEncoder.OffsetBinary = OffsetBinary;
    State.ADCEncoder.TwosComplement = TwosComplement;
    State.ADCEncoder.DecodedVoltage = DecodedTwosVoltage;
    State.ADCEncoder.InputFormat = InputFormat;
    State.ADCEncoder.LSBWeight_V = LSBWeight;
    State.ADCEncoder.OffsetBinaryRange = [0, NumberCodes - 1];
    State.ADCEncoder.TwosComplementRange = ...
        [-HalfScale, HalfScale - 1];
    State.ADCEncoder.DownstreamRepresentation = ...
        "Signed two's complement";
    State.ADCEncoder.BitOrder = "MSB first";
    State.ADCEncoder.SamplingFrequency_Hz = SamplingFrequency;
    State.ADCEncoder.FrameLength = FrameLength;
    State.ADCEncoder.FramesProcessed = FramesProcessed;
    State.ADCEncoder.InputSampleCount = NumberSamples;
    State.ADCEncoder.OutputSampleCount = numel(TwosComplement);
    State.ADCEncoder.MappingSummary = MappingSummary;

    State.ADCEncoder.TonePreservation = struct();
    State.ADCEncoder.TonePreservation.Summary = ...
        TonePreservationSummary;
    State.ADCEncoder.TonePreservation.MeasurementsPreservedOK = ...
        ToneMeasurementsPreservedOK;

    State.ADCEncoder.Mapping = struct();
    State.ADCEncoder.Mapping.OffsetMappingErrorCount = ...
        OffsetMappingErrorCount;
    State.ADCEncoder.Mapping.TwosMappingErrorCount = ...
        TwosMappingErrorCount;
    State.ADCEncoder.Mapping.RoundTripErrorCount = ...
        RoundTripErrorCount;
    State.ADCEncoder.Mapping.MaximumOffsetVoltageError_V = ...
        MaximumOffsetVoltageError;
    State.ADCEncoder.Mapping.MaximumTwosVoltageError_V = ...
        MaximumTwosVoltageError;

    State.ADCEncoder.Intermodulation = struct();
    State.ADCEncoder.Intermodulation.Input = InputIMDMetrics;
    State.ADCEncoder.Intermodulation.Output = OutputIMDMetrics;
    State.ADCEncoder.Intermodulation.Comparison = IMDComparisonSummary;
    State.ADCEncoder.Intermodulation.IM2Change_dB = IM2Change_dB;
    State.ADCEncoder.Intermodulation.IM3Change_dB = IM3Change_dB;

    State.ADCEncoder.PowerRatios = struct();
    State.ADCEncoder.PowerRatios.Summary = PowerRatioSummary;
    State.ADCEncoder.PowerRatios.InputComponentMeasurements = ...
        InputComponentMeasurements;
    State.ADCEncoder.PowerRatios.OutputComponentMeasurements = ...
        OutputComponentMeasurements;
    State.ADCEncoder.PowerRatios.InputBroadbandNoisePower_V2 = ...
        InputBroadbandNoisePower;
    State.ADCEncoder.PowerRatios.OutputBroadbandNoisePower_V2 = ...
        OutputBroadbandNoisePower;
    State.ADCEncoder.PowerRatios.InputSNR_dB = InputSNR_dB;
    State.ADCEncoder.PowerRatios.OutputSNR_dB = OutputSNR_dB;
    State.ADCEncoder.PowerRatios.SNRChange_dB = SNRChange_dB;
    State.ADCEncoder.PowerRatios.InputSINR_dB = InputSINR_dB;
    State.ADCEncoder.PowerRatios.OutputSINR_dB = OutputSINR_dB;
    State.ADCEncoder.PowerRatios.SINRChange_dB = SINRChange_dB;
    State.ADCEncoder.PowerRatios.SNRPreservationOK = ...
        SNRPreservationOK;
    State.ADCEncoder.PowerRatios.SINRPreservationOK = ...
        SINRPreservationOK;

    State.ADCEncoder.AnalysisRecord = struct();
    State.ADCEncoder.AnalysisRecord.InputStartIndex = ...
        AnalysisStartIndex;
    State.ADCEncoder.AnalysisRecord.InputEndIndex = ...
        AnalysisEndIndex;
    State.ADCEncoder.AnalysisRecord.OutputSampleCount = ...
        numel(DecodedAnalysisRecord);
    State.ADCEncoder.AnalysisRecord.PSDWindowLength = ...
        PSDWindowLength;
    State.ADCEncoder.AnalysisRecord.PSDOverlapLength = ...
        PSDOverlapLength;
    State.ADCEncoder.AnalysisRecord.PSDFFTLength = ...
        PSDFFTLength;

    State.ADCEncoder.Compliance = struct();
    State.ADCEncoder.Compliance.QuantizerHandoffOK = ...
        HandoffSignalOK && HandoffTimeOK && HandoffCountOK;
    State.ADCEncoder.Compliance.OutputRateOK = OutputRateOK;
    State.ADCEncoder.Compliance.SampleCountOK = ...
        OutputSampleCountOK;
    State.ADCEncoder.Compliance.OffsetTypeOK = OffsetTypeOK;
    State.ADCEncoder.Compliance.TwosTypeOK = TwosTypeOK;
    State.ADCEncoder.Compliance.OffsetMappingOK = OffsetMappingOK;
    State.ADCEncoder.Compliance.TwosMappingOK = TwosMappingOK;
    State.ADCEncoder.Compliance.RoundTripMappingOK = ...
        RoundTripMappingOK;
    State.ADCEncoder.Compliance.OffsetVoltageRecoveryOK = ...
        OffsetVoltageRecoveryOK;
    State.ADCEncoder.Compliance.TwosVoltageRecoveryOK = ...
        TwosVoltageRecoveryOK;
    State.ADCEncoder.Compliance.InputFormatOK = InputFormatOK;
    State.ADCEncoder.Compliance.FrameFormatOK = FrameFormatOK;
    State.ADCEncoder.Compliance.ToneMeasurementsPreservedOK = ...
        ToneMeasurementsPreservedOK;
    State.ADCEncoder.Compliance.PowerRatioHandoffOK = ...
        PowerRatioHandoffOK;
    State.ADCEncoder.Compliance.SNRPreservationOK = ...
        SNRPreservationOK;
    State.ADCEncoder.Compliance.SINRPreservationOK = ...
        SINRPreservationOK;
    State.ADCEncoder.OverallOK = OverallEncoderOK;

    % The signed integer stream is the fixed-point decimator input.
    State.CurrentSignal = TwosComplement;
    State.Time = Time;
    State.Fs = SamplingFrequency;
end


function [PSDFrequency, PowerPSD] = LocalHammingPSD( ...
        InputSignal, SamplingFrequency, ...
        WindowLength, OverlapLength, FFTLength)
%% Hamming-Welch PSD using the established ADC-rate analysis lengths.

    InputSignal = InputSignal(:);

    if numel(InputSignal) < WindowLength
        error('RunDemoADCEncoder:PSDRecordTooShort', ...
            'The signal is shorter than the Hamming-Welch window.');
    end

    if OverlapLength >= WindowLength
        error('RunDemoADCEncoder:InvalidPSDOverlap', ...
            'PSDOverlapLength must be less than PSDWindowLength.');
    end

    if FFTLength < WindowLength
        error('RunDemoADCEncoder:InvalidPSDFFTLength', ...
            'PSDFFTLength must be at least PSDWindowLength.');
    end

    HammingWindow = hamming(WindowLength, "periodic");

    [PowerPSD, PSDFrequency] = pwelch( ...
        InputSignal, ...
        HammingWindow, ...
        OverlapLength, ...
        FFTLength, ...
        SamplingFrequency, ...
        "onesided");
end


function Result = LocalPassFail(Condition)
%% Convert a scalar compliance decision to a readable label.

    if Condition
        Result = "PASS";
    else
        Result = "FAIL";
    end
end
