function State = RunDemoHPF(State, ShowPlots)
%% =======================================================
%% DC Attenuation HIGH-PASS FILTER DEMONSTRATION
%% =======================================================
% Process the received composite signal through the frame-based HPF,
% verify the approved design requirements, and pass the filtered signal to
% the next approved stage through State.CurrentSignal.


    %% ==========================================
    %% VALIDATE INTERSTAGE INPUT CONTRACT
    %% ==========================================

    if nargin < 1 || nargin > 2 || ~isstruct(State)
        error('RunDemoHPF:InvalidState', ...
            ['RunDemoHPF requires a State structure input and an ', ...
             'optional logical ShowPlots input.']);
    end

    if nargin < 2 || isempty(ShowPlots)
        ShowPlots = true;
    end

    if ~islogical(ShowPlots) || ~isscalar(ShowPlots)
        error('RunDemoHPF:InvalidPlotVisibility', ...
            'ShowPlots must be a logical scalar.');
    end

    RequiredFields = [ ...
        "Parameters", ...
        "Fs", ...
        "Time", ...
        "CurrentSignal"];

    for k = 1:numel(RequiredFields)
        if ~isfield(State, RequiredFields(k))
            error('RunDemoHPF:MissingStateField', ...
                'State.%s is required.', RequiredFields(k));
        end
    end

    P = State.Parameters;
    Fs = State.Fs;
    Time = State.Time(:);
    InputSignal = double(State.CurrentSignal(:));

    if numel(Time) ~= numel(InputSignal)
        error('RunDemoHPF:StateLengthMismatch', ...
            'State.Time and State.CurrentSignal must have equal lengths.');
    end

    FrameLength = P.getValue("FrameLength");
    NumberSamples = numel(InputSignal);
    NumberFrames = ceil(NumberSamples / FrameLength);


    %% ==========================================
    %% FRAME-BASED HIGH-PASS FILTER PROCESSING
    %% ==========================================

    Filter = ADCFilter(P);
    HPFOutputSignal = zeros(NumberSamples, 1);

    for FrameIndex = 1:NumberFrames
        FrameStart = (FrameIndex - 1) * FrameLength + 1;
        FrameEnd = min(FrameStart + FrameLength - 1, NumberSamples);
        FrameIndices = FrameStart:FrameEnd;

        HPFOutputSignal(FrameIndices) = ...
            Filter.ProcessHPFFrame(InputSignal(FrameIndices));
    end

    % Retrieve the exact initialized design used by ProcessHPFFrame().
    HPFSOS = Filter.HPFSOS;
    HPFGain = Filter.HPFGain;


    %% ==========================================
    %% FILTER-ORDER AND RESPONSE VERIFICATION
    %% ==========================================

    [MinimumOrder, MinimumCutoffHz, TransitionWidthHz, ...
        ConfiguredOrder, OrderOK, RollOff_dBPerOctave, ...
        RollOff_dBPerDecade] = ...
        FindButterworthOrder(P, "HPF");

    [PassbandOK, StopbandOK, ResponseOverallOK, ...
        PassbandRipple_dB, WorstPassbandLoss_dB, ...
        StopbandAttenuation_dB, MeasuredTransitionWidthHz, ...
        WorstStopbandFrequencyHz] = ...
        CheckADCFilterResponse(P, "HPF", 131072);


    %% ==========================================
    %% DC REJECTION, SETTLING, AND STABILITY
    %% ==========================================

    DCRemovalMetrics = MeasureDCRemovalResponse( ...
        InputSignal, ...
        HPFOutputSignal, ...
        HPFSOS, ...
        HPFGain, ...
        P);


    %% ==========================================
    %% DESIRED-TONE PRESERVATION
    %% ==========================================

    DesiredFrequencies = [ ...
        P.getValue("FData"); ...
        P.getValue("FData2")];

    [DesiredResponse, ~] = ...
        freqz(HPFSOS, DesiredFrequencies, Fs);

    DesiredResponse = HPFGain .* DesiredResponse;

    DesiredToneLoss_dB = ...
        -20 * log10(max(abs(DesiredResponse), realmin("double")));

    MaximumDesiredToneLoss_dB = ...
        P.getValue("MaxDesiredToneLossHPF");

    DesiredToneLossOK = ...
        all(DesiredToneLoss_dB <= MaximumDesiredToneLoss_dB);

    DifferentialToneLoss_dB = ...
        abs(DesiredToneLoss_dB(1) - DesiredToneLoss_dB(2));


    %% ==========================================
    %% MEASURED INPUT/OUTPUT SNR AND SINR
    %% ==========================================
    % Use the exact observation record and detected component frequencies
    % established by the signal-generator stage. Both sides of the HPF are
    % therefore measured with the same Welch estimator, frequency grid,
    % component integration width, and exclusion masks.

    if ~isfield(State, "SignalGenerator") || ...
            ~isfield(State.SignalGenerator, "AnalysisRecord") || ...
            ~isfield(State.SignalGenerator, "Measurements") || ...
            ~isfield( ...
                State.SignalGenerator.Measurements, ...
                "DesiredFrequencies_Hz") || ...
            ~isfield( ...
                State.SignalGenerator.Measurements, ...
                "InterferenceFrequency_Hz")

        error('RunDemoHPF:MissingSignalAnalysisState', ...
            ['The signal-generator analysis record and detected ', ...
             'component frequencies are required for HPF SNR/SINR ', ...
             'measurement.']);
    end

    AnalysisStartIndex = ...
        State.SignalGenerator.AnalysisRecord.StartIndex;
    AnalysisEndIndex = ...
        State.SignalGenerator.AnalysisRecord.EndIndex;

    if ~isscalar(AnalysisStartIndex) || ...
            ~isscalar(AnalysisEndIndex) || ...
            AnalysisStartIndex < 1 || ...
            AnalysisEndIndex > NumberSamples || ...
            AnalysisStartIndex ~= fix(AnalysisStartIndex) || ...
            AnalysisEndIndex ~= fix(AnalysisEndIndex) || ...
            AnalysisEndIndex < AnalysisStartIndex

        error('RunDemoHPF:InvalidSignalAnalysisRecord', ...
            'The signal-generator analysis-record indices are invalid.');
    end

    AnalysisIndices = AnalysisStartIndex:AnalysisEndIndex;
    InputAnalysisRecord = InputSignal(AnalysisIndices);
    OutputAnalysisRecord = HPFOutputSignal(AnalysisIndices);

    Spectrum = SpectrumAnalyzer(P, Fs);

    [PowerPSDFrequency, InputPowerPSD] = ...
        Spectrum.HammingPSD(InputAnalysisRecord);
    [OutputPowerPSDFrequency, OutputPowerPSD] = ...
        Spectrum.HammingPSD(OutputAnalysisRecord);

    if ~isequal(PowerPSDFrequency, OutputPowerPSDFrequency)
        error('RunDemoHPF:PSDGridMismatch', ...
            'Input and output Welch PSD frequency grids must match.');
    end

    PSDWindowLength = P.getValue("PSDWindowLength");
    DCGuardBandwidth = 2 * Fs / PSDWindowLength;

    DetectedDesiredFrequencies = ...
        State.SignalGenerator.Measurements.DesiredFrequencies_Hz(:);
    DetectedInterferenceFrequency = ...
        State.SignalGenerator.Measurements.InterferenceFrequency_Hz;

    if numel(DetectedDesiredFrequencies) ~= 2
        error('RunDemoHPF:InvalidDesiredFrequencies', ...
            'Exactly two detected desired frequencies are required.');
    end

    PowerMeasurementNames = [ ...
        "Data Signal 1"; ...
        "Data Signal 2"; ...
        "Detected Interferer"];

    PowerMeasurementFrequencies = [ ...
        DetectedDesiredFrequencies; ...
        DetectedInterferenceFrequency];

    InputComponentMeasurements = ...
        Spectrum.MeasureComponentPowerAmplitude( ...
            InputPowerPSD, ...
            PowerPSDFrequency, ...
            PSDWindowLength, ...
            PowerMeasurementFrequencies, ...
            PowerMeasurementNames);

    OutputComponentMeasurements = ...
        Spectrum.MeasureComponentPowerAmplitude( ...
            OutputPowerPSD, ...
            PowerPSDFrequency, ...
            PSDWindowLength, ...
            PowerMeasurementFrequencies, ...
            PowerMeasurementNames);

    DesiredBandLower = min(DesiredFrequencies) - 50e6;
    DesiredBandUpper = max(DesiredFrequencies) + 50e6;

    BroadbandNoiseMask = ...
        PowerPSDFrequency > DCGuardBandwidth & ...
        PowerPSDFrequency <= Fs/2 & ...
        ~(PowerPSDFrequency >= DesiredBandLower & ...
        PowerPSDFrequency <= DesiredBandUpper) & ...
        abs( ...
            PowerPSDFrequency - DetectedInterferenceFrequency) > 50e6;

    if ~any(BroadbandNoiseMask)
        error('RunDemoHPF:EmptyNoiseMeasurementBand', ...
            'No Welch PSD bins remain for broadband-noise measurement.');
    end

    InputBroadbandNoisePSD = ...
        mean(InputPowerPSD(BroadbandNoiseMask));
    OutputBroadbandNoisePSD = ...
        mean(OutputPowerPSD(BroadbandNoiseMask));

    % Retain the signal-generator stage's one-sided equivalent-noise
    % convention so the reported input value and every downstream value
    % remain directly comparable across the complete Nyquist bandwidth.
    NoiseBandwidth = Fs / 2;

    InputBroadbandNoisePower = ...
        InputBroadbandNoisePSD * NoiseBandwidth;
    OutputBroadbandNoisePower = ...
        OutputBroadbandNoisePSD * NoiseBandwidth;

    InputDesiredSignalPower = ...
        sum(InputComponentMeasurements.ComponentPower_V2(1:2));
    OutputDesiredSignalPower = ...
        sum(OutputComponentMeasurements.ComponentPower_V2(1:2));

    InputInterferencePower = ...
        InputComponentMeasurements.ComponentPower_V2(3);
    OutputInterferencePower = ...
        OutputComponentMeasurements.ComponentPower_V2(3);

    InputSNR_dB = 10 * log10( ...
        InputDesiredSignalPower / ...
        max(InputBroadbandNoisePower, realmin("double")));

    OutputSNR_dB = 10 * log10( ...
        OutputDesiredSignalPower / ...
        max(OutputBroadbandNoisePower, realmin("double")));

    InputSINR_dB = 10 * log10( ...
        InputDesiredSignalPower / ...
        max( ...
            InputBroadbandNoisePower + InputInterferencePower, ...
            realmin("double")));

    OutputSINR_dB = 10 * log10( ...
        OutputDesiredSignalPower / ...
        max( ...
            OutputBroadbandNoisePower + OutputInterferencePower, ...
            realmin("double")));

    SNRChange_dB = OutputSNR_dB - InputSNR_dB;
    SINRChange_dB = OutputSINR_dB - InputSINR_dB;

    PowerRatioSummary = table( ...
        ["Before HPF"; "After HPF"], ...
        [InputDesiredSignalPower; OutputDesiredSignalPower], ...
        [InputBroadbandNoisePower; OutputBroadbandNoisePower], ...
        [InputInterferencePower; OutputInterferencePower], ...
        [InputSNR_dB; OutputSNR_dB], ...
        [InputSINR_dB; OutputSINR_dB], ...
        'VariableNames', { ...
            'Observation', ...
            'DesiredSignalPower_V2', ...
            'BroadbandNoisePower_V2', ...
            'InterferencePower_V2', ...
            'SNR_dB', ...
            'SINR_dB'});


    %% ==========================================
    %% TWO-TONE INTERMODULATION COMPARISON
    %% ==========================================
    % Characterize the same IM2 / IM3 product locations before and after
    % the linear HPF using the actual 40-GS/s stage sampling frequency.

    InputIMDMetrics = ...
        MeasureADCIntermodulationPerformance( ...
            InputSignal, DetectedDesiredFrequencies, P, Fs);

    OutputIMDMetrics = ...
        MeasureADCIntermodulationPerformance( ...
            HPFOutputSignal, DetectedDesiredFrequencies, P, Fs);

    IM2Change_dB = ...
        OutputIMDMetrics.WorstIM2_dBc - ...
        InputIMDMetrics.WorstIM2_dBc;

    IM3Change_dB = ...
        OutputIMDMetrics.WorstIM3_dBc - ...
        InputIMDMetrics.WorstIM3_dBc;

    IMDComparisonSummary = table( ...
        ["Worst IM2"; "Worst IM3"], ...
        [InputIMDMetrics.WorstIM2_dBc; ...
         InputIMDMetrics.WorstIM3_dBc], ...
        [OutputIMDMetrics.WorstIM2_dBc; ...
         OutputIMDMetrics.WorstIM3_dBc], ...
        [IM2Change_dB; IM3Change_dB], ...
        'VariableNames', { ...
            'Metric', ...
            'BeforeHPF_dBc', ...
            'AfterHPF_dBc', ...
            'Change_dB'});
    %% ==========================================
    %% OVERALL HPF PERFORMANCE DECISION
    %% ==========================================

    OverallHPFOK = ...
        OrderOK && ...
        ResponseOverallOK && ...
        DCRemovalMetrics.OverallOK && ...
        DesiredToneLossOK;


    %% ==========================================
    %% COMMAND-WINDOW PERFORMANCE SUMMARY
    %% ==========================================

    fprintf("\n");
    fprintf("===============================================================\n");
    fprintf("DC Attenuation HIGH-PASS FILTER PERFORMANCE SUMMARY\n");
    fprintf("===============================================================\n");

    fprintf("Design and implementation\n");
    fprintf("  Butterworth order               : %d\n", ...
        ConfiguredOrder);
    fprintf("  Minimum required order          : %d\n", ...
        MinimumOrder);
    fprintf("  Configured cutoff               : %.6f MHz\n", ...
        P.getValue("FcHigh") / 1e6);
    fprintf("  Minimum-order cutoff            : %.6f MHz\n", ...
        MinimumCutoffHz / 1e6);
    fprintf("  SOS sections                    : %d\n", ...
        size(HPFSOS, 1));
    fprintf("  Processed frames                : %d\n", ...
        NumberFrames);
    fprintf("  Roll-off                        : %.3f dB/octave\n", ...
        RollOff_dBPerOctave);
    fprintf("  Roll-off                        : %.3f dB/decade\n", ...
        RollOff_dBPerDecade);

    fprintf("\nFrequency-response compliance\n");
    fprintf("  Transition width                : %.3f MHz\n", ...
        MeasuredTransitionWidthHz / 1e6);
    fprintf("  Passband loss                   : %.6f dB\n", ...
        WorstPassbandLoss_dB);
    fprintf("  Passband ripple                 : %.6f dB\n", ...
        PassbandRipple_dB);
    fprintf("  Stopband attenuation            : %.6f dB\n", ...
        StopbandAttenuation_dB);
    fprintf("  Worst stopband frequency        : %.6f MHz\n", ...
        WorstStopbandFrequencyHz / 1e6);

    fprintf("\nReceived-waveform DC Attenuation\n");
    fprintf("  Measured input DC               : %.6f V\n", ...
        DCRemovalMetrics.InputDC_V);
    fprintf("  Measured output DC              : %.6e V\n", ...
        DCRemovalMetrics.OutputDC_V);
    fprintf("  Measured DC rejection           : %.3f dB\n", ...
        DCRemovalMetrics.DCRejection_dB);
    fprintf("  Required DC rejection           : %.3f dB\n", ...
        DCRemovalMetrics.RequiredDCRejection_dB);
    fprintf("  Maximum residual DC             : %.6e V\n", ...
        DCRemovalMetrics.MaximumResidualDC_V);

    fprintf("\nTransient and stability\n");
    fprintf("  1%% settling time                : %.6f ns\n", ...
        DCRemovalMetrics.SettlingTime_s * 1e9);
    fprintf("  Required settling time          : %.6f ns\n", ...
        DCRemovalMetrics.RequiredSettlingTime_s * 1e9);
    fprintf("  Maximum pole radius             : %.9f\n", ...
        DCRemovalMetrics.MaximumPoleRadius);

    fprintf("\nDesired-tone preservation\n");
    fprintf("  Data Signal 1 loss              : %.9f dB\n", ...
        DesiredToneLoss_dB(1));
    fprintf("  Data Signal 2 loss              : %.9f dB\n", ...
        DesiredToneLoss_dB(2));
    fprintf("  Differential tone loss          : %.9f dB\n", ...
        DifferentialToneLoss_dB);
    fprintf("  Maximum permitted loss          : %.6f dB\n", ...
        MaximumDesiredToneLoss_dB);

    fprintf("\nTwo-tone intermodulation comparison\n");
    disp(IMDComparisonSummary);
    fprintf( ...
        "  Positive change means the IM product became stronger after the HPF.\n");

    fprintf("\nMeasured power-ratio comparison\n");
    disp(PowerRatioSummary);
    fprintf("  SNR change (after - before)     : %+.3f dB\n", ...
        SNRChange_dB);
    fprintf("  SINR change (after - before)    : %+.3f dB\n", ...
        SINRChange_dB);

    if OverallHPFOK
        fprintf("\nOverall HPF performance           : PASS\n");
    else
        fprintf("\nOverall HPF performance           : FAIL\n");
    end


    if ShowPlots

    %% ==========================================
    %% STATIC MAGNITUDE-RESPONSE PLOT
    %% ==========================================

    Fstop = P.getValue("FstopHPF");
    Fpass = P.getValue("FpassHPF");
    Astop = P.getValue("AstopHPF");
    Apass = P.getValue("ApassHPF");
    FcHigh = P.getValue("FcHigh");

    ResponsePlotMaximumHz = 1.2e9;
    ResponseFrequency = linspace(0, ResponsePlotMaximumHz, 65537);
    ResponseFrequency = unique([ ...
        ResponseFrequency, ...
        Fstop, ...
        FcHigh, ...
        Fpass, ...
        DesiredFrequencies.']);

    [FrequencyResponse, ResponseFrequency] = ...
        freqz(HPFSOS, ResponseFrequency, Fs);

    FrequencyResponse = HPFGain .* FrequencyResponse;
    MagnitudeResponse_dB = ...
        20 * log10(max(abs(FrequencyResponse), realmin("double")));

    figure( ...
        "Name", "DC Attenuation HPF - Magnitude Response", ...
        "Color", "w");

    plot( ...
        ResponseFrequency / 1e9, ...
        MagnitudeResponse_dB, ...
        "LineWidth", 1.5, ...
        "DisplayName", "Realized HPF response");
    hold on;

    plot( ...
        [0, Fstop] / 1e9, ...
        [-Astop, -Astop], ...
        "r--", ...
        "LineWidth", 1.3, ...
        "DisplayName", "Stopband limit");

    plot( ...
        [Fpass, ResponsePlotMaximumHz] / 1e9, ...
        [-Apass, -Apass], ...
        "g--", ...
        "LineWidth", 1.3, ...
        "DisplayName", "Passband-loss limit");

   xline( ...
    Fstop / 1e9, ...
    ":", ...
    "Fstop", ...
    "HandleVisibility", "off");

   xline( ...
    FcHigh / 1e9, ...
    ":", ...
    "FcHigh", ...
    "HandleVisibility", "off");

    xline( ...
    Fpass / 1e9, ...
    ":", ...
    "Fpass", ...
    "HandleVisibility", "off");

    grid on;
    xlim([0, ResponsePlotMaximumHz / 1e9]);
    ylim([-100, 2]);
    xlabel("Frequency (GHz)");
    ylabel("Magnitude (dB)");
    title(sprintf( ...
        "Order-%d Butterworth DC Attenuation HPF", ...
        ConfiguredOrder));
    legend("Location", "southeast");


    %% ==========================================
    %% NORMALIZED DC-STEP SETTLING PLOT
    %% ==========================================

    StepPlotMaximum_s = ...
        2 * DCRemovalMetrics.RequiredSettlingTime_s;

    StepPlotMask = ...
        DCRemovalMetrics.StepTime_s <= StepPlotMaximum_s;

    figure( ...
        "Name", "DC Attenuation HPF - Step Settling", ...
        "Color", "w");

    plot( ...
        DCRemovalMetrics.StepTime_s(StepPlotMask) * 1e6, ...
        DCRemovalMetrics.StepResponse(StepPlotMask), ...
        "LineWidth", 1.5, ...
        "DisplayName", "Unit-DC step response");
    hold on;

    yline( ...
        DCRemovalMetrics.SettlingTolerance, ...
        "r--", ...
        "+1% tolerance");
    yline( ...
        -DCRemovalMetrics.SettlingTolerance, ...
        "r--", ...
        "-1% tolerance");

    if isfinite(DCRemovalMetrics.SettlingTime_s)
        xline( ...
            DCRemovalMetrics.SettlingTime_s * 1e6, ...
            "b--", ...
            "Measured settling");
    end

    xline( ...
        DCRemovalMetrics.RequiredSettlingTime_s * 1e6, ...
        "k:", ...
        sprintf( ...
            "%.3g microseconds requirement", ...
            DCRemovalMetrics.RequiredSettlingTime_s * 1e6));

    grid on;
    xlim([0, StepPlotMaximum_s * 1e6]);
    xlabel("Time (microseconds)");
    ylabel("Normalized amplitude");
    title("HPF Rejection of an Applied DC Step");


    %% ==========================================
    %% RECEIVED-SIGNAL SPECTRAL COMPARISON
    %% ==========================================

    InputPSD_dB = ...
        10 * log10(max(InputPowerPSD, realmin("double")));
    OutputPSD_dB = ...
        10 * log10(max(OutputPowerPSD, realmin("double")));

    [FFTFrequency, InputMagnitude] = ...
        Spectrum.HammingFFT(InputSignal);
    [~, OutputMagnitude] = ...
        Spectrum.HammingFFT(HPFOutputSignal);

    InputMagnitude_dBV = ...
        20 * log10(max(InputMagnitude, realmin("double")));
    OutputMagnitude_dBV = ...
        20 * log10(max(OutputMagnitude, realmin("double")));

    figure( ...
        "Name", "DC Attenuation HPF - Received-Signal Spectrum", ...
        "Color", "w");

    SpectrumLayout = tiledlayout(2, 1, ...
        "TileSpacing", "compact", ...
        "Padding", "compact");

    nexttile;
    plot( ...
        PowerPSDFrequency / 1e9, ...
        InputPSD_dB, ...
        "LineWidth", 1.1, ...
        "DisplayName", "Before HPF");
    hold on;
    plot( ...
        PowerPSDFrequency / 1e9, ...
        OutputPSD_dB, ...
        "LineStyle", "--", ...
        "LineWidth", 1.1, ...
        "DisplayName", "After HPF");
    xline(Fstop / 1e9, ":", "Fstop");
    xline(Fpass / 1e9, ":", "Fpass");
    grid on;
    xlim([0, 0.8]);
    xlabel("Frequency (GHz)");
    ylabel("PSD (dBV^2/Hz)");
    title("Welch PSD: Common Analysis Record Before and After HPF");
    legend("Location", "best");

    nexttile;
    plot( ...
        FFTFrequency / 1e9, ...
        InputMagnitude_dBV, ...
        "LineWidth", 1.1, ...
        "DisplayName", "Before HPF");
    hold on;
    plot( ...
        FFTFrequency / 1e9, ...
        OutputMagnitude_dBV, ...
        "LineStyle", "--", ...
        "LineWidth", 1.1, ...
        "DisplayName", "After HPF");
    xline(DesiredFrequencies(1) / 1e9, ":", "Data 1");
    xline(DesiredFrequencies(2) / 1e9, ":", "Data 2");
    grid on;
    xlim([0.995, 1.006]);
    xlabel("Frequency (GHz)");
    ylabel("Magnitude (dBV)");
    title("Hamming FFT: Desired-Tone Preservation and Overlap");
    legend("Location", "best");

    title(SpectrumLayout, ...
        "Received Signal Before and After DC Attenuation");


    %% ==========================================
    %% MATLAB FILTER ANALYZER
    %% ==========================================

    FilterVisualization = FiltWinAnalyzer();
    FilterVisualization.AnalyzeSOSFilter( ...
        HPFSOS, ...
        HPFGain, ...
        Fs, ...
        "DC Attenuation Butterworth HPF");
    end


    %% ==========================================
    %% STORE HPF STAGE OUTPUT AND MEASUREMENTS
    %% ==========================================

    State.HPF = struct();
    State.HPF.OutputSignal = HPFOutputSignal;
    State.HPF.SOS = HPFSOS;
    State.HPF.Gain = HPFGain;

    State.HPF.Design = struct();
    State.HPF.Design.MinimumOrder = MinimumOrder;
    State.HPF.Design.ConfiguredOrder = ConfiguredOrder;
    State.HPF.Design.MinimumCutoffHz = MinimumCutoffHz;
    State.HPF.Design.ConfiguredCutoffHz = P.getValue("FcHigh");
    State.HPF.Design.TransitionWidthHz = TransitionWidthHz;
    State.HPF.Design.RollOff_dBPerOctave = RollOff_dBPerOctave;
    State.HPF.Design.RollOff_dBPerDecade = RollOff_dBPerDecade;
    State.HPF.Design.OrderOK = OrderOK;

    State.HPF.Response = struct();
    State.HPF.Response.PassbandRipple_dB = PassbandRipple_dB;
    State.HPF.Response.WorstPassbandLoss_dB = ...
        WorstPassbandLoss_dB;
    State.HPF.Response.StopbandAttenuation_dB = ...
        StopbandAttenuation_dB;
    State.HPF.Response.WorstStopbandFrequencyHz = ...
        WorstStopbandFrequencyHz;
    State.HPF.Response.PassbandOK = PassbandOK;
    State.HPF.Response.StopbandOK = StopbandOK;
    State.HPF.Response.OverallOK = ResponseOverallOK;

    State.HPF.DCRemoval = DCRemovalMetrics;
    State.HPF.DesiredFrequencies_Hz = DesiredFrequencies;
    State.HPF.DesiredToneLoss_dB = DesiredToneLoss_dB;
    State.HPF.DifferentialToneLoss_dB = DifferentialToneLoss_dB;
    State.HPF.DesiredToneLossOK = DesiredToneLossOK;

    State.HPF.Intermodulation = struct();
    State.HPF.Intermodulation.Input = InputIMDMetrics;
    State.HPF.Intermodulation.Output = OutputIMDMetrics;
    State.HPF.Intermodulation.Comparison = IMDComparisonSummary;
    State.HPF.Intermodulation.IM2Change_dB = IM2Change_dB;
    State.HPF.Intermodulation.IM3Change_dB = IM3Change_dB;

    State.HPF.PowerRatios = struct();
    State.HPF.PowerRatios.Summary = PowerRatioSummary;
    State.HPF.PowerRatios.InputComponentMeasurements = ...
        InputComponentMeasurements;
    State.HPF.PowerRatios.OutputComponentMeasurements = ...
        OutputComponentMeasurements;
    State.HPF.PowerRatios.InputBroadbandNoisePSD_V2PerHz = ...
        InputBroadbandNoisePSD;
    State.HPF.PowerRatios.OutputBroadbandNoisePSD_V2PerHz = ...
        OutputBroadbandNoisePSD;
    State.HPF.PowerRatios.InputDesiredSignalPower_V2 = ...
        InputDesiredSignalPower;
    State.HPF.PowerRatios.OutputDesiredSignalPower_V2 = ...
        OutputDesiredSignalPower;
    State.HPF.PowerRatios.InputBroadbandNoisePower_V2 = ...
        InputBroadbandNoisePower;
    State.HPF.PowerRatios.OutputBroadbandNoisePower_V2 = ...
        OutputBroadbandNoisePower;
    State.HPF.PowerRatios.InputInterferencePower_V2 = ...
        InputInterferencePower;
    State.HPF.PowerRatios.OutputInterferencePower_V2 = ...
        OutputInterferencePower;
    State.HPF.PowerRatios.InputSNR_dB = InputSNR_dB;
    State.HPF.PowerRatios.OutputSNR_dB = OutputSNR_dB;
    State.HPF.PowerRatios.SNRChange_dB = SNRChange_dB;
    State.HPF.PowerRatios.InputSINR_dB = InputSINR_dB;
    State.HPF.PowerRatios.OutputSINR_dB = OutputSINR_dB;
    State.HPF.PowerRatios.SINRChange_dB = SINRChange_dB;
    State.HPF.OverallOK = OverallHPFOK;

    State.CurrentSignal = HPFOutputSignal;

    %% ==========================================
    %% HPF STABILITY ANALYSIS
    %% ==========================================

    % Get implemented HPF
    [HPFSOS, HPFGain] = Filter.DCRemoval();

    % Convert to transfer-function form
    [HPFB, HPFA] = sos2tf(HPFSOS, HPFGain);

    % Calculate poles
    HPFPoles = roots(HPFA);

    % Maximum pole radius
    MaxPoleRadius = max(abs(HPFPoles));

    HPFStable = all(abs(HPFPoles) < 1);

    fprintf("\nHPF STABILITY\n");
    fprintf("Maximum pole radius : %.5f\n", MaxPoleRadius);
    fprintf("Stable              : %s\n", string(HPFStable));

    %% ==========================================
    %% HPF POLE-ZERO STABILITY FIGURE
    %% ==========================================

    if ShowPlots
        figure( ...
            "Name", "DC Attenuation HPF - Pole-Zero Stability", ...
            "Color", "w");

        zplane(HPFB, HPFA);

        grid on;

        title(sprintf( ...
            "DC Attenuation HPF Pole-Zero Stability: " + ...
            "Max Pole Radius = %.5f", ...
            MaxPoleRadius));

        xlabel("Real Part");
        ylabel("Imaginary Part");

        exportgraphics( ...
            gcf, ...
            "DC Attenuation-HPF-Pole-Zero-Stability.png", ...
            "Resolution", 300);
    end
end
