function State = RunDemoSigGen(Config, ShowPlots)
%% HIGH-SPEED ADC-POLYPHASE SIGNAL-CHAIN DEMONSTRATION
%% =======================================================
% Generate and characterize the high-speed low-SNR received signal using
% power, correlation, spectral, time-frequency, and phase-domain analysis.
% Return the generated signal and receiver-known references explicitly so
% that the next approved signal-chain stage can consume them.

if nargin < 1 || nargin > 2 || ...
        ~isa(Config, "HighSpeedDesignConfig")
    error( ...
        'ADCPolyphaseSystemIntegration:InvalidDemoConfiguration', ...
        ['RunDemoSigGen requires a HighSpeedDesignConfig input and ', ...
         'an optional logical ShowPlots input.']);
end

if nargin < 2 || isempty(ShowPlots)
    ShowPlots = true;
end

if ~islogical(ShowPlots) || ~isscalar(ShowPlots)
    error( ...
        'ADCPolyphaseSystemIntegration:InvalidPlotVisibility', ...
        'ShowPlots must be a logical scalar.');
end

P = Config.ADCParams;

Fs = P.getValue("Fs");
Dur = P.getValue("Dur");
FrameLength = P.getValue("FrameLength");

TotalSamples = round(Fs * Dur);
ExpectedFrames = ceil(TotalSamples / FrameLength);

%% ==========================================
%% SIGNAL GENERATOR
%% ==========================================

rng(Config.RandomSeed, "twister");
Generator = SignalGenerator(P);

InputSignal = zeros(TotalSamples, 1);
t = zeros(TotalSamples, 1);

% Retain only the receiver-known desired references used later for
% known-reference cross-correlation and final validation. Unknown
% impairments are intentionally not retained as analysis ground truth.
ReferenceSignals.DataSignal1 = zeros(TotalSamples, 1);
ReferenceSignals.DataSignal2 = zeros(TotalSamples, 1);

while ~Generator.IsDone()
    [InputFrame, TimeFrame, ComponentFrame, FrameInfo] = ...
        Generator.GenNoisyTwoDataSignals();

    SampleLocations = FrameInfo.SampleIndex + 1;

    InputSignal(SampleLocations) = InputFrame;
    t(SampleLocations) = TimeFrame;

    ReferenceSignals.DataSignal1(SampleLocations) = ...
        ComponentFrame.DataSignal1;
    ReferenceSignals.DataSignal2(SampleLocations) = ...
        ComponentFrame.DataSignal2;
end

%% =========================================================
%% RECEIVED-SIGNAL CHARACTERIZATION POLICY
%% =========================================================
% Numerical characterization is deliberately deferred until the analysis
% tools operate on the received composite waveform. The final high-speed
% summary is built from measured correlation, Welch-PSD, Hamming-FFT,
% STFT, component-power, noise, and phase results.
%
% The clean Data-Signal-1 and Data-Signal-2 waveforms are retained only as
% receiver-known references for cross-correlation and for a separate
% validation table. They are not used to calculate the measured summary.

%% ==========================================
%% CORRELATION ANALYSIS
%% ==========================================

Correlation = CorrelationAnalyzer(P, Fs);

% Use one substantial finite observation record. Select its centre from the
% strongest measured frame mean-square value in the received composite,
% rather than from any generator-side envelope or impairment ground truth.
CorrelationRecordLength = min(262144, TotalSamples);

NumObservedFrames = ceil(TotalSamples / FrameLength);
ObservedFrameMeanSquare = zeros(NumObservedFrames, 1);
ObservedFrameCentreIndex = zeros(NumObservedFrames, 1);

for FrameIndex = 1:NumObservedFrames

    FrameStart = (FrameIndex - 1) * FrameLength + 1;
    FrameEnd = min(FrameStart + FrameLength - 1, TotalSamples);
    FrameIndices = FrameStart:FrameEnd;

    ObservedFrameMeanSquare(FrameIndex) = ...
        mean(InputSignal(FrameIndices).^2);

    ObservedFrameCentreIndex(FrameIndex) = ...
        round((FrameStart + FrameEnd) / 2);
end

[~, StrongestObservedFrame] = ...
    max(ObservedFrameMeanSquare);

CorrelationCentreIndex = ...
    ObservedFrameCentreIndex(StrongestObservedFrame);

CorrelationStartIndex = ...
    max(1, CorrelationCentreIndex - floor(CorrelationRecordLength / 2));

CorrelationEndIndex = ...
    CorrelationStartIndex + CorrelationRecordLength - 1;

if CorrelationEndIndex > TotalSamples
    CorrelationEndIndex = TotalSamples;
    CorrelationStartIndex = ...
        max(1, CorrelationEndIndex - CorrelationRecordLength + 1);
end

CorrelationIndices = ...
    CorrelationStartIndex:CorrelationEndIndex;

CorrelationObservedRaw = ...
    InputSignal(CorrelationIndices);

CorrelationData1Reference = ...
    ReferenceSignals.DataSignal1(CorrelationIndices);

CorrelationData2Reference = ...
    ReferenceSignals.DataSignal2(CorrelationIndices);

% Keep the raw composite for autocorrelation so the DC term is retained.
% Remove only the mean for known-reference cross-correlation, where a large
% DC term does not help detect either zero-mean data waveform.
CorrelationObservedZeroMean = ...
    CorrelationObservedRaw - mean(CorrelationObservedRaw);

CorrelationMaxLag = ...
    CorrelationRecordLength - 1;


%% ------------------------------------------
%% AUTOCORRELATION: UNKNOWN COMPOSITE SIGNAL
%% ------------------------------------------

[AutoCorrelationValue, ~, AutoLagTime] = ...
    Correlation.AutoCorrelation( ...
        CorrelationObservedRaw, ...
        CorrelationMaxLag, ...
        "coeff");
%% ==========================================
%% WELCH PSD OF AUTOCORRELATION OBSERVATION RECORD
%% ==========================================

Spectrum = SpectrumAnalyzer(P, Fs);

[PSDFreq, PSD] = Spectrum.HammingPSD(CorrelationObservedRaw);

% Convert the raw power density to dBV^2/Hz for a professional Y-axis
PSD_dB = 10 * log10(max(PSD, realmin("double")));


% The desired signals are receiver-known quantities. The input impairments
% are not supplied to the analysis. Detect them directly from the received
% observation record.
%
% DC is estimated from the received-signal mean.
DetectedDCOffset = ...
    mean(CorrelationObservedRaw);

PSDWindowLength = ...
    P.getValue("PSDWindowLength");

DCGuardBandwidth = ...
    2 * Fs / PSDWindowLength;

% Keep the compact dominant-peak display used by the demo.
AutoDetectionMask = ...
    PSDFreq > DCGuardBandwidth & PSDFreq <= 8e9;

[AutoSpectralPeaks, AutoSpectralPeakFrequencies] = ...
    findpeaks( ...
        PSD_dB(AutoDetectionMask), ...
        PSDFreq(AutoDetectionMask), ...
        "MinPeakDistance", 0.10e9, ...
         "MinPeakHeight", -40, ...
        "SortStr", "descend", ...
        "NPeaks", 3);

% Blind narrow band-interference search:
% exclude DC and the receiver-known desired-signal band, then select the
% strongest remaining spectral peak. The configured interference frequency
% is deliberately NOT used here.
DesiredBandLower = ...
    min(P.getValue("FData"), P.getValue("FData2")) - 50e6;

DesiredBandUpper = ...
    max(P.getValue("FData"), P.getValue("FData2")) + 50e6;

InterferenceSearchMask = ...
    PSDFreq > DCGuardBandwidth & ...
    PSDFreq <= 8e9 & ...
    ~(PSDFreq >= DesiredBandLower & PSDFreq <= DesiredBandUpper);

InterferenceCandidateIndices = ...
    find(InterferenceSearchMask);

[DetectedInterferencePSDDB, InterferenceLocalIndex] = ...
    max(PSD_dB(InterferenceSearchMask));

DetectedInterferenceIndex = ...
    InterferenceCandidateIndices(InterferenceLocalIndex);

DetectedInterferenceFrequency = ...
    PSDFreq(DetectedInterferenceIndex);

% Estimate the broadband AWGN floor after excluding the known desired band
% and a guard region around the detected narrowband interferer.
NoiseEstimationMask = ...
    InterferenceSearchMask & ...
    abs(PSDFreq - DetectedInterferenceFrequency) > 50e6;

EstimatedAWGNFloorPSDDB = ...
    median(PSD_dB(NoiseEstimationMask));

fprintf("\nAUTOCORRELATION ANALYSIS\n");
fprintf("Correlation record length: %d samples\n", ...
    CorrelationRecordLength);
fprintf("Correlation record duration: %.4f microseconds\n", ...
    CorrelationRecordLength / Fs * 1e6);
fprintf("DC retained in raw autocorrelation: %.4f V measured mean\n", ...
    mean(CorrelationObservedRaw));

fprintf("\nBLIND INPUT-IMPAIRMENT ESTIMATES\n");
fprintf("Estimated DC offset: %.4f V\n", ...
    DetectedDCOffset);
fprintf("Detected unexpected narrowband interferer: %.6f GHz\n", ...
    DetectedInterferenceFrequency / 1e9);
fprintf("Detected interferer PSD: %.2f dBV^2/Hz\n", ...
    DetectedInterferencePSDDB);
fprintf("Estimated broadband AWGN floor: %.2f dBV^2/Hz\n", ...
    EstimatedAWGNFloorPSDDB);

if ~isempty(AutoSpectralPeaks)
    fprintf("Strongest non-DC periodic " + ...
        "components from Welch PSD spectrum:\n");
    for k = 1:length(AutoSpectralPeaks)
        fprintf("  %.6f GHz   %.2f dBV^2/Hz\n", ...
            AutoSpectralPeakFrequencies(k) / 1e9, ...
            AutoSpectralPeaks(k)); % Prints the correct dB value matching your plot
    end
end

%% ==========================================
%% AUTOCORRELATION PLOTS
%% ==========================================

if ShowPlots
figure( ...
    "Name", "Signal Generator - Autocorrelation Analysis", ...
    "Color", "w");

tiledlayout(2, 1, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

% ------------------------------------------
% TILE 1: LAG-DOMAIN AUTOCORRELATION
% ------------------------------------------
AutoLagTime = AutoLagTime * 1e6;

nexttile;

plot( ...
    AutoLagTime, ...
    AutoCorrelationValue, ...
    "LineWidth", 0.8);
grid on;
xlabel("Lag Time (\mu s)");
ylabel("Normalized autocorrelation (Rxx)");
title( ...
    "Symmetric Autocorrelation analysis");
ylim([-0.5 1.5]);

% ------------------------------------------
% TILE 2: MAGNITUDE POWER SPECTRAL DENSITY
% ------------------------------------------
nexttile;
% Standard continuous line plot 
plot(PSDFreq / 1e9, PSD_dB, 'k', 'LineWidth', 1.0); 
hold on;

% DC is retained and therefore appears at 0 Hz.
plot( ...
    0, ...
    PSD_dB(1), ...
    "o", ...
    "LineWidth", 1.2);

text( ...
    0.05, ...
    PSD_dB(1), ...
    "DC", ...
    "VerticalAlignment", "bottom");

for k = 1:length(AutoSpectralPeaks)

    plot( ...
        AutoSpectralPeakFrequencies(k) / 1e9, ...
        AutoSpectralPeaks(k), ...
        "o", ...
        "LineWidth", 1.2);

    text( ...
        AutoSpectralPeakFrequencies(k) / 1e9 + 0.05, ...
        AutoSpectralPeaks(k), ...
        sprintf("%.4f GHz", ...
        AutoSpectralPeakFrequencies(k) / 1e9), ...
        "VerticalAlignment", "bottom");
end

grid on;
xlim([0 8]); % Limit view to your 8 GHz area of interest
xlabel('Frequency (GHz)');
ylabel('PSD (dBV^2/Hz)');
title('Welch PSD of the Autocorrelation Observation Record');
end


%% ===========================================
%% CROSS-CORRELATION: KNOWN DATA REFERENCES
%% ============================================

[CrossData1, ~, ~, ...
        CrossData1Peak, CrossData1DetectedLag, ...
        CrossData1DetectedDelay] = ...
    Correlation.CrossCorrelation( ...
        CorrelationObservedZeroMean, ...
        CorrelationData1Reference, ...
        CorrelationMaxLag, ...
        "coeff");

[CrossData2, ~, ~, ...
        CrossData2Peak, CrossData2DetectedLag, ...
        CrossData2DetectedDelay] = ...
    Correlation.CrossCorrelation( ...
        CorrelationObservedZeroMean, ...
        CorrelationData2Reference, ...
        CorrelationMaxLag, ...
        "coeff");

[CrossFreq1, CrossPSD1] = Spectrum.HammingPSD(CrossData1);

[CrossFreq2, CrossPSD2] = Spectrum.HammingPSD(CrossData2);

% Convert the raw power density to dBV^2/Hz for a professional Y-axis
PSD_dB1 = 10 * log10(max(CrossPSD1, realmin("double")));

PSD_dB2 = 10 * log10(max(CrossPSD2, realmin("double")));


CrossData1SearchMask = ...
    CrossFreq1 >= 0.995e9 & ...
    CrossFreq1 <= 1.006e9;

CrossData2SearchMask = ...
    CrossFreq2 >= 0.995e9 & ...
    CrossFreq2 <= 1.006e9;

CrossData1CandidateIndices = ...
    find(CrossData1SearchMask);

CrossData2CandidateIndices = ...
    find(CrossData2SearchMask);

[~, CrossData1LocalPeakIndex] = ...
    max(CrossPSD1(CrossData1SearchMask));

[~, CrossData2LocalPeakIndex] = ...
    max(CrossPSD2(CrossData2SearchMask));

CrossData1DetectedFrequency = ...
    CrossFreq1( ...
        CrossData1CandidateIndices(CrossData1LocalPeakIndex));

CrossData2DetectedFrequency = ...
    CrossFreq2( ...
        CrossData2CandidateIndices(CrossData2LocalPeakIndex));

CorrelationComponent = [ ...
    "Data Signal 1"; ...
    "Data Signal 2"];

CorrelationReferenceFrequencyGHz = [ ...
    P.getValue("FData"); ...
    P.getValue("FData2")] / 1e9;

CorrelationDetectedFrequencyGHz = [ ...
    CrossData1DetectedFrequency; ...
    CrossData2DetectedFrequency] / 1e9;

CrossCorrelationPeak = [ ...
    CrossData1Peak; ...
    CrossData2Peak];

CrossCorrelationDetectedLag = [ ...
    CrossData1DetectedLag; ...
    CrossData2DetectedLag];

CrossCorrelationDetectedDelayNs = [ ...
    CrossData1DetectedDelay; ...
    CrossData2DetectedDelay] * 1e9;

CrossCorrelationSummary = table( ...
    CorrelationComponent, ...
    CorrelationReferenceFrequencyGHz, ...
    CorrelationDetectedFrequencyGHz, ...
    CrossCorrelationPeak, ...
    CrossCorrelationDetectedLag, ...
    CrossCorrelationDetectedDelayNs, ...
    'VariableNames', { ...
        'Component', ...
        'ReferenceFrequency_GHz', ...
        'CrossSpectrumDetected_GHz', ...
        'PeakCorrelation', ...
        'DetectedLag_samples', ...
        'DetectedDelay_ns'});

fprintf("\nKNOWN-REFERENCE CROSS-CORRELATION DETECTION\n");
disp(CrossCorrelationSummary);

%% =======================================================
%% CORRELATION DETECTION INTERPRETATION
%% =======================================================
% The cross-correlation results above are measured detection outputs.
% No theoretical processing-gain SNR/SINR values are folded into the
% received-signal measurement summary.

%% ==========================================
%% CROSS-CORRELATION FREQUENCY-DOMAIN PLOTS
%% ==========================================

if ShowPlots
figure( ...
    "Name", "Signal Generator - Cross-Correlation Detection", ...
    "Color", "w");

CrossLayout = tiledlayout(2, 1, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

Peak_dB1 = PSD_dB1(CrossData1CandidateIndices(CrossData1LocalPeakIndex));
Peak_dB2 = PSD_dB2(CrossData2CandidateIndices(CrossData2LocalPeakIndex));

% ------------------------------------------
% DATA SIGNAL 1
% ------------------------------------------
nexttile;

plot( ...
    CrossFreq1(CrossData1SearchMask) / 1e9, ...
    PSD_dB1(CrossData1SearchMask), ...
    "LineWidth", 1.0);

hold on;

plot( ...
    CrossData1DetectedFrequency / 1e9, ...
    Peak_dB1, ...
    "o", ...
    "LineWidth", 1.3, ...
    "MarkerFaceColor", "r"); % Makes the peak visually prominent

text(CrossData1DetectedFrequency / 1e9 + 0.0002, Peak_dB1, ...
    sprintf('  %.2f dB/Hz', Peak_dB1), ...
    'VerticalAlignment', 'middle', 'FontWeight', 'bold');

grid on;
xlabel("Frequency (GHz)");
ylabel("Correlation PSD (dB/Hz)");
title(sprintf( ...
    "Known-Reference Cross-Correlation Spectrum: Data Signal 1 Detected " + ...
"at %.6f GHz (%.2f dB/Hz)", ...
    CrossData1DetectedFrequency / 1e9, Peak_dB1));

% ------------------------------------------
% DATA SIGNAL 2
% ------------------------------------------
nexttile;

plot( ...
    CrossFreq2(CrossData2SearchMask) / 1e9, ...
    PSD_dB2(CrossData2SearchMask), ... 
    "LineWidth", 1.0);

hold on;

plot( ...
    CrossData2DetectedFrequency / 1e9, ...
    Peak_dB2, ...
    "o", ...
    "LineWidth", 1.3, ...
    "MarkerFaceColor", "r");

text(CrossData2DetectedFrequency / 1e9 + 0.0002, Peak_dB2, ...
    sprintf('  %.2f dB/Hz', Peak_dB2), ...
    'VerticalAlignment', 'middle', 'FontWeight', 'bold');

grid on;
xlabel("Frequency (GHz)");
ylabel("Correlation PSD (dB/Hz)");
title(sprintf( ...
    "Known-Reference Cross-Correlation Spectrum: " + ...
    "Data Signal 2 Detected at %.6f GHz (%.2f dB/Hz)", ...
    CrossData2DetectedFrequency / 1e9, Peak_dB2));

title(CrossLayout, ...
    "Known-Reference Detection in the Noise-Dominated Composite Signal");
end

%% ==================
%% SPECTRUM ANALYSIS
%% ==================

Spectrum = SpectrumAnalyzer(P, Fs);

[HammingFreq, HammingMagnitude] = ...
    Spectrum.HammingFFT(InputSignal);

[STFTSpectrum, STFTFreq, STFTTime] = ...
    Spectrum.HammingSTFT(InputSignal);

% Use the same Hamming analysis window for both phase representations so
% magnitude and phase refer to the same received record and FFT grid.
[PhaseFreq, WrappedPhase] = ...
    Spectrum.PhaseSpectrum( ...
        InputSignal, ...
        "wrapped", ...
        "hamming");

[UnwrappedPhaseFreq, UnwrappedPhase] = ...
    Spectrum.PhaseSpectrum( ...
        InputSignal, ...
        "unwrapped", ...
        "hamming");

if ~isequal(PhaseFreq, UnwrappedPhaseFreq)
    error("Wrapped and unwrapped phase frequency grids must match.");
end

%% ==========================================
%% HAMMING STFT - TIME-FREQUENCY LOCALIZATION
%% ==========================================

STFTMagnitudeDB = 20 * log10( ...
    max(abs(STFTSpectrum), realmin("double")));

STFTNoiseBand = STFTFreq >= 2e9 & STFTFreq <= 3e9;
STFTNoiseReferenceDB = median( ...
    STFTMagnitudeDB(STFTNoiseBand, :), ...
    "all");

STFTRelativeToNoiseDB = ...
    STFTMagnitudeDB - STFTNoiseReferenceDB;

STFTTimeMicroseconds = STFTTime * 1e6;
STFTTimeSpan = ...
    STFTTimeMicroseconds(end) - STFTTimeMicroseconds(1);

STFTLabelTimeLeft = ...
    STFTTimeMicroseconds(1) + 0.02 * STFTTimeSpan;
STFTLabelTimeRight = ...
    STFTTimeMicroseconds(end) - 0.02 * STFTTimeSpan;

% A common display range makes the three STFT views directly comparable.
% Values at or below the median noise reference are intentionally pushed
% toward the bottom of the color scale so deterministic components stand out.
STFTDisplayLimits = [0 25];

if ShowPlots
figure( ...
    "Name", "Signal Generator - Hamming STFT", ...
    "Color", "w");

STFTLayout = tiledlayout(3, 1, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

% ------------------------------------------
% DC / LOW-FREQUENCY REGION
% ------------------------------------------
STFTDCAxes = nexttile;
imagesc( ...
    STFTDCAxes, ...
    STFTTimeMicroseconds, ...
    STFTFreq / 1e6, ...
    STFTRelativeToNoiseDB);

axis(STFTDCAxes, "xy");

ylim(STFTDCAxes, [0 10]);

clim(STFTDCAxes, STFTDisplayLimits);

grid(STFTDCAxes, "on");
hold(STFTDCAxes, "on");

yline(STFTDCAxes, ...
    0, ...
    "--w", ...
    "LineWidth", 1.2);

text( ...
    STFTDCAxes, ...
    STFTLabelTimeLeft, ...
    1.0, ...
    "DC", ...
    "Color", "w", ...
    "FontWeight", "bold", ...
    "VerticalAlignment", "bottom");

ylabel(STFTDCAxes, "Frequency (MHz)");
title(STFTDCAxes, ...
    "Low-Frequency View: DC Component");

% ------------------------------------------
% DATA-BAND REGION
% ------------------------------------------
STFTDataAxes = nexttile;

imagesc( ...
    STFTDataAxes, ...
    STFTTimeMicroseconds, ...
    STFTFreq / 1e9, ...
    STFTRelativeToNoiseDB);

axis(STFTDataAxes, "xy");
ylim(STFTDataAxes, [0.995 1.006]);
clim(STFTDataAxes, STFTDisplayLimits);
grid(STFTDataAxes, "on");
hold(STFTDataAxes, "on");

yline(STFTDataAxes, ...
    P.getValue("FData") / 1e9, ...
    "--w", ...
    "LineWidth", 1.2);
yline(STFTDataAxes, ...
    P.getValue("FData2") / 1e9, ...
    "--w", ...
    "LineWidth", 1.2);

text( ...
    STFTDataAxes, ...
    STFTLabelTimeLeft, ...
    P.getValue("FData") / 1e9 - 0.0015, ...
    "Data 1", ...
    "Color", "w", ...
    "FontWeight", "bold", ...
    "VerticalAlignment", "top");

text( ...
    STFTDataAxes, ...
    STFTLabelTimeRight, ...
    P.getValue("FData2") / 1e9 + 0.0015, ...
    "Data 2", ...
    "Color", "w", ...
    "FontWeight", "bold", ...
    "HorizontalAlignment", "right", ...
    "VerticalAlignment", "bottom");

ylabel(STFTDataAxes, "Frequency (GHz)");
title(STFTDataAxes, ...
    "Data-Band Time Evolution: Data 1 and Data 2 ");

% ------------------------------------------
% INTERFERENCE REGION
% ------------------------------------------
STFTInterferenceAxes = nexttile;

imagesc( ...
    STFTInterferenceAxes, ...
    STFTTimeMicroseconds, ...
    STFTFreq / 1e9, ...
    STFTRelativeToNoiseDB);

axis(STFTInterferenceAxes, "xy");

DetectedInterferenceGHz = ...
    DetectedInterferenceFrequency / 1e9;

ylim(STFTInterferenceAxes, ...
    [DetectedInterferenceGHz - 0.20, ...
     DetectedInterferenceGHz + 0.20]);

clim(STFTInterferenceAxes, STFTDisplayLimits);
grid(STFTInterferenceAxes, "on");
hold(STFTInterferenceAxes, "on");

yline(STFTInterferenceAxes, ...
    DetectedInterferenceGHz, ...
    "--w", ...
    "LineWidth", 1.2);

text( ...
    STFTInterferenceAxes, ...
    STFTLabelTimeLeft, ...
    DetectedInterferenceGHz + 0.025, ...
    sprintf("Detected interferer: %.4f GHz", ...
        DetectedInterferenceGHz), ...
    "Color", "w", ...
    "FontWeight", "bold", ...
    "VerticalAlignment", "bottom");

xlabel(STFTInterferenceAxes, "Time (microseconds)");
ylabel(STFTInterferenceAxes, "Frequency (GHz)");
title(STFTInterferenceAxes, ...
    "High Interference Signal");

linkaxes( ...
    [STFTDCAxes STFTDataAxes STFTInterferenceAxes], ...
    "x");

STFTColorbar = colorbar(STFTInterferenceAxes);
STFTColorbar.Layout.Tile = "east";
STFTColorbar.Label.String = ...
    "Magnitude relative to median noise floor (dB)";

title(STFTLayout, ...
    "Hamming STFT: Time Localization Used to Select the Resolution Interval");
end

%% ==========================================
%% HAMMING-WINDOW PHASE-SPECTRUM ANALYSIS
%% ==========================================
% Wrapped phase is used for the phase of individual deterministic
% components. Unwrapped phase is retained as the continuous phase-spectrum
% representation across frequency. Large unwrapped values include the
% accumulated +/-2*pi branch history and are not treated as independent
% source-phase values for isolated components.

HammingMagnitudeDB = ...
    20 * log10( ...
        max(HammingMagnitude, realmin("double")));

PhaseNoiseFloorDB = ...
    median(HammingMagnitudeDB( ...
        HammingFreq > DCGuardBandwidth & ...
        HammingFreq <= 8e9 & ...
        ~(HammingFreq >= DesiredBandLower & ...
          HammingFreq <= DesiredBandUpper) & ...
        abs(HammingFreq - DetectedInterferenceFrequency) > 50e6));

PhaseComponentName = [ ...
    "DC"; ...
    "Data Signal 1"; ...
    "Data Signal 2"; ...
    "Detected Interferer"];

PhaseComponentFrequency = [ ...
    0; ...
    CrossData1DetectedFrequency; ...
    CrossData2DetectedFrequency; ...
    DetectedInterferenceFrequency];

NumPhaseComponents = ...
    numel(PhaseComponentFrequency);

PhaseBinIndex = ...
    zeros(NumPhaseComponents, 1);

PhaseMeasuredFrequency = ...
    zeros(NumPhaseComponents, 1);

DetectedWrappedPhase = ...
    zeros(NumPhaseComponents, 1);

DetectedUnwrappedPhase = ...
    zeros(NumPhaseComponents, 1);

PhaseMagnitudeDB = ...
    zeros(NumPhaseComponents, 1);

for k = 1:NumPhaseComponents

    [~, PhaseBinIndex(k)] = ...
        min(abs( ...
            PhaseFreq - ...
            PhaseComponentFrequency(k)));

    PhaseMeasuredFrequency(k) = ...
        PhaseFreq(PhaseBinIndex(k));

    DetectedWrappedPhase(k) = ...
        WrappedPhase(PhaseBinIndex(k));

    DetectedUnwrappedPhase(k) = ...
        UnwrappedPhase(PhaseBinIndex(k));

    PhaseMagnitudeDB(k) = ...
        HammingMagnitudeDB(PhaseBinIndex(k));
end

PhaseMagnitudeAboveNoiseDB = ...
    PhaseMagnitudeDB - PhaseNoiseFloorDB;

PhaseSummary = table( ...
    PhaseComponentName, ...
    PhaseMeasuredFrequency / 1e9, ...
    DetectedWrappedPhase, ...
    rad2deg(DetectedWrappedPhase), ...
    DetectedUnwrappedPhase, ...
    PhaseMagnitudeDB, ...
    PhaseMagnitudeAboveNoiseDB, ...
    'VariableNames', { ...
        'Component', ...
        'MeasuredFrequency_GHz', ...
        'WrappedPhase_rad', ...
        'WrappedPhase_deg', ...
        'UnwrappedPhase_rad', ...
        'HammingMagnitude_dBV', ...
        'MagnitudeAboveMedianNoise_dB'});

fprintf("\nHAMMING-WINDOW PHASE-SPECTRUM ANALYSIS\n");
fprintf("Wrapped phase is used for individual component angles.\n");
fprintf("Unwrapped phase is shown as the continuous frequency-domain ");
fprintf("representation and includes branch-history multiples of 2*pi.\n\n");
disp(PhaseSummary);

% Plot the complete Hamming-windowed phase spectrum over the same 0-8 GHz
% analysis range used elsewhere in the received-signal characterization.
PhaseDisplayMask = ...
    PhaseFreq <= 8e9;

if ShowPlots
figure( ...
    "Name", "Signal Generator - Wrapped and Unwrapped Phase Spectrum", ...
    "Color", "w");

PhaseLayout = tiledlayout(2, 1, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

% ------------------------------------------
% WRAPPED HAMMING PHASE SPECTRUM
% ------------------------------------------
nexttile;

plot( ...
    PhaseFreq(PhaseDisplayMask) / 1e9, ...
    WrappedPhase(PhaseDisplayMask), ...
    ".", ...
    "MarkerSize", 3);

hold on;

plot( ...
    PhaseMeasuredFrequency / 1e9, ...
    DetectedWrappedPhase, ...
    "o", ...
    "LineWidth", 1.3);

for k = 1:NumPhaseComponents
    text( ...
        PhaseMeasuredFrequency(k) / 1e9, ...
        DetectedWrappedPhase(k), ...
        "  " + PhaseComponentName(k), ...
        "VerticalAlignment", "bottom");
end

yline(pi, "--", "HandleVisibility", "off");
yline(-pi, "--", "HandleVisibility", "off");
yline(0, ":", "HandleVisibility", "off");
grid on;

xlim([0 8]);
ylim([-pi pi]);
xlabel("Frequency (GHz)");
ylabel("Wrapped phase (rad)");
title("Wrapped Hamming FFT Phase Spectrum");
legend("Phase spectrum", "Detected components", "Location", "best");

% ------------------------------------------
% UNWRAPPED HAMMING PHASE SPECTRUM
% ------------------------------------------
nexttile;

plot( ...
    PhaseFreq(PhaseDisplayMask) / 1e9, ...
    UnwrappedPhase(PhaseDisplayMask), ...
    ".", ...
    "MarkerSize", 3);

hold on;

plot( ...
    PhaseMeasuredFrequency / 1e9, ...
    DetectedUnwrappedPhase, ...
    "o", ...
    "LineWidth", 1.3);

for k = 1:NumPhaseComponents
    text( ...
        PhaseMeasuredFrequency(k) / 1e9, ...
        DetectedUnwrappedPhase(k), ...
        "  " + PhaseComponentName(k), ...
        "VerticalAlignment", "bottom");
end

yline(0, ":", "HandleVisibility", "off");
grid on;

xlim([0 8]);
xlabel("Frequency (GHz)");
ylabel("Unwrapped phase (rad)");
title("Unwrapped Hamming FFT Phase Spectrum");
legend("Phase spectrum", "Detected components", "Location", "best");

title(PhaseLayout, ...
    "Received-Signal Hamming Phase Spectrum");
end

%% ==========================================
%% AWGN RMS ESTIMATION FROM WELCH PSD
%% ==========================================

NoisePSDMask = ...
    PSDFreq > DCGuardBandwidth & ...
    PSDFreq <= Fs/2 & ...
    ~(PSDFreq >= DesiredBandLower & ...
    PSDFreq <= DesiredBandUpper) & ...
    abs(PSDFreq - DetectedInterferenceFrequency) > 50e6;

% Estimate the white-noise power spectral density directly from PSD bins
% outside DC, the receiver-known desired band, and the blindly detected
% narrowband interference region.
EstimatedAWGNPSD = mean(PSD(NoisePSDMask));

% For a one-sided PSD of a real signal, the white-noise bandwidth extends
% from DC to Nyquist.
NoiseBandwidth = Fs / 2;

EstimatedAWGNPower = ...
    EstimatedAWGNPSD * NoiseBandwidth;

EstimatedAWGNRMS = ...
    sqrt(EstimatedAWGNPower);

fprintf("\nWELCH-PSD BROADBAND-NOISE ESTIMATION\n");
fprintf("Estimated AWGN PSD   : %.6e V^2/Hz\n", ...
    EstimatedAWGNPSD);
fprintf("Estimated AWGN power : %.6e V^2\n", ...
    EstimatedAWGNPower);
fprintf("Estimated AWGN RMS   : %.4f V RMS\n", ...
    EstimatedAWGNRMS);

%% =======================================================
%% COMPONENT POWER AND AMPLITUDE FROM MEASURED PSD
%% =======================================================

% The desired-component frequencies come from the preceding
% known-reference cross-correlation measurements. The interference
% frequency comes from the preceding blind PSD search. DC is measured at
% zero frequency. No generator-side impairment values are supplied here.
PowerMeasurementNames = [ ...
    "DC"; ...
    "Data Signal 1"; ...
    "Data Signal 2"; ...
    "Detected Interferer"];

PowerMeasurementFrequencies = [ ...
    0; ...
    CrossData1DetectedFrequency; ...
    CrossData2DetectedFrequency; ...
    DetectedInterferenceFrequency];

ComponentMeasurements = ...
    Spectrum.MeasureComponentPowerAmplitude( ...
        PSD, ...
        PSDFreq, ...
        PSDWindowLength, ...
        PowerMeasurementFrequencies, ...
        PowerMeasurementNames);

% Preserve the sign of the received DC term. PSD power gives DC magnitude
% only; the received-signal mean provides its sign.
MeasuredSignedDC = mean(CorrelationObservedRaw);

% Measured desired-signal, interference, SNR, and SINR values.
MeasuredDesiredSignalPower = ...
    ComponentMeasurements.ComponentPower_V2(2) + ...
    ComponentMeasurements.ComponentPower_V2(3);

MeasuredInterferencePower = ...
    ComponentMeasurements.ComponentPower_V2(4);

MeasuredInputSNR = ...
    10 * log10( ...
        MeasuredDesiredSignalPower / ...
        EstimatedAWGNPower);

MeasuredInputSINR = ...
    10 * log10( ...
        MeasuredDesiredSignalPower / ...
        (EstimatedAWGNPower + MeasuredInterferencePower));

fprintf("\nPSD COMPONENT POWER / AMPLITUDE MEASUREMENT\n");
disp(ComponentMeasurements);

%% =======================================================
%% CONSOLIDATE FFT, STFT, CORRELATION, PSD, AND PHASE DATA
%% =======================================================

NumMeasuredComponents = ...
    height(ComponentMeasurements);

HammingMeasuredMagnitudeDB = ...
    zeros(NumMeasuredComponents, 1);

STFTPeakAboveNoiseDB = ...
    zeros(NumMeasuredComponents, 1);

SummaryWrappedPhase = ...
    zeros(NumMeasuredComponents, 1);

for k = 1:NumMeasuredComponents

    MeasuredFrequency = ...
        ComponentMeasurements.MeasuredFrequency_Hz(k);

    [~, HammingBin] = ...
        min(abs(HammingFreq - MeasuredFrequency));

    HammingMeasuredMagnitudeDB(k) = ...
        20 * log10( ...
            max(HammingMagnitude(HammingBin), ...
                realmin("double")));

    [~, STFTBin] = ...
        min(abs(STFTFreq - MeasuredFrequency));

    STFTPeakAboveNoiseDB(k) = ...
        max(STFTRelativeToNoiseDB(STFTBin, :));

    [~, SummaryPhaseBin] = ...
        min(abs(PhaseFreq - MeasuredFrequency));

    SummaryWrappedPhase(k) = ...
        WrappedPhase(SummaryPhaseBin);
end

SummaryCrossCorrelationPeak = [ ...
    NaN; ...
    CrossData1Peak; ...
    CrossData2Peak; ...
    NaN];

MeasuredComponentSummary = table( ...
    ComponentMeasurements.Component, ...
    ComponentMeasurements.MeasuredFrequency_Hz / 1e9, ...
    ComponentMeasurements.ComponentPower_V2, ...
    ComponentMeasurements.NoisePower_V2, ...
    ComponentMeasurements.RMSAmplitude_V, ...
    ComponentMeasurements.EquivalentPeakAmplitude_V, ...
    SummaryCrossCorrelationPeak, ...
    HammingMeasuredMagnitudeDB, ...
    STFTPeakAboveNoiseDB, ...
    SummaryWrappedPhase, ...
    rad2deg(SummaryWrappedPhase), ...
    'VariableNames', { ...
        'Component', ...
        'MeasuredFrequency_GHz', ...
        'ComponentPower_V2', ...
        'LocalNoisePower_V2', ...
        'RMSAmplitude_V', ...
        'EquivalentPeakAmplitude_V', ...
        'CrossCorrelationPeak', ...
        'HammingMagnitude_dBV', ...
        'STFTPeakAboveNoise_dB', ...
        'WrappedPhase_rad', ...
        'WrappedPhase_deg'});

%% ==========================================
%% TWO-TONE INTERMODULATION BASELINE
%% ==========================================
% Establish the received-signal IM2 / IM3 baseline before any downstream
% HPF, LPF, AGC, sampling, quantization, or encoding stage is applied.

DetectedDesiredFrequencies = [ ...
    CrossData1DetectedFrequency; ...
    CrossData2DetectedFrequency];

SignalGeneratorIMDMetrics = ...
    MeasureADCIntermodulationPerformance( ...
        InputSignal, DetectedDesiredFrequencies, P, Fs);

SignalGeneratorIMDSummary = table( ...
    ["Worst IM2"; "Worst IM3"], ...
    [SignalGeneratorIMDMetrics.WorstIM2_dBc; ...
     SignalGeneratorIMDMetrics.WorstIM3_dBc], ...
    'VariableNames', { ...
        'Metric', ...
        'ReceivedSignal_dBc'});
%% =======================================================
%% HIGH-SPEED RECEIVED-SIGNAL MEASUREMENT SUMMARY
%% =======================================================

fprintf("\n");
fprintf("===============================================================\n");
fprintf("HIGH-SPEED RECEIVED-SIGNAL MEASUREMENT SUMMARY\n");
fprintf("===============================================================\n");

fprintf("Acquisition / observation\n");
fprintf("  Sampling frequency              : %.3f GS/s\n", ...
    Fs / 1e9);
fprintf("  Signal duration                 : %.4f microseconds\n", ...
    Dur * 1e6);
fprintf("  Generated samples               : %d\n", ...
    TotalSamples);
fprintf("  Generated frames                : %d\n", ...
    ExpectedFrames);
fprintf("  Analysis-record length          : %d samples\n", ...
    CorrelationRecordLength);
fprintf("  Analysis-record duration        : %.4f microseconds\n", ...
    CorrelationRecordLength / Fs * 1e6);

fprintf("\nMeasured received impairments\n");
fprintf("  Signed DC offset                : %.4f V\n", ...
    MeasuredSignedDC);
fprintf("  Broadband AWGN PSD              : %.6e V^2/Hz\n", ...
    EstimatedAWGNPSD);
fprintf("  Broadband AWGN power            : %.6e V^2\n", ...
    EstimatedAWGNPower);
fprintf("  Broadband AWGN RMS              : %.4f V RMS\n", ...
    EstimatedAWGNRMS);
fprintf("  Detected interferer             : %.6f GHz\n", ...
    DetectedInterferenceFrequency / 1e9);

fprintf("\nMeasured power ratios\n");
fprintf("  Desired power (Data 1 + Data 2) : %.6e V^2\n", ...
    MeasuredDesiredSignalPower);
fprintf("  Interference power              : %.6e V^2\n", ...
    MeasuredInterferencePower);
fprintf("  Input SNR                       : %.3f dB\n", ...
    MeasuredInputSNR);
fprintf("  Input SINR                      : %.3f dB\n", ...
    MeasuredInputSINR);

fprintf("\nTwo-tone intermodulation baseline\n");
disp(SignalGeneratorIMDSummary);

fprintf("\nMeasured deterministic-component characterization\n");
disp(MeasuredComponentSummary);

%% =======================================================
%% SEPARATE KNOWN-REFERENCE VALIDATION
%% =======================================================
% This table is intentionally separate from the measured summary above.
% It is used only to verify that the two detected desired components agree
% with the receiver-known reference signals. These reference values do not
% feed the measured SNR, SINR, noise, interference, power, or phase results.

ReferenceData1RMS = ...
    sqrt(mean(CorrelationData1Reference.^2));

ReferenceData2RMS = ...
    sqrt(mean(CorrelationData2Reference.^2));

ReferenceEquivalentPeakAmplitude = ...
    sqrt(2) * [ ...
        ReferenceData1RMS; ...
        ReferenceData2RMS];

MeasuredDesiredEquivalentPeakAmplitude = ...
    ComponentMeasurements.EquivalentPeakAmplitude_V(2:3);

ReferenceFrequencyGHz = [ ...
    P.getValue("FData"); ...
    P.getValue("FData2")] / 1e9;

MeasuredDesiredFrequencyGHz = ...
    ComponentMeasurements.MeasuredFrequency_Hz(2:3) / 1e9;

FrequencyError_kHz = ...
    abs( ...
        ComponentMeasurements.MeasuredFrequency_Hz(2:3) - ...
        [P.getValue("FData"); P.getValue("FData2")]) / 1e3;

AmplitudeError_V = ...
    MeasuredDesiredEquivalentPeakAmplitude - ...
    ReferenceEquivalentPeakAmplitude;

AmplitudeErrorPercent = ...
    100 * abs(AmplitudeError_V) ./ ...
    max(ReferenceEquivalentPeakAmplitude, realmin("double"));

ReferenceValidation = table( ...
    ["Data Signal 1"; "Data Signal 2"], ...
    ReferenceFrequencyGHz, ...
    MeasuredDesiredFrequencyGHz, ...
    FrequencyError_kHz, ...
    ReferenceEquivalentPeakAmplitude, ...
    MeasuredDesiredEquivalentPeakAmplitude, ...
    AmplitudeError_V, ...
    AmplitudeErrorPercent, ...
    'VariableNames', { ...
        'Component', ...
        'ReferenceFrequency_GHz', ...
        'MeasuredFrequency_GHz', ...
        'FrequencyError_kHz', ...
        'ReferenceEquivalentPeak_V', ...
        'MeasuredEquivalentPeak_V', ...
        'AmplitudeError_V', ...
        'AmplitudeError_percent'});

fprintf("\n");
fprintf("===============================================================\n");
fprintf("KNOWN-REFERENCE VALIDATION - NOT USED TO FORM MEASURED SUMMARY\n");
fprintf("===============================================================\n");
disp(ReferenceValidation);

%% =======================================================
%% SIGNAL-GENERATOR STAGE OUTPUT
%% =======================================================
% Do not expose the generator's internally known DC, AWGN, or interferer
% waveforms as analysis ground truth. Only the receiver-known desired
% references and quantities measured from the received composite continue
% through the demonstration pipeline.

State = struct();

State.Config = Config;
State.Parameters = P;

State.Fs = Fs;
State.Time = t;

State.InputSignal = InputSignal;
State.CurrentSignal = InputSignal;
State.ReferenceSignals = ReferenceSignals;

State.SignalGenerator = struct();
State.SignalGenerator.TotalSamples = TotalSamples;
State.SignalGenerator.FrameLength = FrameLength;
State.SignalGenerator.NumFrames = ExpectedFrames;

% Preserve the exact finite observation record used for the signal-
% generator measurements. Downstream stages use the same sample interval
% for before/after SNR and SINR comparisons, eliminating record-selection
% bias from the reported stage-to-stage changes.
State.SignalGenerator.AnalysisRecord = struct();
State.SignalGenerator.AnalysisRecord.StartIndex = ...
    CorrelationStartIndex;
State.SignalGenerator.AnalysisRecord.EndIndex = ...
    CorrelationEndIndex;
State.SignalGenerator.AnalysisRecord.Length = ...
    CorrelationRecordLength;

State.SignalGenerator.Intermodulation = struct();
State.SignalGenerator.Intermodulation.Metrics = ...
    SignalGeneratorIMDMetrics;
State.SignalGenerator.Intermodulation.Summary = ...
    SignalGeneratorIMDSummary;

State.SignalGenerator.Measurements = struct();
State.SignalGenerator.Measurements.ComponentSummary = ...
    MeasuredComponentSummary;
State.SignalGenerator.Measurements.ReferenceValidation = ...
    ReferenceValidation;
State.SignalGenerator.Measurements.SignedDC_V = ...
    MeasuredSignedDC;
State.SignalGenerator.Measurements.AWGNPSD_V2PerHz = ...
    EstimatedAWGNPSD;
State.SignalGenerator.Measurements.AWGNPower_V2 = ...
    EstimatedAWGNPower;
State.SignalGenerator.Measurements.AWGNRMS_V = ...
    EstimatedAWGNRMS;
State.SignalGenerator.Measurements.InterferenceFrequency_Hz = ...
    DetectedInterferenceFrequency;
State.SignalGenerator.Measurements.DesiredFrequencies_Hz = ...
    DetectedDesiredFrequencies;
State.SignalGenerator.Measurements.InputSNR_dB = ...
    MeasuredInputSNR;
State.SignalGenerator.Measurements.InputSINR_dB = ...
    MeasuredInputSINR;
end
