function State = RunDemoSampler(State, ShowPlots)
%% =======================================================
%% FRAME-BASED ADC SAMPLER DEMONSTRATION
%% =======================================================
% Move the actual low-SNR AGC output through the existing stateful
% ADC.Sampler implementation, characterize the rate change and spectral
% preservation, and pass the resulting ADC-rate record to the next stage.
% This stage performs ideal sampling only: it does not filter, quantize,
% or model aperture jitter.


    %% ==========================================
    %% VALIDATE INTERSTAGE INPUT CONTRACT
    %% ==========================================

    if nargin < 1 || nargin > 2 || ~isstruct(State)
        error('RunDemoSampler:InvalidState', ...
            ['RunDemoSampler requires a State structure input and an ', ...
             'optional logical ShowPlots input.']);
    end

    if nargin < 2 || isempty(ShowPlots)
        ShowPlots = true;
    end

    if ~islogical(ShowPlots) || ~isscalar(ShowPlots)
        error('RunDemoSampler:InvalidPlotVisibility', ...
            'ShowPlots must be a logical scalar.');
    end

    RequiredFields = [ ...
        "Parameters"; ...
        "Fs"; ...
        "Time"; ...
        "CurrentSignal"; ...
        "AGC"; ...
        "SignalGenerator"];

    for k = 1:numel(RequiredFields)
        if ~isfield(State, RequiredFields(k))
            error('RunDemoSampler:MissingStateField', ...
                'State.%s is required.', RequiredFields(k));
        end
    end

    P = State.Parameters;
    InputSamplingFrequency = double(State.Fs);
    InputTime = double(State.Time(:));
    InputSignal = double(State.CurrentSignal(:));

    validateattributes( ...
        InputSamplingFrequency, ...
        {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, ...
        mfilename, ...
        'State.Fs');

    if isempty(InputSignal)
        error('RunDemoSampler:EmptyInput', ...
            'The sampler requires a nonempty AGC output signal.');
    end

    if ~isreal(InputSignal) || any(~isfinite(InputSignal))
        error('RunDemoSampler:InvalidInputSignal', ...
            'State.CurrentSignal must be finite and real valued.');
    end

    if numel(InputTime) ~= numel(InputSignal)
        error('RunDemoSampler:StateLengthMismatch', ...
            'State.Time and State.CurrentSignal must have equal lengths.');
    end

    ConfiguredInputSamplingFrequency = P.getValue("Fs");
    InputRateTolerance = max( ...
        1e-3, 32 * eps(ConfiguredInputSamplingFrequency));
    InputRateOK = abs( ...
        InputSamplingFrequency - ConfiguredInputSamplingFrequency) <= ...
        InputRateTolerance;

    if ~InputRateOK
        error('RunDemoSampler:ConfiguredRateMismatch', ...
            ['State.Fs must match the high-rate sampling frequency ', ...
             'held by State.Parameters.']);
    end

    FrameLength = P.getValue("FrameLength");
    DownsamplingFactor = P.getValue("DF");

    validateattributes( ...
        FrameLength, ...
        {'numeric'}, ...
        {'scalar', 'integer', 'finite', 'positive'}, ...
        mfilename, ...
        'FrameLength');
    validateattributes( ...
        DownsamplingFactor, ...
        {'numeric'}, ...
        {'scalar', 'integer', 'finite', 'positive'}, ...
        mfilename, ...
        'DF');

    NumberInputSamples = numel(InputSignal);
    NumberFrames = ceil(NumberInputSamples / FrameLength);
    ExpectedOutputSamples = ceil( ...
        NumberInputSamples / DownsamplingFactor);
    ExpectedADCSamplingFrequency = ...
        InputSamplingFrequency / DownsamplingFactor;


    %% ==========================================
    %% FRAME-BASED ADC SAMPLING
    %% ==========================================
    % One handle instance is retained across every frame so ADC.Sampler's
    % global phase state never restarts at a frame boundary.

    SamplerModel = ADC(P);

    SampledSignal = zeros(ExpectedOutputSamples, 1);
    SampleIndex = zeros(ExpectedOutputSamples, 1);

    OutputWriteIndex = 1;
    ADCSamplingFrequency = NaN;

    for FrameIndex = 1:NumberFrames
        FrameStart = (FrameIndex - 1) * FrameLength + 1;
        FrameEnd = min( ...
            FrameStart + FrameLength - 1, NumberInputSamples);
        FrameIndices = FrameStart:FrameEnd;

        [SampledFrame, SampleIndexFrame, FrameSamplingFrequency] = ...
            SamplerModel.Sampler(InputSignal(FrameIndices));

        if isnan(ADCSamplingFrequency)
            ADCSamplingFrequency = FrameSamplingFrequency;
        elseif FrameSamplingFrequency ~= ADCSamplingFrequency
            error('RunDemoSampler:FrameRateMismatch', ...
                'The ADC sampling frequency changed between frames.');
        end

        NumberFrameOutputSamples = numel(SampledFrame);
        OutputEndIndex = ...
            OutputWriteIndex + NumberFrameOutputSamples - 1;

        if OutputEndIndex > ExpectedOutputSamples
            error('RunDemoSampler:OutputAllocationExceeded', ...
                'ADC.Sampler produced more samples than expected.');
        end

        if NumberFrameOutputSamples > 0
            OutputLocations = OutputWriteIndex:OutputEndIndex;

            SampledSignal(OutputLocations) = SampledFrame;
            SampleIndex(OutputLocations) = SampleIndexFrame;

            OutputWriteIndex = OutputEndIndex + 1;
        end
    end

    NumberOutputSamples = OutputWriteIndex - 1;

    if NumberOutputSamples ~= ExpectedOutputSamples
        error('RunDemoSampler:OutputCountMismatch', ...
            'ADC.Sampler produced an unexpected number of samples.');
    end

    if any(SampleIndex < 0) || ...
            any(SampleIndex > NumberInputSamples - 1) || ...
            any(SampleIndex ~= fix(SampleIndex))
        error('RunDemoSampler:InvalidGlobalSampleIndex', ...
            'ADC.Sampler returned an invalid global source-sample index.');
    end

    SampleTime = InputTime(SampleIndex + 1);


    %% ==========================================
    %% SAMPLING-RATE AND GLOBAL-PHASE CHECKS
    %% ==========================================

    ExpectedSampleIndex = ...
        (0:DownsamplingFactor:NumberInputSamples - 1)';

    OutputRateTolerance = max( ...
        1e-3, 32 * eps(ExpectedADCSamplingFrequency));

    OutputRateOK = abs( ...
        ADCSamplingFrequency - ExpectedADCSamplingFrequency) <= ...
        OutputRateTolerance;
    SampleCountOK = ...
        NumberOutputSamples == ExpectedOutputSamples;
    GlobalSamplingPhaseOK = ...
        isequal(SampleIndex, ExpectedSampleIndex);
    FiniteOutputOK = ...
        all(isfinite(SampledSignal));

    SampleCountReductionPercentage = ...
        100 * (1 - NumberOutputSamples / NumberInputSamples);


    %% ==========================================
    %% RECEIVER-MEASURED COMPONENT FREQUENCIES
    %% ==========================================

    if ~isfield(State.SignalGenerator, "AnalysisRecord") || ...
            ~isfield(State.SignalGenerator, "Measurements") || ...
            ~isfield( ...
                State.SignalGenerator.Measurements, ...
                "DesiredFrequencies_Hz") || ...
            ~isfield( ...
                State.SignalGenerator.Measurements, ...
                "InterferenceFrequency_Hz")

        error('RunDemoSampler:MissingSignalAnalysisState', ...
            ['The signal-generator analysis record and receiver-measured ', ...
             'component frequencies are required for sampler analysis.']);
    end

    DetectedDesiredFrequencies = ...
        double(State.SignalGenerator.Measurements.DesiredFrequencies_Hz(:));
    DetectedInterferenceFrequency = double( ...
        State.SignalGenerator.Measurements.InterferenceFrequency_Hz);

    if numel(DetectedDesiredFrequencies) ~= 2 || ...
            any(~isfinite(DetectedDesiredFrequencies)) || ...
            ~isscalar(DetectedInterferenceFrequency) || ...
            ~isfinite(DetectedInterferenceFrequency)
        error('RunDemoSampler:InvalidMeasuredFrequencies', ...
            ['Exactly two finite desired frequencies and one finite ', ...
             'interference frequency are required.']);
    end

    ADCNyquistFrequency = ADCSamplingFrequency / 2;
    DesiredBandBelowNyquistOK = ...
        all(DetectedDesiredFrequencies > 0 & ...
        DetectedDesiredFrequencies < ADCNyquistFrequency);

    if ~DesiredBandBelowNyquistOK
        error('RunDemoSampler:DesiredBandAboveNyquist', ...
            'The detected desired-signal band must lie below ADC Nyquist.');
    end

    OutputAliasFrequency = LocalFoldToFirstNyquist( ...
        DetectedInterferenceFrequency, ADCSamplingFrequency);


    %% ==========================================
    %% FULL-RECORD HAMMING-FFT TONE PRESERVATION
    %% ==========================================

    InputSpectrum = SpectrumAnalyzer(P, InputSamplingFrequency);
    OutputSpectrum = SpectrumAnalyzer(P, ADCSamplingFrequency);

    [InputFFTFrequency, InputMagnitude] = ...
        InputSpectrum.HammingFFT(InputSignal);
    [OutputFFTFrequency, OutputMagnitude] = ...
        OutputSpectrum.HammingFFT(SampledSignal);

    InputTrueFrequencyResolution = ...
        InputSamplingFrequency / NumberInputSamples;
    OutputTrueFrequencyResolution = ...
        ADCSamplingFrequency / NumberOutputSamples;

    ResolutionTolerance = max( ...
        1e-9, 32 * eps(InputTrueFrequencyResolution));
    MatchedTrueResolutionOK = abs( ...
        OutputTrueFrequencyResolution - ...
        InputTrueFrequencyResolution) <= ResolutionTolerance;

    TrueFrequencyResolution = ...
        max(InputTrueFrequencyResolution, ...
        OutputTrueFrequencyResolution);
    InputFFTBinSpacing = ...
        InputFFTFrequency(2) - InputFFTFrequency(1);
    OutputFFTDisplayBinSpacing = ...
        OutputFFTFrequency(2) - OutputFFTFrequency(1);

    % HammingFFT zero-pads the shorter sampler output to the configured
    % full-record FFT length. Retain that finer grid for plotting, but
    % decimate it back to the true-resolution grid for an unbiased
    % before/after frequency and level comparison.
    FFTGridTolerance = max( ...
        1e-3, 32 * eps(ADCSamplingFrequency));
    InputComparisonFFTMask = ...
        InputFFTFrequency <= ADCNyquistFrequency + FFTGridTolerance;
    InputComparisonFFTFrequency = ...
        InputFFTFrequency(InputComparisonFFTMask);
    InputComparisonMagnitude = ...
        InputMagnitude(InputComparisonFFTMask);

    OutputComparisonIndices = ...
        (1:DownsamplingFactor:numel(OutputFFTFrequency))';
    OutputComparisonFFTFrequency = ...
        OutputFFTFrequency(OutputComparisonIndices);
    OutputComparisonMagnitude = ...
        OutputMagnitude(OutputComparisonIndices);

    if numel(InputComparisonFFTFrequency) ~= ...
            numel(OutputComparisonFFTFrequency) || ...
            any(abs( ...
                InputComparisonFFTFrequency - ...
                OutputComparisonFFTFrequency) > FFTGridTolerance)
        error('RunDemoSampler:FFTGridMismatch', ...
            ['Input and output Hamming-FFT comparison grids must agree ', ...
             'through the ADC Nyquist frequency.']);
    end

    ComparisonFFTBinSpacing = ...
        OutputComparisonFFTFrequency(2) - ...
        OutputComparisonFFTFrequency(1);

    SortedDesiredFrequencies = sort(DetectedDesiredFrequencies);
    MinimumToneSeparation = min(diff(SortedDesiredFrequencies));

    if MinimumToneSeparation <= 0
        error('RunDemoSampler:UnresolvedDesiredFrequencies', ...
            'The two desired frequencies must be distinct.');
    end

    ToneSearchHalfWidth = 0.4 * MinimumToneSeparation;

    [InputMeasuredToneFrequency, InputMeasuredToneMagnitude] = ...
        LocalMeasureFFTPeaks( ...
            InputComparisonFFTFrequency, ...
            InputComparisonMagnitude, ...
            DetectedDesiredFrequencies, ...
            ToneSearchHalfWidth);

    [OutputMeasuredToneFrequency, OutputMeasuredToneMagnitude] = ...
        LocalMeasureFFTPeaks( ...
            OutputComparisonFFTFrequency, ...
            OutputComparisonMagnitude, ...
            DetectedDesiredFrequencies, ...
            ToneSearchHalfWidth);

    FrequencyChange_Hz = ...
        OutputMeasuredToneFrequency - InputMeasuredToneFrequency;
    FrequencyError_Bins = ...
        abs(FrequencyChange_Hz) / TrueFrequencyResolution;

    InputToneLevel_dBV = 20 * log10(max( ...
        InputMeasuredToneMagnitude, realmin("double")));
    OutputToneLevel_dBV = 20 * log10(max( ...
        OutputMeasuredToneMagnitude, realmin("double")));
    ToneLevelChange_dB = ...
        OutputToneLevel_dBV - InputToneLevel_dBV;

    MaximumFrequencyErrorBins = ...
        P.getValue("MaxSamplerFrequencyErrorBins");
    MaximumToneLevelChange_dB = ...
        P.getValue("MaxSamplerToneLevelChange");

    ToneFrequencyPreservationOK = ...
        all(FrequencyError_Bins <= MaximumFrequencyErrorBins);
    ToneLevelPreservationOK = ...
        all(abs(ToneLevelChange_dB) <= MaximumToneLevelChange_dB);

    TonePreservationSummary = table( ...
        ["Data Signal 1"; "Data Signal 2"], ...
        DetectedDesiredFrequencies, ...
        InputMeasuredToneFrequency, ...
        OutputMeasuredToneFrequency, ...
        FrequencyChange_Hz, ...
        FrequencyError_Bins, ...
        InputToneLevel_dBV, ...
        OutputToneLevel_dBV, ...
        ToneLevelChange_dB, ...
        'VariableNames', { ...
            'Component', ...
            'ReceiverTargetFrequency_Hz', ...
            'BeforeSamplerFrequency_Hz', ...
            'AfterSamplerFrequency_Hz', ...
            'FrequencyChange_Hz', ...
            'FrequencyError_Bins', ...
            'BeforeSamplerLevel_dBV', ...
            'AfterSamplerLevel_dBV', ...
            'LevelChange_dB'});


    %% ==========================================
    %% MATCHED-PHYSICAL-TIME HAMMING-WELCH PSD
    %% ==========================================
    % The input and output PSD windows cover the same physical duration.
    % Scaling all Welch lengths by DF keeps the frequency grids identical
    % without constructing another ADCParameters object.

    AnalysisStartIndex = ...
        State.SignalGenerator.AnalysisRecord.StartIndex;
    AnalysisEndIndex = ...
        State.SignalGenerator.AnalysisRecord.EndIndex;

    if ~isscalar(AnalysisStartIndex) || ...
            ~isscalar(AnalysisEndIndex) || ...
            AnalysisStartIndex < 1 || ...
            AnalysisEndIndex > NumberInputSamples || ...
            AnalysisStartIndex ~= fix(AnalysisStartIndex) || ...
            AnalysisEndIndex ~= fix(AnalysisEndIndex) || ...
            AnalysisEndIndex < AnalysisStartIndex
        error('RunDemoSampler:InvalidSignalAnalysisRecord', ...
            'The signal-generator analysis-record indices are invalid.');
    end

    InputAnalysisIndices = AnalysisStartIndex:AnalysisEndIndex;
    InputAnalysisRecord = InputSignal(InputAnalysisIndices);

    OutputAnalysisMask = ...
        SampleIndex >= AnalysisStartIndex - 1 & ...
        SampleIndex <= AnalysisEndIndex - 1;
    OutputAnalysisRecord = SampledSignal(OutputAnalysisMask);

    InputPSDWindowLength = P.getValue("PSDWindowLength");
    InputPSDOverlapLength = P.getValue("PSDOverlapLength");
    InputPSDFFTLength = P.getValue("PSDFFTLength");

    InputPSDLengths = [ ...
        InputPSDWindowLength, ...
        InputPSDOverlapLength, ...
        InputPSDFFTLength];

    if any(mod(InputPSDLengths, DownsamplingFactor) ~= 0)
        error('RunDemoSampler:UnmatchedPSDConfiguration', ...
            ['PSD window, overlap, and FFT lengths must be divisible ', ...
             'by DF for matched-time sampler analysis.']);
    end

    OutputPSDWindowLength = ...
        InputPSDWindowLength / DownsamplingFactor;
    OutputPSDOverlapLength = ...
        InputPSDOverlapLength / DownsamplingFactor;
    OutputPSDFFTLength = ...
        InputPSDFFTLength / DownsamplingFactor;

    if numel(InputAnalysisRecord) < InputPSDWindowLength || ...
            numel(OutputAnalysisRecord) < OutputPSDWindowLength
        error('RunDemoSampler:AnalysisRecordTooShort', ...
            ['The matched input/output records must each contain one ', ...
             'complete Welch analysis window.']);
    end

    [InputPSDFrequency, InputPowerPSD] = ...
        InputSpectrum.HammingPSD(InputAnalysisRecord);

    [OutputPSDFrequency, OutputPowerPSD] = ...
        LocalHammingPSD( ...
            OutputAnalysisRecord, ...
            ADCSamplingFrequency, ...
            OutputPSDWindowLength, ...
            OutputPSDOverlapLength, ...
            OutputPSDFFTLength);

    PSDGridTolerance = max( ...
        1e-3, 32 * eps(ADCSamplingFrequency));
    InputCommonMask = ...
        InputPSDFrequency <= ADCNyquistFrequency + PSDGridTolerance;
    InputCommonPSDFrequency = ...
        InputPSDFrequency(InputCommonMask);
    InputCommonPowerPSD = ...
        InputPowerPSD(InputCommonMask);

    if numel(InputCommonPSDFrequency) ~= numel(OutputPSDFrequency) || ...
            any(abs( ...
                InputCommonPSDFrequency - OutputPSDFrequency) > ...
                PSDGridTolerance)
        error('RunDemoSampler:PSDGridMismatch', ...
            ['Matched-time input and output Welch PSD grids must agree ', ...
             'through the ADC Nyquist frequency.']);
    end

    CommonPSDFrequency = OutputPSDFrequency;
    CommonPSDSpacing = ...
        CommonPSDFrequency(2) - CommonPSDFrequency(1);

    InputComponentNames = [ ...
        "Data Signal 1"; ...
        "Data Signal 2"; ...
        "Detected Interferer"];
    OutputComponentNames = [ ...
        "Data Signal 1"; ...
        "Data Signal 2"; ...
        "Predicted Interference Alias"];

    InputComponentFrequencies = [ ...
        DetectedDesiredFrequencies; ...
        DetectedInterferenceFrequency];
    OutputComponentFrequencies = [ ...
        DetectedDesiredFrequencies; ...
        OutputAliasFrequency];

    InputComponentMeasurements = ...
        InputSpectrum.MeasureComponentPowerAmplitude( ...
            InputPowerPSD, ...
            InputPSDFrequency, ...
            InputPSDWindowLength, ...
            InputComponentFrequencies, ...
            InputComponentNames);

    OutputComponentMeasurements = ...
        OutputSpectrum.MeasureComponentPowerAmplitude( ...
            OutputPowerPSD, ...
            OutputPSDFrequency, ...
            OutputPSDWindowLength, ...
            OutputComponentFrequencies, ...
            OutputComponentNames);

    DesiredBandLower = ...
        min(DetectedDesiredFrequencies) - 50e6;
    DesiredBandUpper = ...
        max(DetectedDesiredFrequencies) + 50e6;
    AliasGuardHalfWidth = 50e6;
    DCGuardBandwidth = ...
        2 * InputSamplingFrequency / InputPSDWindowLength;

    BroadbandNoiseMask = ...
        CommonPSDFrequency > DCGuardBandwidth & ...
        ~(CommonPSDFrequency >= DesiredBandLower & ...
        CommonPSDFrequency <= DesiredBandUpper) & ...
        abs(CommonPSDFrequency - OutputAliasFrequency) > ...
        AliasGuardHalfWidth;

    if ~any(BroadbandNoiseMask)
        error('RunDemoSampler:EmptyNoiseMeasurementBand', ...
            'No matched common-band PSD bins remain for noise measurement.');
    end

    UpstreamAGCSNR_dB = ...
        State.AGC.PowerRatios.OutputSNR_dB;

    UpstreamAGCSINR_dB = ...
        State.AGC.PowerRatios.OutputSINR_dB;

    InputBroadbandNoisePower = sum( ...
        InputCommonPowerPSD(BroadbandNoiseMask)) * CommonPSDSpacing;
    OutputBroadbandNoisePower = sum( ...
        OutputPowerPSD(BroadbandNoiseMask)) * CommonPSDSpacing;

    InputDesiredSignalPower = sum( ...
        InputComponentMeasurements.ComponentPower_V2(1:2));
    OutputDesiredSignalPower = sum( ...
        OutputComponentMeasurements.ComponentPower_V2(1:2));

    InputInterferencePower = ...
        InputComponentMeasurements.ComponentPower_V2(3);
    OutputAliasPower = ...
        OutputComponentMeasurements.ComponentPower_V2(3);

    InputSNR_dB = 10 * log10( ...
        max(InputDesiredSignalPower, realmin("double")) / ...
        max(InputBroadbandNoisePower, realmin("double")));
    OutputSNR_dB = 10 * log10( ...
        max(OutputDesiredSignalPower, realmin("double")) / ...
        max(OutputBroadbandNoisePower, realmin("double")));

    InputSINR_dB = 10 * log10( ...
        max(InputDesiredSignalPower, realmin("double")) / ...
        max( ...
            InputBroadbandNoisePower + InputInterferencePower, ...
            realmin("double")));
    OutputSINR_dB = 10 * log10( ...
        max(OutputDesiredSignalPower, realmin("double")) / ...
        max( ...
            OutputBroadbandNoisePower + OutputAliasPower, ...
            realmin("double")));

    SNRChange_dB = OutputSNR_dB - InputSNR_dB;
    SINRChange_dB = OutputSINR_dB - InputSINR_dB;
    AliasPowerChange_dB = 10 * log10( ...
        max(OutputAliasPower, realmin("double")) / ...
        max(InputInterferencePower, realmin("double")));

    MaximumSNRDegradation_dB = ...
        P.getValue("MaxSamplerSNRDegradation");
    MaximumSINRDegradation_dB = ...
        P.getValue("MaxSamplerSINRDegradation");

    SNRPreservationOK = ...
        SNRChange_dB >= -MaximumSNRDegradation_dB;
    SINRPreservationOK = ...
        SINRChange_dB >= -MaximumSINRDegradation_dB;

    PowerRatioSummary = table( ...
        ["Sampler Input (0-5 GHz)"; "Sampler Output (0-5 GHz)"], ...
        [InputDesiredSignalPower; OutputDesiredSignalPower], ...
        [InputBroadbandNoisePower; OutputBroadbandNoisePower], ...
        [InputInterferencePower; OutputAliasPower], ...
        [InputSNR_dB; OutputSNR_dB], ...
        [InputSINR_dB; OutputSINR_dB], ...
        'VariableNames', { ...
            'Observation', ...
            'DesiredSignalPower_V2', ...
            'CommonBandNoisePower_V2', ...
            'InterferenceOrAliasPower_V2', ...
            'SNR_dB', ...
            'SINR_dB'});


    %% ==========================================
    %% TWO-TONE INTERMODULATION COMPARISON
    %% ==========================================
    % Measure the same IM2 / IM3 product locations before and after ideal
    % sampling. Each side uses its own physical sampling frequency while the
    % full records retain the same true frequency resolution.

    InputIMDMetrics = ...
        MeasureADCIntermodulationPerformance( ...
            InputSignal, ...
            DetectedDesiredFrequencies, ...
            P, ...
            InputSamplingFrequency);

    OutputIMDMetrics = ...
        MeasureADCIntermodulationPerformance( ...
            SampledSignal, ...
            DetectedDesiredFrequencies, ...
            P, ...
            ADCSamplingFrequency);

    IM2Change_dB = ...
        OutputIMDMetrics.WorstIM2_dBc - ...
        InputIMDMetrics.WorstIM2_dBc;

    IM3Change_dB = ...
        OutputIMDMetrics.WorstIM3_dBc - ...
        InputIMDMetrics.WorstIM3_dBc;

    IMDComparisonSummary = table( ...
        ["Worst IM2"; "Worst IM3"], ...
        [InputIMDMetrics.WorstIM2_dBc; ...
         InputIMDMetrics.WorstIM3_dBc], ...
        [OutputIMDMetrics.WorstIM2_dBc; ...
         OutputIMDMetrics.WorstIM3_dBc], ...
        [IM2Change_dB; IM3Change_dB], ...
        'VariableNames', { ...
            'Metric', ...
            'BeforeSampler_dBc', ...
            'AfterSampler_dBc', ...
            'Change_dB'});
    %% ==========================================
    %% NEXT-STAGE FULL-SCALE OBSERVATION
    %% ==========================================
    % The ideal sampler does not clip. This observation only reports how
    % many retained samples presently exceed the following quantizer's
    % input limits; it is intentionally excluded from sampler compliance.

    QuantizerPeak = P.getValue("Vfs") / 2;
    SamplesOutsideQuantizerRange = ...
        sum(abs(SampledSignal) > QuantizerPeak);
    SamplesOutsideQuantizerRangePercentage = ...
        100 * SamplesOutsideQuantizerRange / NumberOutputSamples;


    %% ==========================================
    %% OVERALL SAMPLER PERFORMANCE DECISION
    %% ==========================================

    OverallSamplerOK = ...
        InputRateOK && ...
        OutputRateOK && ...
        SampleCountOK && ...
        GlobalSamplingPhaseOK && ...
        FiniteOutputOK && ...
        DesiredBandBelowNyquistOK && ...
        MatchedTrueResolutionOK && ...
        ToneFrequencyPreservationOK && ...
        ToneLevelPreservationOK && ...
        SNRPreservationOK && ...
        SINRPreservationOK;


    %% ==========================================
    %% COMMAND-WINDOW PERFORMANCE SUMMARY
    %% ==========================================

    fprintf("\n");
    fprintf("===============================================================\n");
    fprintf("FRAME-BASED ADC SAMPLER PERFORMANCE SUMMARY\n");
    fprintf("===============================================================\n");

    fprintf("Design and implementation\n");
    fprintf("  Input                            : AGC output\n");
    fprintf("  Sampling model                   : Ideal clock; no aperture jitter\n");
    fprintf("  Input sampling frequency         : %.6f GS/s\n", ...
        InputSamplingFrequency / 1e9);
    fprintf("  Downsampling factor              : %d\n", ...
        DownsamplingFactor);
    fprintf("  ADC sampling frequency           : %.6f GS/s\n", ...
        ADCSamplingFrequency / 1e9);
    fprintf("  ADC Nyquist frequency            : %.6f GHz\n", ...
        ADCNyquistFrequency / 1e9);
    fprintf("  Input / output frame length      : %d / %d samples\n", ...
        FrameLength, ceil(FrameLength / DownsamplingFactor));
    fprintf("  Processed frames                 : %d\n", ...
        SamplerModel.FramesProcessed);
    fprintf("  Input / output sample count      : %d / %d\n", ...
        NumberInputSamples, NumberOutputSamples);
    fprintf("  Sample-count reduction           : %.3f %%\n", ...
        SampleCountReductionPercentage);
    fprintf("  Global retained indices          : 0:%d:%d\n", ...
        DownsamplingFactor, SampleIndex(end));

    fprintf("\nFrequency resolution\n");
    fprintf("  True full-record resolution      : %.6f kHz\n", ...
        TrueFrequencyResolution / 1e3);
    fprintf("  Input Hamming-FFT bin spacing    : %.6f kHz\n", ...
        InputFFTBinSpacing / 1e3);
    fprintf("  Output plotted FFT bin spacing   : %.6f kHz\n", ...
        OutputFFTDisplayBinSpacing / 1e3);
    fprintf("  Shared compliance-grid spacing   : %.6f kHz\n", ...
        ComparisonFFTBinSpacing / 1e3);
    fprintf("  Zero-padding interpretation      : Display interpolation only\n");

    fprintf("\nMeasured Data 1 / Data 2 preservation\n");
    disp(TonePreservationSummary);
    fprintf("  Allowed frequency error          : %.3f true-resolution bin(s)\n", ...
        MaximumFrequencyErrorBins);
    fprintf("  Allowed absolute level change    : %.3f dB\n", ...
        MaximumToneLevelChange_dB);

    fprintf("\nInterference alias observation\n");
    fprintf("  Input interference frequency     : %.6f GHz\n", ...
        DetectedInterferenceFrequency / 1e9);
    fprintf("  Predicted first-Nyquist alias    : %.6f GHz\n", ...
        OutputAliasFrequency / 1e9);
    fprintf("  Input residual interference power: %.6e V^2\n", ...
        InputInterferencePower);
    fprintf("  Output measured alias power      : %.6e V^2\n", ...
        OutputAliasPower);
    fprintf("  Alias/input power change         : %+.6f dB\n", ...
        AliasPowerChange_dB);

    fprintf("\nTwo-tone intermodulation comparison\n");
    disp(IMDComparisonSummary);
    fprintf( ...
        "  Positive change means the IM product became stronger after sampling.\n");

    fprintf("\nSampler common-band power-ratio comparison\n");
    fprintf("  Upstream AGC reported SNR        : %.6f dB\n", ...
        UpstreamAGCSNR_dB);
    fprintf("  Upstream AGC reported SINR       : %.6f dB\n", ...
        UpstreamAGCSINR_dB);
    fprintf("  Input / output Welch windows     : %d / %d samples\n", ...
        InputPSDWindowLength, OutputPSDWindowLength);
    fprintf("  Common physical window duration  : %.6f microseconds\n", ...
        InputPSDWindowLength / InputSamplingFrequency * 1e6);
    disp(PowerRatioSummary);
    fprintf("  SNR change (after - before)      : %+.6f dB\n", ...
        SNRChange_dB);
    fprintf("  Allowed SNR degradation          : %.6f dB\n", ...
        MaximumSNRDegradation_dB);
    fprintf("  SINR change (after - before)     : %+.6f dB\n", ...
        SINRChange_dB);
    fprintf("  Allowed SINR degradation         : %.6f dB\n", ...
        MaximumSINRDegradation_dB);

    fprintf("\nSampler compliance\n");
    fprintf("  Output-rate requirement          : %s\n", ...
        LocalPassFail(OutputRateOK));
    fprintf("  Sample-count requirement         : %s\n", ...
        LocalPassFail(SampleCountOK));
    fprintf("  Global-phase continuity          : %s\n", ...
        LocalPassFail(GlobalSamplingPhaseOK));
    fprintf("  Desired band below Nyquist       : %s\n", ...
        LocalPassFail(DesiredBandBelowNyquistOK));
    fprintf("  Desired-tone frequency           : %s\n", ...
        LocalPassFail(ToneFrequencyPreservationOK));
    fprintf("  Desired-tone level               : %s\n", ...
        LocalPassFail(ToneLevelPreservationOK));
    fprintf("  SNR preservation                 : %s\n", ...
        LocalPassFail(SNRPreservationOK));
    fprintf("  SINR preservation                : %s\n", ...
        LocalPassFail(SINRPreservationOK));

    fprintf("\nNext quantizer input observation (not a sampler criterion)\n");
    fprintf("  Quantizer input limits           : %.6f to %+.6f V\n", ...
        -QuantizerPeak, QuantizerPeak);
    fprintf("  Retained samples outside limits  : %d of %d (%.9f %%)\n", ...
        SamplesOutsideQuantizerRange, ...
        NumberOutputSamples, ...
        SamplesOutsideQuantizerRangePercentage);

    if OverallSamplerOK
        fprintf("\nOverall sampler performance       : PASS\n");
    else
        fprintf("\nOverall sampler performance       : FAIL\n");
    end


    %% ==========================================
    %% APPROVED SAMPLER FIGURES
    %% ==========================================

    if ShowPlots
        PerformanceAnalyzer = SamplerAnalyzer(P);

        PerformanceAnalyzer.PlotSamplingOperation( ...
            InputTime, ...
            InputSignal, ...
            SampleTime, ...
            SampledSignal, ...
            SampleIndex);

        PlotData = struct();
        PlotData.InputFFTFrequency = InputFFTFrequency;
        PlotData.InputMagnitude = InputMagnitude;
        PlotData.OutputFFTFrequency = OutputFFTFrequency;
        PlotData.OutputMagnitude = OutputMagnitude;
        PlotData.CommonPSDFrequency = CommonPSDFrequency;
        PlotData.InputCommonPSD = InputCommonPowerPSD;
        PlotData.OutputPSD = OutputPowerPSD;
        PlotData.DesiredFrequencies = DetectedDesiredFrequencies;
        PlotData.InputInterferenceFrequency = ...
            DetectedInterferenceFrequency;
        PlotData.OutputAliasFrequency = OutputAliasFrequency;
        PlotData.ADCSamplingFrequency = ADCSamplingFrequency;

        PerformanceAnalyzer.PlotSpectralComparison(PlotData);
    end


    %% ==========================================
    %% STORE SAMPLER OUTPUT AND MEASUREMENTS
    %% ==========================================

    State.Sampler = struct();
    State.Sampler.OutputSignal = SampledSignal;
    State.Sampler.Time = SampleTime;
    State.Sampler.SampleIndex = SampleIndex;
    State.Sampler.InputSamplingFrequency_Hz = ...
        InputSamplingFrequency;
    State.Sampler.ADCSamplingFrequency_Hz = ...
        ADCSamplingFrequency;
    State.Sampler.ADCNyquistFrequency_Hz = ...
        ADCNyquistFrequency;
    State.Sampler.DownsamplingFactor = DownsamplingFactor;
    State.Sampler.InputSampleCount = NumberInputSamples;
    State.Sampler.OutputSampleCount = NumberOutputSamples;
    State.Sampler.SampleCountReductionPercentage = ...
        SampleCountReductionPercentage;
    State.Sampler.FramesProcessed = SamplerModel.FramesProcessed;
    State.Sampler.TrueFrequencyResolution_Hz = ...
        TrueFrequencyResolution;
    State.Sampler.OutputFFTDisplayBinSpacing_Hz = ...
        OutputFFTDisplayBinSpacing;
    State.Sampler.ComparisonFFTBinSpacing_Hz = ...
        ComparisonFFTBinSpacing;

    State.Sampler.AnalysisRecord = struct();
    State.Sampler.AnalysisRecord.InputStartIndex = AnalysisStartIndex;
    State.Sampler.AnalysisRecord.InputEndIndex = AnalysisEndIndex;
    State.Sampler.AnalysisRecord.InputSampleCount = ...
        numel(InputAnalysisRecord);
    State.Sampler.AnalysisRecord.OutputSampleCount = ...
        numel(OutputAnalysisRecord);
    State.Sampler.AnalysisRecord.InputPSDWindowLength = ...
        InputPSDWindowLength;
    State.Sampler.AnalysisRecord.OutputPSDWindowLength = ...
        OutputPSDWindowLength;

    State.Sampler.TonePreservation = struct();
    State.Sampler.TonePreservation.Summary = ...
        TonePreservationSummary;
    State.Sampler.TonePreservation.FrequencyPreservationOK = ...
        ToneFrequencyPreservationOK;
    State.Sampler.TonePreservation.LevelPreservationOK = ...
        ToneLevelPreservationOK;

    State.Sampler.Intermodulation = struct();
    State.Sampler.Intermodulation.Input = InputIMDMetrics;
    State.Sampler.Intermodulation.Output = OutputIMDMetrics;
    State.Sampler.Intermodulation.Comparison = IMDComparisonSummary;
    State.Sampler.Intermodulation.IM2Change_dB = IM2Change_dB;
    State.Sampler.Intermodulation.IM3Change_dB = IM3Change_dB;

    State.Sampler.Aliasing = struct();
    State.Sampler.Aliasing.InputInterferenceFrequency_Hz = ...
        DetectedInterferenceFrequency;
    State.Sampler.Aliasing.PredictedAliasFrequency_Hz = ...
        OutputAliasFrequency;
    State.Sampler.Aliasing.InputInterferencePower_V2 = ...
        InputInterferencePower;
    State.Sampler.Aliasing.OutputAliasPower_V2 = ...
        OutputAliasPower;
    State.Sampler.Aliasing.PowerChange_dB = ...
        AliasPowerChange_dB;

    State.Sampler.PowerRatios = struct();
    State.Sampler.PowerRatios.Summary = PowerRatioSummary;
    State.Sampler.PowerRatios.InputComponentMeasurements = ...
        InputComponentMeasurements;
    State.Sampler.PowerRatios.OutputComponentMeasurements = ...
        OutputComponentMeasurements;
    State.Sampler.PowerRatios.InputBroadbandNoisePower_V2 = ...
        InputBroadbandNoisePower;
    State.Sampler.PowerRatios.OutputBroadbandNoisePower_V2 = ...
        OutputBroadbandNoisePower;
    State.Sampler.PowerRatios.InputSNR_dB = InputSNR_dB;
    State.Sampler.PowerRatios.OutputSNR_dB = OutputSNR_dB;
    State.Sampler.PowerRatios.SNRChange_dB = SNRChange_dB;
    State.Sampler.PowerRatios.InputSINR_dB = InputSINR_dB;
    State.Sampler.PowerRatios.OutputSINR_dB = OutputSINR_dB;
    State.Sampler.PowerRatios.SINRChange_dB = SINRChange_dB;
    State.Sampler.PowerRatios.SNRPreservationOK = ...
        SNRPreservationOK;
    State.Sampler.PowerRatios.SINRPreservationOK = ...
        SINRPreservationOK;

    State.Sampler.NextQuantizerObservation = struct();
    State.Sampler.NextQuantizerObservation.InputLimit_V = ...
        QuantizerPeak;
    State.Sampler.NextQuantizerObservation.OutsideRangeSampleCount = ...
        SamplesOutsideQuantizerRange;
    State.Sampler.NextQuantizerObservation.OutsideRangePercentage = ...
        SamplesOutsideQuantizerRangePercentage;

    State.Sampler.Compliance = struct();
    State.Sampler.Compliance.InputRateOK = InputRateOK;
    State.Sampler.Compliance.OutputRateOK = OutputRateOK;
    State.Sampler.Compliance.SampleCountOK = SampleCountOK;
    State.Sampler.Compliance.GlobalSamplingPhaseOK = ...
        GlobalSamplingPhaseOK;
    State.Sampler.Compliance.FiniteOutputOK = FiniteOutputOK;
    State.Sampler.Compliance.DesiredBandBelowNyquistOK = ...
        DesiredBandBelowNyquistOK;
    State.Sampler.Compliance.MatchedTrueResolutionOK = ...
        MatchedTrueResolutionOK;
    State.Sampler.Compliance.ToneFrequencyPreservationOK = ...
        ToneFrequencyPreservationOK;
    State.Sampler.Compliance.ToneLevelPreservationOK = ...
        ToneLevelPreservationOK;
    State.Sampler.Compliance.SNRPreservationOK = SNRPreservationOK;
    State.Sampler.Compliance.SINRPreservationOK = SINRPreservationOK;
    State.Sampler.OverallOK = OverallSamplerOK;

    State.CurrentSignal = SampledSignal;
    State.Time = SampleTime;
    State.Fs = ADCSamplingFrequency;
end


function [MeasuredFrequency, PeakMagnitude] = LocalMeasureFFTPeaks( ...
        Frequency, Magnitude, TargetFrequencies, SearchHalfWidth)
%% Measure the strongest Hamming-FFT bin in a nonoverlapping local band.

    Frequency = Frequency(:);
    Magnitude = Magnitude(:);
    TargetFrequencies = TargetFrequencies(:);

    if numel(Frequency) ~= numel(Magnitude)
        error('RunDemoSampler:FFTLengthMismatch', ...
            'FFT frequency and magnitude vectors must have equal lengths.');
    end

    MeasuredFrequency = zeros(size(TargetFrequencies));
    PeakMagnitude = zeros(size(TargetFrequencies));

    for k = 1:numel(TargetFrequencies)
        SearchMask = abs( ...
            Frequency - TargetFrequencies(k)) <= SearchHalfWidth;

        if ~any(SearchMask)
            error('RunDemoSampler:EmptyToneSearchBand', ...
                'No Hamming-FFT bins lie inside a desired-tone search band.');
        end

        CandidateIndices = find(SearchMask);
        [PeakMagnitude(k), LocalPeakIndex] = ...
            max(Magnitude(SearchMask));
        MeasuredFrequency(k) = ...
            Frequency(CandidateIndices(LocalPeakIndex));
    end
end


function AliasFrequency = LocalFoldToFirstNyquist( ...
        InputFrequency, SamplingFrequency)
%% Fold a nonnegative frequency into the real-signal first Nyquist zone.

    AliasFrequency = abs(mod( ...
        InputFrequency + SamplingFrequency / 2, ...
        SamplingFrequency) - SamplingFrequency / 2);
end


function [PSDFrequency, PowerPSD] = LocalHammingPSD( ...
        InputSignal, SamplingFrequency, ...
        WindowLength, OverlapLength, FFTLength)
%% Hamming-Welch PSD with sampler-specific matched-time lengths.

    InputSignal = InputSignal(:);

    if numel(InputSignal) < WindowLength
        error('RunDemoSampler:OutputPSDRecordTooShort', ...
            'The sampler output is shorter than its Welch window.');
    end

    HammingWindow = hamming(WindowLength, "periodic");

    [PowerPSD, PSDFrequency] = pwelch( ...
        InputSignal, ...
        HammingWindow, ...
        OverlapLength, ...
        FFTLength, ...
        SamplingFrequency, ...
        "onesided");
end


function ResultText = LocalPassFail(Condition)
%% Return compact command-window compliance text.

    if Condition
        ResultText = 'PASS';
    else
        ResultText = 'FAIL';
    end
end
