classdef SamplerAnalyzer < handle
    %% ==========================================
    %% FRAME-BASED ADC SAMPLER VISUALIZATION
    %% ==========================================
    properties
        Parameters
    end

    methods
        function obj = SamplerAnalyzer(P)
            %% ===========================
            %% SAMPLER ANALYZER CONSTRUCTOR
            %% ===========================
            obj.Parameters = P;
        end

        function PlotSamplingOperation( ...
                obj, InputTime, InputSignal, SampleTime, SampledSignal)
            %% ==========================================
            %% PLOT HIGH-RATE REFERENCE AND ADC SAMPLES
            %% ==========================================

            InputTime = InputTime(:);
            InputSignal = InputSignal(:);
            SampleTime = SampleTime(:);
            SampledSignal = SampledSignal(:);

            if numel(InputTime) ~= numel(InputSignal) || ...
                    numel(SampleTime) ~= numel(SampledSignal)
                error('SamplerAnalyzer:TimeSignalLengthMismatch', ...
                    ['Each sampler time vector must match its ', ...
                     'corresponding signal vector.']);
            end

            if isempty(InputTime) || isempty(SampleTime)
                error('SamplerAnalyzer:EmptySignal', ...
                    'Sampler plots require nonempty input and output signals.');
            end

            InputSamplingFrequency = obj.Parameters.getValue("Fs");
            DownsamplingFactor = obj.Parameters.getValue("DF");
            ADCSamplingFrequency = ...
                InputSamplingFrequency / DownsamplingFactor;

            % Display twelve cycles of Data Signal 1 around the Gaussian
            % burst centre. This is long enough to show the retained ADC
            % samples without turning the plot into a solid waveform.
            DesiredFrequency = obj.Parameters.getValue("FData");
            PlotCentreTime = obj.Parameters.getValue("mu");
            PlotDuration = 12 / DesiredFrequency;

            PlotStartTime = max( ...
                InputTime(1), PlotCentreTime - PlotDuration / 2);
            PlotEndTime = min( ...
                InputTime(end), PlotCentreTime + PlotDuration / 2);

            InputPlotMask = ...
                InputTime >= PlotStartTime & InputTime <= PlotEndTime;
            SamplePlotMask = ...
                SampleTime >= PlotStartTime & SampleTime <= PlotEndTime;

            if ~any(InputPlotMask) || ~any(SamplePlotMask)
                error('SamplerAnalyzer:EmptyPlotWindow', ...
                    'The selected sampler display interval is empty.');
            end

            figure( ...
                "Name", "Sampler - Time-Domain Sampling Operation", ...
                "Color", "w");

            plot( ...
                InputTime(InputPlotMask) * 1e6, ...
                InputSignal(InputPlotMask), ...
                "LineWidth", 1.1, ...
                "DisplayName", sprintf( ...
                    "Input reference (%.3f GS/s)", ...
                    InputSamplingFrequency / 1e9));

            hold on;

            stem( ...
                SampleTime(SamplePlotMask) * 1e6, ...
                SampledSignal(SamplePlotMask), ...
                "Marker", "o", ...
                "MarkerSize", 4, ...
                "LineWidth", 0.9, ...
                "DisplayName", sprintf( ...
                    "ADC samples (%.3f GS/s)", ...
                    ADCSamplingFrequency / 1e9));

            grid on;
            xlim([PlotStartTime, PlotEndTime] * 1e6);
            xlabel("Time (microseconds)");
            ylabel("Amplitude (V)");
            title(sprintf( ...
                "Ideal Frame-Based Sampling by a Factor of %d", ...
                DownsamplingFactor));
            legend("Location", "best");

            hold off;
        end

        function PlotSpectralComparison(obj, PlotData)
            %% =============================================
            %% PLOT TONE PRESERVATION AND ALIAS-FOLD MAPPING
            %% =============================================

            RequiredFields = [ ...
                "InputFFTFrequency", ...
                "InputMagnitude", ...
                "OutputFFTFrequency", ...
                "OutputMagnitude", ...
                "CommonPSDFrequency", ...
                "InputCommonPSD", ...
                "OutputPSD", ...
                "InputInterferenceFrequency", ...
                "OutputAliasFrequency"];

            for k = 1:numel(RequiredFields)
                if ~isfield(PlotData, RequiredFields(k))
                    error('SamplerAnalyzer:MissingPlotData', ...
                        'PlotData.%s is required.', RequiredFields(k));
                end
            end

            InputFFTFrequency = PlotData.InputFFTFrequency(:);
            InputMagnitude = PlotData.InputMagnitude(:);
            OutputFFTFrequency = PlotData.OutputFFTFrequency(:);
            OutputMagnitude = PlotData.OutputMagnitude(:);
            CommonPSDFrequency = PlotData.CommonPSDFrequency(:);
            InputCommonPSD = PlotData.InputCommonPSD(:);
            OutputPSD = PlotData.OutputPSD(:);

            if numel(InputFFTFrequency) ~= numel(InputMagnitude) || ...
                    numel(OutputFFTFrequency) ~= numel(OutputMagnitude) || ...
                    numel(CommonPSDFrequency) ~= numel(InputCommonPSD) || ...
                    numel(CommonPSDFrequency) ~= numel(OutputPSD)
                error('SamplerAnalyzer:PlotDataLengthMismatch', ...
                    'Each spectral axis must match its corresponding data.');
            end

            InputMagnitude_dBV = ...
                20 * log10(max(InputMagnitude, realmin("double")));
            OutputMagnitude_dBV = ...
                20 * log10(max(OutputMagnitude, realmin("double")));
            InputPSD_dB = ...
                10 * log10(max(InputCommonPSD, realmin("double")));
            OutputPSD_dB = ...
                10 * log10(max(OutputPSD, realmin("double")));

            DesiredFrequency1 = obj.Parameters.getValue("FData");
            DesiredFrequency2 = obj.Parameters.getValue("FData2");
            ADCSamplingFrequency = ...
                obj.Parameters.getValue("Fs") / ...
                obj.Parameters.getValue("DF");

            figure( ...
                "Name", "Sampler - Spectral Preservation and Aliasing", ...
                "Color", "w");

            SpectrumLayout = tiledlayout(3, 1, ...
                "TileSpacing", "compact", ...
                "Padding", "compact");


            %% COMMON ADC BASEBAND PSD

            nexttile;

            plot( ...
                CommonPSDFrequency / 1e9, ...
                InputPSD_dB, ...
                "LineWidth", 1.1, ...
                "DisplayName", "Before sampler");
            hold on;
            plot( ...
                CommonPSDFrequency / 1e9, ...
                OutputPSD_dB, ...
                "--", ...
                "LineWidth", 1.1, ...
                "DisplayName", "After sampler");

            grid on;
            xlim([0, ADCSamplingFrequency / 2e9]);
            xlabel("Frequency (GHz)");
            ylabel("PSD (dBV^2/Hz)");
            title("Matched-Time Welch PSD Within the ADC Nyquist Band");
            legend("Location", "best");
            hold off;


            %% DESIRED-TONE PRESERVATION

            nexttile;

            plot( ...
                InputFFTFrequency / 1e9, ...
                InputMagnitude_dBV, ...
                "LineWidth", 1.1, ...
                "DisplayName", "Before sampler");
            hold on;
            plot( ...
                OutputFFTFrequency / 1e9, ...
                OutputMagnitude_dBV, ...
                "--", ...
                "LineWidth", 1.1, ...
                "DisplayName", "After sampler");

            xline(DesiredFrequency1 / 1e9, ":", "Data 1", ...
                "HandleVisibility", "off");
            xline(DesiredFrequency2 / 1e9, ":", "Data 2", ...
                "HandleVisibility", "off");

            grid on;
            xlim([0.995, 1.006]);
            xlabel("Frequency (GHz)");
            ylabel("Magnitude (dBV)");
            title("Hamming FFT: Desired-Tone Preservation");
            legend("Location", "best");
            hold off;


            %% INTERFERENCE ALIAS-FOLD LOCATION

            nexttile;

            plot( ...
                InputFFTFrequency / 1e9, ...
                InputMagnitude_dBV, ...
                "LineWidth", 1.1, ...
                "DisplayName", "Before sampler");
            hold on;
            plot( ...
                OutputFFTFrequency / 1e9, ...
                OutputMagnitude_dBV, ...
                "--", ...
                "LineWidth", 1.1, ...
                "DisplayName", "After sampler");

            xline( ...
                PlotData.InputInterferenceFrequency / 1e9, ...
                ":", ...
                "Input interferer", ...
                "HandleVisibility", "off");
            xline( ...
                PlotData.OutputAliasFrequency / 1e9, ...
                ":", ...
                "Predicted alias", ...
                "HandleVisibility", "off");

            grid on;
            xlim([3.4, 6.6]);
            xlabel("Frequency (GHz)");
            ylabel("Magnitude (dBV)");
            title("Hamming FFT: 6.2 GHz to 3.8 GHz Alias Mapping");
            legend("Location", "best");
            hold off;

            title(SpectrumLayout, ...
                "Received Signal Before and After ADC Sampling");
        end
    end
end
